### ISSUE TITLE
How to update elixir?

### ISSUE THREAD

**Issue by Butochnikov** [laravel/elixir#102]
my version now:
`"version": "0.10.7",`

current version:
`"version": "0.18.4",`

`npm update` does not update
may be change this?
//package.json
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "latest"  <--- instead of "*"
  }
}
```

**Comment by mabasic** [comment]
It updates just fine for me. Maybe update your nodejs, npm to latest version and try again. Also deleting the `node_modules` dir and running `npm install` solves weird issues sometimes.

**Comment by Butochnikov** [comment]
Why closed? or i had to write here https://github.com/laravel/laravel ?

**Comment by JeffreyWay** [comment]
Because Mario answered your question. Updating npm works just fine.

**Comment by Butochnikov** [comment]
ok, I  try. thanks.
