### ISSUE TITLE
Multiple calls to browserify task run only the last call

### ISSUE THREAD

**Issue by mabasic** [laravel/elixir#103]
Hello,

I have two `mix.browserify` tasks and only the last one gets executed if I run `gulp`:

```
mix.browserify('app.js', null, 'assets/js');
mix.browserify('events.js', 'public/js/eventPage.js', 'assets/js');
```

I have tried chaining them like so:

```
mix.browserify('app.js', null, 'assets/js').browserify('events.js', 'public/js/eventPage.js', 'assets/js');
```

But still only the last call to browserify runs.

I have even tried to to do: 

```
mix.browserify([
        'events.js', 'public/js/eventPage.js', 'assets/js',
        'app.js', null, 'assets/js'
    ]);
```

But I get this error:

```
F:\Repositories\Laranotti\node_modules\laravel-elixir\ingredients\commands\Utilities.js:30
        file = file.replace(dir, '');
                   ^
TypeError: Cannot read property 'replace' of null
    at F:\Repositories\Laranotti\node_modules\laravel-elixir\ingredients\commands\Utilities.js:30:20
    at Array.map (native)
    at prefixDirToFiles (F:\Repositories\Laranotti\node_modules\laravel-elixir\ingredients\commands\Utilities.js:29:18)
    at Object.buildGulpSrc (F:\Repositories\Laranotti\node_modules\laravel-elixir\ingredients\commands\Utilities.js:13:16)
    at Object.browserify (F:\Repositories\Laranotti\node_modules\laravel-elixir\ingredients\browserify.js:65:21)
    at F:\Repositories\Laranotti\gulpfile.js:22:9
    at Elixir (F:\Repositories\Laranotti\node_modules\laravel-elixir\index.js:3:5)
    at Object.<anonymous> (F:\Repositories\Laranotti\gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

I am running Elixir version `0.18.5`.

The thing that I am trying to do is create two files:

- bundle.js - which I load in html
- eventPage.js - which is loaded by the extension in background page

**Comment by Skyrpex** [comment]
Currently, the browserify's ingredient can't handle more than one call to mix.browserify.

@JeffreyWay, I suggest you to take a look at my [laravel-elixir-browserify fork](https://github.com/Skyrpex/laravel-elixir-browserify) which handles multiple browserify calls, and also uses watchify.

**Comment by rdeutz** [comment]
same problem when calling less

**Comment by JeffreyWay** [comment]
You can call less() multiple times. Just make sure that you've updated to the latest version of Elixir.

**Comment by rawcreative** [comment]
@Skyrpex the laravel-elixir-browserify extension no longer works out of the box since the built in browserify task overrides the extension.

**Comment by phaza** [comment]
+1, amazingly annoying. Trying to use this to create a bundle for <head> and a bundle that goes before </body>

**Comment by mabasic** [comment]
I don't know how, but on the current project that I am working on I see two browserify calls:

```
 Running Browserify: ./resources/assets/js/app.js
 Running Browserify: ./resources/assets/js/marine.js
```

and both are getting called and work.

This is my gulpfile:

```
mix.browserify('app.js', 'public/js/app.js', 'resources/assets/js');
mix.browserify('marine.js', 'public/js/marine.js', 'resources/assets/js');
```

Maybe the issue has been fixed somehow.

**Comment by joetannenbaum** [comment]
I'm still having this issue, running Elixir 1.0.1. I see that it logs the following:
```
Running Browserify: ./resources/assets/js/apps/dashboard/app-dev.js
Running Browserify: ./resources/assets/js/apps/catalog/app-dev.js
```
But it only compiles the last one in the list. Here is my gulpfile:
```
mix.browserify('apps/dashboard/app-dev.js', 'public/js/apps/dashboard/app.js');
mix.browserify('apps/catalog/app-dev.js', 'public/js/apps/catalog/app.js');
```
Is anyone else still having this issue?

**Comment by Oyed** [comment]
Yes, still also having this issue.

**Comment by devinfd** [comment]
+1
Recently updated elixir and now it is overriding laravel-elixir-browserify. I think it's great that elixir has a native browserify ingredient but it really needs to support multiple bundles.

**Comment by mabasic** [comment]
I am having the same issue with my latest project, so this issue is still active.

**Comment by JeffreyWay** [comment]
The latest version of Elixir (^2.0.0) supports multiple calls to browserify().

**Comment by mabasic** [comment]
@JeffreyWay Oh tnx, I just updated and everything works great :)

**Comment by JeffreyWay** [comment]
`mix.browserify()` now uses Watchify, when running `gulp watch`.

**Comment by afigienas** [comment]
@JeffreyWay after updated Elixir browserify to ^2.0.0, multiple calls to browserify() only work the first time

**Comment by devinfd** [comment]
@afigienas It works fine for me.
Are you separating your browserify calls like so?
```
mix.browserify('admin.js', 'public/js/admin.js');
mix.browserify('app.js', 'public/js/app.js');
```

**Comment by afigienas** [comment]
@devinfd Yes, I call:
```
mix.browserify('front/app.js', 'public/assets/front/js');
mix.browserify('admin/app.js', 'public/assets/admin/js');
```
First time(if file public/assets/front/js/bundle.js doesn't exist), when I run gulp watch, it works fine. But when I make any changes in front/app.js file, bundle.js file doesn't update. If I comment second line, and run gulp watch again, it works fine

**Comment by devinfd** [comment]
@afigienas I believe that you need to specify the name of the output bundle file. Have you tried that?
```
mix.browserify('front/app.js', 'public/assets/front/js/app.js');
mix.browserify('admin/app.js', 'public/assets/admin/js/app.js');
```

**Comment by afigienas** [comment]
@devinfd thanks! 
When I specify files names It almost works. But it work when I kill gulp watch command and run it again.  But target files doesn't updates without killing and re-running gulp watch command.

**Comment by devinfd** [comment]
Yea, if you make a change to your gulp file while watching your assets you need to reset the watch in order to take in those changes.

Devin Dombrowski
dddesigns3@gmail.com

**Comment by afigienas** [comment]
No no, I mean, if I made changes in public/assets/front/js/app.js file, not gulpfile.js

**Comment by devinfd** [comment]
Ok now I believe you because now I'm having a similar issue. I need to investigate it further before know what's going on and harassing Jeffrey.

**Comment by tonioriol** [comment]
i have exactly the same problem @afigienas
