### ISSUE TITLE
Is it necessary that buildDir should be build named directory?

### ISSUE THREAD

**Issue by harshjv** [laravel/elixir#105]
See [version.js:78](https://github.com/laravel/elixir/blob/master/ingredients/version.js#L78)

`getBuildDir()` is adding suffix `build` to user given `buildDir`. This gives less options to set a custom build directory.

**Comment by patrickbrouwers** [comment]
I think this is because the `elixir()` helper in Laravel expects a /build directory.

**Comment by JeffreyWay** [comment]
Yep. Also, it's a safety thing, since we clear out everything in that directory.
