### ISSUE TITLE
Can it be used outside Laravel?

### ISSUE THREAD

**Issue by sanketsahusoft** [laravel/elixir#109]
This is some great stuff and you must consider it promoting outside Laravel as well.

Do you think it will work without Laravel? Say, I want to use it for just any general webpage where I want to convert LESS to CSS?

**Comment by JeffreyWay** [comment]
Should work. You'll need to create a `elixir.json` file in your project root to override some default file paths. That's the main Laravel-specific thing.

**Comment by sanketsahusoft** [comment]
I didn't know that existed. Thanks!
