### ISSUE TITLE
elixir() producing relative url, different to Laravels asset() function

### ISSUE THREAD

**Issue by TommyC81** [laravel/elixir#113]
Not sure if it is by design. I have my Laravel installation in a subdirectory on the server. When versioning assets and using elixir() to insert it, elixir() produces a relative url rather than a full url.

This works differently compared to Laravels built-in asset() function.

Example:

Application url: http://localhost/applicationX/
elixir output: /build/css/app-d148e6a5.css (which then incorrectly points to http://localhost/build...)
asset output: http://localhost/applicationX/css/stylesheet.css

This can obviously be worked around by adding {{ url() }} in the blade template prior to the elixir() output. But is this intentional?

**Comment by golevel** [comment]
I just ran into this as well. It's only a problem for me on localhost where my install is on a subdirectory, but it does seem odd even for production where it would work to all of a sudden switch to relative urls instead of absolute everywhere else.

**Comment by JeffreyWay** [comment]
The elixir() function is part of the Laravel framework repo, so this issue should be submitted there.
