### ISSUE TITLE
Build directory outside working directory error

### ISSUE THREAD

**Issue by Wiejeben** [laravel/elixir#119]
Hi,

Because of how my server is setup I have to move the public folder outside Laravel, this should work fine however whenever I let gulp run version() it gives me:

Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.

Can force be added to ingredients/version.js, row 64 to the del() function?

**Comment by JeffreyWay** [comment]
That scares me.

What does your Gulpfile look like?

**Comment by JeffreyWay** [comment]
Merged.
