### ISSUE TITLE
Gulp watch not watching

### ISSUE THREAD

**Issue by jerairrest** [laravel/elixir#124]
Hello!

I'm having an issue getting Gulp to watch my Laravel resource folder for a change. Using the default configuration it doesn't seem to work. I managed to find the following code snippet that seems to allow watching of a particular folder, but it doesn't seem to watch the sub folders of the path.

```
elixir.config.registerWatcher("watch", "resources/assets/scss/**", 'default');
```

Any thoughts or ideas what I maybe doing wrong?

Thank you muchly!

**Comment by JeffreyWay** [comment]
By default, it'll watch `resources/assets/sass/`. Are you saying that you want to have it watch a different directory instead?

**Comment by seta0909** [comment]
i got same issue when i use gulp watch, console seems work but my css file will be empty.

**Comment by jerairrest** [comment]
Ideally it would be nice if there were an initial config file or the path could be sent up in the grunt file to specify which folders should be watched. Currently I would like multiple folders to be watched so when I change a component for my front end Gulp just does its magic.

**Comment by JeffreyWay** [comment]
Elixir is convention-based, so if you need a lot of configurability, it might be best to fall back to standard Gulp tasks. Or, you can override the ones that Laravel provides, and then hook into them with Elixir.
