### ISSUE TITLE
Proposal: Solution for relative path resource issue when using .version()

### ISSUE THREAD

**Issue by htcang** [laravel/elixir#125]
Refer to #66 and #70 , how about we add a param to `version` to  allow input an array of folders in /public ( for example `mix.version('all.css', ['img', 'resources', 'fonts'])`) and then just create symlink for those folders in our `build` folder. 

So our new `build` directory structure will look like this:
```
public
├── build
|   ├── css
|   |   └── all-906ce017.css
|   |
|   ├── js
|   |   └── all-906ce017.js
|   |
|   ├── img (symlink -> public/img) 
|   |
|   ├── resources(symlink -> public/resources) 
|   |
|   └── fonts(symlink -> public/fonts) 
|
└── rev-manifest.json
``` 
if the second param has something like `['resources/font', 'resources/image', 'resources\icon']`, we just simple create a `resources` symlink.

I think this is the safe way to deal with the relative path issue in css/js as when we delete the `build` dir, only symlinks got deleted.

@JeffreyWay Do you think this is viable solution?

**Comment by JeffreyWay** [comment]
Hmm - not sure. I'm thinking there's a cleaner way to handle this.

**Comment by tholu** [comment]
So you want to solve this with #70?
