### ISSUE TITLE
When using multiple depending mix.scripts last file is not found even if it exists on disk

### ISSUE THREAD

**Issue by mabasic** [laravel/elixir#127]
If I try to do this:

```
elixir(function(mix) {
    mix.scripts(['jquery.js', 'something.js'], 'public/js/main.js')
       .scripts(['threads.js', 'main.js'], 'public/js/forum.js');
});
```

Last file in scripts `main.js` is not found even if it exists on disk.

Is there a way to resolve this? Maybe Elixir is locking the file and the second scripts task cannot see it?

**Comment by mabasic** [comment]
I have resolved my issue by moving the files from first `scripts` task to the seconds `scripts task. See [here](https://laracasts.com/discuss/channels/general-discussion/combining-multiple-js-files-in-assets-into-one-in-public), but this is still an issue if you are creating two separate files.

**Comment by JeffreyWay** [comment]
Are you using the latest version of Elixir? Pretty sure this was resolved.

Either way, closing, since you figured this out.

**Comment by mabasic** [comment]
I am using the latest version. If I run into the issue again I'll let you know.
