### ISSUE TITLE
Real World example

### ISSUE THREAD

**Issue by stephanedemotte** [laravel/elixir#131]
Hi,

Elixir look pretty good, but when we try to run more than a simple command, we meet a lot of problem.
And the documentation are really poor.

Can you make a Laracast video, or add a gulpfile.js, with a real world example.
We never use only mix.browserify() or mix.less()....

With Laravel we can make really really more complicated than a simple website.
It could be cool to have a example with :
Sass, concat css vendor, concat with the Sass, make Revision, Concat JS vendor, concat JS app, and re-concat together, make a revision of all of that, copy some fonts, copy and compress some images, make some sprites..... And the same thing for the Frontend and the Backend.... so we need that in 2 separate folder.

We hit a big wall, between your example and the real life...

If we use Gulp, it's because we have more than a simple less file to compile.
It could be really help-full to get a great "kickstart" with all of that.

Anyway, thank you really really much for your great work. :)

**Comment by JeffreyWay** [comment]
If you have an incredibly complex app, then just use Gulp.

Otherwise, I'm not exactly sure what your question is. You may concat any of the methods outline in the documentation.

```
mix.sass('app.scss')
     .scripts(['file.js', 'another.js'])
     .copy('...', '...');
     .
```
