### ISSUE TITLE
Error installing on windows

### ISSUE THREAD

**Issue by grupohermes** [laravel/elixir#133]
Hi @JeffreyWay, im installing laravel-elixir in a windows web server, im getting this errors while running npm install.

npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp Cloning into 'C:\cygwin64\tmp\npm-6396-3b1906fa\git-cache-b1fb09b2ce2e\f13599f5198b853948429062c2b334010a337342'...
npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp fatal: '/cygdrive/c/Users/UBueno/AppData/Roaming/npm-cache/_git-remotes/https-github-com-am11-pangyp-8a40b7fa/C:\Users\UBueno\AppData\Roaming\npm-cache\_git-remotes\https-github-com-am11-pangyp-8a40b7fa' does not appear to be a git repository
npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp fatal: Could not read from remote repository.
npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp
npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp Please make sure you have the correct access rights
npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp and the repository exists.
npm ERR! Failed to clone git+https://github.com/am11/pangyp#f13599f5198b853948429062c2b334010a337342 from https://github.com/am11/pangyp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "laravel-elixir"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code 128

I don't know what is happening, do you have any clues?

In my Mac it justs install good.

**Comment by JeffreyWay** [comment]
No idea. Could be any number of things, honestly. Doesn't look like an Elixir issue, though.

**Comment by matthewjewell** [comment]
@grupohermes - Downgrading node to `0.10.33` may resolve this, it did for me.
