### ISSUE TITLE
Optional Autoprefixer 

### ISSUE THREAD

**Issue by deframe** [laravel/elixir#135]
Hi,

I noticed in "**ingredients/commands/CompileCSS.js**" that the autoprefixer is a mandatory part of compilation. This adds over a second to the compilation process on my system but it's not a requirement for my project(s).

Perhaps this should be a configuration option?

`.pipe(plugins.if(config.autoprefixer, plugins.autoprefixer()))`

If I find time this evening then I'll submit a pull request!

**Comment by tymondesigns** [comment]
Linked to #100
