### ISSUE TITLE
Simple mix.scripts() not working

### ISSUE THREAD

**Issue by Shonetow** [laravel/elixir#139]
This is almost the same thing as in documentation

```
elixir(function(mix) {
	mix.scripts(['main.js', 'contact.js'], 'public/js/main.js');
});
```
I have all folders:
![image](https://cloud.githubusercontent.com/assets/4283547/7645690/046c51b2-fab9-11e4-9eae-16ee054886d5.png)

![image](https://cloud.githubusercontent.com/assets/4283547/7645705/5e60a416-fab9-11e4-9e71-79c03f212a46.png)

And nothing. Not even watching for changes, No errors.

**Comment by JeffreyWay** [comment]
Just tried that exact code out with a fresh install of Laravel, and all worked correctly.

If you have specifics on your Laravel setup or Elixir version, let me know. Otherwise, I can confirm it all works.

**Comment by Shonetow** [comment]
Yeah... solved with `npm update`
Tnx Jeff!
