### ISSUE TITLE
Sourcemap

### ISSUE THREAD

**Issue by LeusMaximus** [laravel/elixir#142]
During development I nee source map. On production I need disable sourcemap and delete map files. Can we do it with elixir?

**Comment by JeffreyWay** [comment]
Sourcemaps will be based upon the value set in your configuration file.

https://github.com/laravel/elixir/blob/master/Config.js#L13

**Comment by LeusMaximus** [comment]
I need two different task. In the first must be created sourcemap. In the second sourcemap files must be deleted.
