### ISSUE TITLE
Use multiple custom paths with mix.scripts

### ISSUE THREAD

**Issue by eablokker** [laravel/elixir#143]
I'd really like to include scripts from my bower_components folder in addition to the resources/assets/js folder. The following doesn't work, it ends up messing up the path, like `File not found: /bower_componentsbootstrap/dist/js/bootstrap.js` where it somehow removes the / between /bower_components and /bootstrap.

```
mix.scripts([
			'resources/assets/js/libs/**/*.js',
			'bower_components/bootstrap/dist/js/bootstrap.js',
			'bower_components/lodash/lodash.js',
			'bower_components/angular-google-maps/dist/angular-google-maps.js',
			'resources/assets/js/app.js',
			'resources/assets/js/appRoutes.js',
			'resources/assets/js/controllers/**/*.js',
			'resources/assets/js/services/**/*.js',
			'resources/assets/js/directives/**/*.js'
		], 'public/build/js/all.js', '/')
```

What is the preferred way of including scripts from multiple folders? Also I don't want to include all scripts from bower_components because there are a lot in there that I don't want to include.

**Comment by eablokker** [comment]
I think I figured it out. I had to use `./` as my path instead of `/`. That seems to work.

**Comment by JeffreyWay** [comment]
Yep.
