### ISSUE TITLE
mix.rubySass does not generate correct "sources" key into sourcemap

### ISSUE THREAD

**Issue by rafaelbeckel** [laravel/elixir#144]
When I use mix.rubySass('style.scss'); the sourcemap it generates does not contain all the source files I refer with @include in my scss. 

The "sources" key is generated like that:
 ... "sources":["style.css"] ... (and there's no "file" key)
causing Developer Tools point to the generated 4000+ lines style.css file. Probably its trying to embed reference files, but without success.

When I run it directly via sass command, everything works fine. The generated sourcemap contains the "file" key with value "style.css" and the "sources" key contains a big array with all my original .scss files. Dev Tools recognizes it and everything works fine.

As a workaround, i'm using gulp-shell package to call sass directly with only one line of code:
gulp.task('sass', shell.task([ 'sass resources/assets/sass/style.scss public/css/style.css' ]));

Then I started to wonder... what the advantages of using gulp-ruby-sass and all its dependencies to do exactly the same thing? Could be rubySass command wrapped around gulp-shell instead?

Cheers,

**Comment by JeffreyWay** [comment]
If you can give me an example that I can try out on my end, I'll take a look. Tough to say otherwise. Sounds like it might be an issue with, not Elixir, but the Gulp Ruby Sass extension that Elixir uses.

**Comment by rafaelbeckel** [comment]
Yes, the issue was with gulp-ruby-sass extension. And that's exactly the point.

Wouldn't it be simpler to wrap mix.rubySass() command to use gulp-shell instead?

Sass has native sourcemap support, but gulp-ruby-sass tries to reproduce it using Javascript. I just didn't get the point of using it, as the intent of using mix.rubySass() command is to just use native sass.
