### ISSUE TITLE
not installable via npm

### ISSUE THREAD

**Issue by simonfunk** [laravel/elixir#152]
hi jeffrey

at the moment, it's not possible to install laravel-elixir via npm.
i checked the error log and figured out that there is a spelling error in the request link: http://regitry.npmjs.org/laravel-elixir

there is a s missing the word regi(s)try.

by the way, thanks a lot for your exellent work and video tutorials. its always a pleasure be teached from you ;)

**Comment by JeffreyWay** [comment]
Hey, Simon - 

Where did you find that typo? People are installing Elixir every day.

**Comment by simonfunk** [comment]
Hi jeffrey

it's when i type "npm install". After that, i got the npm ERR! in console, so i checked the npm-debug.log file and there i found the link with that typo.

**Comment by simonfunk** [comment]
hi jeffrey
i found now they causing, somehow the npm config was setted false. i've no idea how that happened,
anyway, sorry for disturbing you and thanks for try to help!
