### ISSUE TITLE
Injecting 'use static';

### ISSUE THREAD

**Issue by Skizu** [laravel/elixir#154]
The latest versions of elixir seem to be injecting 'use static'; into all javascript files; this breaks the javascript for me.

Using 1.0.2 seems to be fine.

**Comment by tymondesigns** [comment]
Don't you mean `'use strict'` ?

**Comment by Skizu** [comment]
Yeah; it's been a long day.

**Comment by mikeerickson** [comment]
What happens when injecting this code? Do you have a sample JS file that is "broken"?

**Comment by iWader** [comment]
Having big issues with this today.

@mikeerickson libs that use "this" to access the global break, which surprising a huge amount of libs do that.

**Comment by mikeerickson** [comment]
Ah, so you are saying the `addition` of "use strict" is breaking your app.

yah, that is something of an old issue.  may js devs have been 'lazy' over the years to say the least.

**Comment by Skizu** [comment]
Indeed, and sadly 3rd party code so not much I can do.

**Comment by tymondesigns** [comment]
As hacky as it is, maybe you could add this - https://www.npmjs.com/package/gulp-remove-use-strict

**Comment by iWader** [comment]
@tymondesigns the issue with that is by introducing strict mode certain runtime behaviours change, thus you have the same issue upon removing it.

This behaviour would be "okay" if it was just applying it to my own code, but its not, its applying it to the entire concatenated js file.

I say "okay" because its not really okay to be adding/removing something that alters the runtime environment of the code. If I was to write my code specifically in strict mode I would use a safe method such as the follow so that strict mode is only applied to my code, and not the entire concatenated file.

```javascript
(function() { 'use strict';
});
```

**Comment by tymondesigns** [comment]
@iWader yea you have a point there.. I guess the fact that many js libs haven't encapsulated their code properly makes this difficult.

Not sure if the babel transpiler has an option to disable adding 'use strict'. 

It was discussed here - https://github.com/babel/babel/issues/114

**Comment by iWader** [comment]
I assumed it was from babel but not at work to play around with different elixir versions to tell if that was the case.

@JeffreyWay can we remove babel seeing as most people arn't going to be using v7 features anyway. For those that want it can add the tasks themselves or perhaps setup a different `scripts()` task in elixir for this so its available out of the box?

**Comment by JeffreyWay** [comment]
Hey, all - 

We have two options:

1. You may disable Babel support, if you don't desire it. `elixir.config.babel.enabled = false`.
2. We can blacklist "useStrict", so that it doesn't get included. Not sure we should do this, but it's an option.

Any preference?

**Comment by iWader** [comment]
Could we go for the option of having it disabled by default but can be enabled using the config?

Realistically most people are not going to be using v7 features and out of the box this breaks even simple concatenation of 3rd party libraries.

**Comment by komarnicki** [comment]
I totally agree with @iWader.

**Comment by hackel** [comment]
Ideally, there would be a way to specify which files to pipe through Babel on a per-call basis.  I don't want to pass any of my dependencies through it (at least so far), but need to translate my own code.  Perhaps add an additional options parameter to the scripts* ingredients?

**Comment by gbrock** [comment]
Please keep babel disabled by default.  It broke Modernizr.js for me, turning the last line of the file into:

```js
})(undefined, undefined.document);
```

...and made my common `scripts` task take a **lot** more time and resources.
