### ISSUE TITLE
Babel enabled by default in all environments

### ISSUE THREAD

**Issue by chriseverson** [laravel/elixir#158]
Babel was enabled by default in cd78083980fc202772df2ebe9a72d8fe27e8d03e yet I think this should be something that should check the environment and be disabled by default unless in production, like the other obfuscation / compiling actions.

This is day one with Elixir for me, so I'll let someone else chime in and tell me if I'm right/wrong before sending a pull request.

**Comment by JeffreyWay** [comment]
You'd need Babel to run in dev mode too.

Folks can disable it with `elixir.config.babel.enabled = false`.
