### ISSUE TITLE
Laravel elixir auto concatenating coffee files

### ISSUE THREAD

**Issue by lynkyle** [laravel/elixir#160]
I have just installed again laravel 5 via composer. Then proceeded to follow instructions on installation and setup of laravel elixir.

The thing is, elixir is auto concatenating my coffee files.  Here is the contents of my gulpfile.js

    var elixir = require('laravel-elixir');
        
    elixir(function(mix) {
        mix.coffee().less('app.less');
    });

I have the following sample files in these locations:

    resources/assets/coffee/sample/myApp.coffee
    resources/assets/coffee/sample/controllers/sampleController.coffee
    resources/assets/coffee/sample/directives/sampleDirective.coffee

After running gulp, the output is in:

    public/js/app.js

The 3 coffee files are concatenated within the output file.

If I try this on a older install of laravel 5, about a month old, it works as expected. The files are not concatenated and the directory structure is intact.

I have taken a peek at the:
    node_modules/laravel-elixir/package.json

On the new installation, elixir version is 2.1.1 while on the old one is 1.0.3.

Anyone can shed a light on this?

I have posted this earlier at stackoverflow also. http://stackoverflow.com/questions/30547405/laravel-elixir-auto-concatenating-coffee-files

**Comment by JeffreyWay** [comment]
For Laravel 5.1 (or anyone who upgrades their installation of Elixir), the `mix.coffee()` method will auto-concatenate your files. This is a feature, not a bug. :)

**Comment by fidgetwidget** [comment]
Without a way to have the same functionality we had before - while it isn't a bug, it's a cut of a feature, and an issue for some users.
Please provide a way to set the concatenating to false with an option. 
I'd be happy to provide a pull request for this if it is something you'd be willing to add.

**Comment by AppSynergy** [comment]
@fidgetwidget  I'd be happy to see / assist your PR!

Given it's a feature - why so?   The `scripts` ingredient provides concatenation if it's desired.

N.B: I suspect I'm not the only one using ~1.x to get around this (but probably missing out on other features / bugfixes as a result :s)
