### ISSUE TITLE
Support for modular assets structure

### ISSUE THREAD

**Issue by rafis** [laravel/elixir#161]
Current structure is:

    resources/assets/css/*.css
    resources/assets/js/*.js

But I would like to use this structure:

    resources/assets/angular/js/angular-animate.js
    resources/assets/angular/js/angular-cookies.js
    resources/assets/angular/js/angular-route.js
    resources/assets/angular/js/angular-sanitize.js
    resources/assets/angular/js/angular.js
    resources/assets/angular-toaster/css/toaster.css
    resources/assets/angular-toaster/js/toaster.js
    resources/assets/app/css/styles.css
    resources/assets/app/js/config.js
    resources/assets/app/js/diretives.js
    resources/assets/app/js/Controllers/MainCtrl.js
    resources/assets/bootstrap/css/bootstrap.css
    resources/assets/bootstrap/fonts/fontawesome-webfont.eot
    resources/assets/bootstrap/fonts/fontawesome-webfont.svg
    resources/assets/bootstrap/fonts/fontawesome-webfont.ttf
    resources/assets/bootstrap/fonts/fontawesome-webfont.woff
    resources/assets/bootstrap/fonts/fontawesome-webfont.woff2
    resources/assets/bootstrap/fonts/FontAwesome.otf
    resources/assets/bootstrap/fonts/glyphicons-halflings-regular.eot
    resources/assets/bootstrap/fonts/glyphicons-halflings-regular.svg
    resources/assets/bootstrap/fonts/glyphicons-halflings-regular.ttf
    resources/assets/bootstrap/fonts/glyphicons-halflings-regular.woff
    resources/assets/bootstrap/js/bootstrap.js
    resources/assets/jquery/js/jquery.js
    resources/assets/toggle-switch/css/toggle-switch.css

I have tried playing with multiple mix.scripts/mix.styles and baseDir, but it combines only first script/style file.

    elixir(function(mix) {

    var outCss = 'public/assets/css/styles.css';
    mix.styles(['bootstrap.css', 'bootstrap-theme.css', 'font-awesome.css'], outCss, 'resources/assets/bootstrap/css');
    mix.copy('resources/assets/bootstrap/fonts', 'public/assets/fonts');
    mix.styles(['toaster.css'], outCss, 'resources/assets/angular-toaster/css');
    mix.styles(['toggle-switch.css'], outCss, 'resources/assets/toggle-switch/css');
    mix.styles(['styles.css'], outCss, 'resources/assets/app/css');

    var outJs = 'public/assets/js/scripts.js';
    mix.scripts(['jquery.js'], outJs, 'resources/assets/jquery/js');
    mix.scripts(['bootstrap.js'], outJs, 'resources/assets/bootstrap/js');
    mix.scripts(['angular.js'], outJs, 'resources/assets/angular/js');
    mix.scripts(['angular-route.js'], outJs, 'resources/assets/angular/js');
    mix.scripts(['angular-cookies.js'], outJs, 'resources/assets/angular/js');
    mix.scripts(['angular-sanitize.js'], outJs, 'resources/assets/angular/js');
    mix.scripts(['angular-animate.js'], outJs, 'resources/assets/angular/js');
    mix.scripts(['toaster.js'], outJs, 'resources/assets/angular-toaster/js');
    mix.scripts(['config.js'], outJs, 'resources/assets/app/js');
    mix.scripts(['directives.js'], outJs, 'resources/assets/app/js');
    mix.scripts(['MainCtrl.js'], outJs, 'resources/assets/app/js/Controllers');

    mix.version([
        'public/assets/css/all.css',
        'public/assets/js/all.js'
    ]);

    });

**Comment by JeffreyWay** [comment]
Why don't you set a base directory of `resources/assets`, and then just use a single `mix.scripts()` call, and specify the relative path from that point.
