### ISSUE TITLE
Reconsider the name of the project

### ISSUE THREAD

**Issue by rhalukongor** [laravel/elixir#163]
I happen to be twice an elixir developer in the same project: We're using Laravel/Elixir and Elixir (the language) in the same project and googling for anything is definitely problematic. Yes I can always search "Laravel Elixir" or "Elixir-lang" but googling is something you do without second thoughts, may be with muscle memory.
Some may ask how can google searches for a language and a build tool may clash? Well, just try "elixir copy file". Also the super generic name of Elixir's Mix build tool make things really worse. You seem to have chosen the same name twice!
This is probably too much to ask but I'd appreciate if my point is at least considered.

**Comment by JeffreyWay** [comment]
Not ideal for sure. I'll talk with Taylor, but we might be out of luck.
