### ISSUE TITLE
Gulp taking ages to merge scripts

### ISSUE THREAD

**Issue by kebian** [laravel/elixir#166]
Gulp will take up to 7 minutes to merge these scripts when using elixir 2.x, but can do the same task in a few seconds using elixir 1.0.0.  Under version 2.x, the resulting file will cause javascript errors.  I've tried all sorts and the only difference is the elixir version. 

package.json
```javascript
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "*"
  }
}
```

bower.json
```javascript
{
  "name": "testsite",
  "version": "0.0.1",
  "authors": [
    "Rob Stiles <robs@codexsoftware.co.uk>"
  ],
  "license": "MIT",
  "dependencies": {
    "bootstrap": "~3.3.4",
    "eonasdan-bootstrap-datetimepicker": "~4.7.14"
  }
}
```

gulpfile.js
```javascript
var elixir = require('laravel-elixir');

elixir(function (mix) {
    mix
        .less('app.less')
        .scripts([
            'jquery/dist/jquery.js',
            'bootstrap/dist/js/bootstrap.js',
            'moment/min/moment-with-locales.js',
            'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js'
        ], 'public/combined.js', 'bower_components')
});
```

**Comment by kilburn** [comment]
I've got the same issue, and the offender is clearly the `babel` javascript compiler. If you don't know what it is or don't need it, you can easy disable it by adding:
```
var elixir = require('laravel-elixir');
[...]
elixir.config.babel.enabled = false;
```
This lowered my script concatenation times by orders of magnitude...

**Comment by JeffreyWay** [comment]
Yeah - it looks like Babel really doesn't do well with libraries and such. And it shouldn't need to bother with them.

So we're pulling Babel compilation out into its own task, like CoffeeScript.

```
mix.scripts(['jquery.js', 'underscore.js']); // normal and fast

mix.babel(['one.js', 'two.js']); // just like .scripts(), but runs through Babel compiler.
```

Update to Elixir 2.3.0.

**Comment by kebian** [comment]
Thanks guys!
