### ISSUE TITLE
Sass compiler puts everything into app.css after the last update, does not keep the folders structure

### ISSUE THREAD

**Issue by JaffParker** [laravel/elixir#168]
We used to have one single string for sass compiler that would go through all the folders and compile files in them. At the same time it kept the folders structure of that original folder. Here's the line:

    mix.sass('sass/toCompile/**', 'public/css');

So, if there was a file **toCompile/common/common.scss** it would be compiled into **public/css/common/common.scss.**

However, after the last update, all the files from toCompile folder are compiled and concatenated into one app.css, whatever the original structure was.

**Comment by JeffreyWay** [comment]
Yeah - this was done on purpose. For Laravel 5.1, any files that you pass to `mix.sass()` will be compiled and concatenated into a single file.

If you don't want that, you can make multiple calls to `mix.sass()`.

**Comment by JaffParker** [comment]
This is a proposal then: make sass compiler more flexible and automatic, because sometimes the amount of calls can grow very high.
