### ISSUE TITLE
Problem with running in sequence - Running copy() after less()

### ISSUE THREAD

**Issue by Fabyo** [laravel/elixir#170]
Already tried everything and nothing has worked

```javascript
var elixir    = require('laravel-elixir'),
	gulp      = require('gulp');

var bowerDir  = elixir.config.bowerDir + '/';
var assetsDir = elixir.config.assetsDir;

gulp.task('default', ['second'], function() {});

gulp.task('first', function() {
	return elixir(function(mix) {
		return mix.copy(bowerDir + 'bootstrap/fonts', 'public/fonts')
			.copy(bowerDir + 'font-awesome/fonts', 'public/fonts')
		
			.copy(bowerDir + 'bootstrap/less', assetsDir + 'less/bootstrap')
			.copy(bowerDir + 'bootstrap-select/less', assetsDir + 'less/bootstrap-select')
			.copy(bowerDir + 'font-awesome/less', assetsDir + 'less/font-awesome')
		
			.copy(bowerDir + 'bootswatch/paper/variables.less', assetsDir + 'less/bootswatch')
			.copy(bowerDir + 'bootswatch/paper/bootswatch.less', assetsDir + 'less/bootswatch');
	});	
});

gulp.task('second', ['first'], function() {
	elixir(function(mix) {	
		mix.less('app.less');
	});	
});
```

>C:\root\laravel-crud>gulp
>[11:26:53] Using gulpfile C:\root\laravel-crud\gulpfile.js
>[11:26:53] Starting 'first'...
>[11:26:55] Finished 'first' after 2.28 s
>[11:26:55] Starting 'second'...
>[11:26:55] Finished 'second' after 2.8 ms
>[11:26:55] Starting 'default'...
>[11:26:55] Starting 'copy'...
>[11:26:55] Finished 'default' after 29 ms
>[11:26:55] Finished 'copy' after 85 ms
>[11:26:55] Starting 'less'...
>[11:26:55] Running Less: resources/assets/less/app.less
>[11:26:56] gulp-notify: [Laravel Elixir] Less Compilation Failed!: 'bootstrap/bo
>otstrap.less' wasn't found. Tried - C:\root\laravel-crud\resources\assets\less\b
>ootstrap\bootstrap.less,bootstrap\bootstrap.less in file C:\root\laravel-crud\re
>sources\assets\less\app.less line no. 1
>{ [Error: 'bootstrap/bootstrap.less' wasn't found. Tried - C:\root\laravel-crud\
>resources\assets\less\bootstrap\bootstrap.less,bootstrap\bootstrap.less in file
>C:\root\laravel-crud\resources\assets\less\app.less line no. 1]
>  type: 'File',
>  filename: 'C:\\root\\laravel-crud\\resources\\assets\\less\\app.less',
>  index: 0,
>  line: 1,
>  callLine: NaN,

**Comment by JeffreyWay** [comment]
Why do you need multiple elixir() calls. Can't `mix.less()` come right before your copy tasks?

**Comment by Fabyo** [comment]
It is that the mix.less does not allow access the path to the bower = `vendor/bower_components`


mix.less(['./vendor/bower_components/bootswatch/paper/bootswatch.less']);

```
[23:36:22] Starting 'less'...
[23:36:22] Running Less: resources/assets/less/./vendor/bower_components/bootswa
tch/paper/bootswatch.less
[23:36:23] File not found: resources/assets/less/./vendor/bower_components/boots
watch/paper/bootswatch.less
```
why I copy the files to less to resources/assets/less and then use the mix.less()

there is another way for me to generate less files that are in bower folder?

thanks

**Comment by JeffreyWay** [comment]
Then can you keep it all in one elixir() set, but copy everything over first? I tried this, and it worked just fine.

```
elixir(function(mix) {
    mix.copy(
        'bower_components/bootstrap/less',
        'resources/assets/less/vendor'
    );

    mix.less('app.less');
});
```

**Comment by Fabyo** [comment]
```javascript
var elixir = require('laravel-elixir');

var bowerDir  = elixir.config.bowerDir + '/';
var assetsDir  = elixir.config.assetsDir;

elixir(function(mix) {
    mix.copy(
        bowerDir  + 'bootstrap/less',
        assetsDir + 'less/bootstrap'
    )
    .copy(
        bowerDir  + 'bootstrap-select/less',
        assetsDir + 'less/bootstrap-select'
    )
    .copy(
        bowerDir  + 'font-awesome/less',
        assetsDir + 'less/font-awesome'
    )

    mix.less('app.less');
});
```
app.less:

```
@import "bootstrap/bootstrap.less";
@import "bootstrap-select/bootstrap-select.less";
@import "font-awesome/font-awesome.less";
```

```
[09:27:33] Using gulpfile C:\root\laravel-crud\gulpfile.js
[09:27:33] Starting 'default'...
[09:27:33] Starting 'copy'...
[09:27:33] Finished 'default' after 14 ms
[09:27:33] Finished 'copy' after 69 ms
[09:27:33] Starting 'less'...
[09:27:33] Running Less: resources/assets/less/app.less
[09:27:34] gulp-notify: [Laravel Elixir] Less Compilation Failed!: 'variables.le
ss' wasn't found. Tried - C:\root\laravel-crud\resources\assets\less\bootstrap\v
ariables.less,variables.less in file C:\root\laravel-crud\resources\assets\less\
bootstrap\bootstrap.less line no. 2
{ [Error: 'variables.less' wasn't found. Tried - C:\root\laravel-crud\resources\
assets\less\bootstrap\variables.less,variables.less in file C:\root\laravel-crud
\resources\assets\less\bootstrap\bootstrap.less line no. 2]
  type: 'File',
  filename: 'C:\\root\\laravel-crud\\resources\\assets\\less\\bootstrap\\bootstr
ap.less',
```

He does not wait finish copying so do not think the file
