### ISSUE TITLE
Allow multiple calls to .coffee()

### ISSUE THREAD

**Issue by h-collector** [laravel/elixir#171]
In regard to recent changes in v2 and issue #160.
It would be almost fine if we had alternative to call .coffee() multiple times with different destinations like with sass/less ( #168, #164 <- we can call `.less(less1, dest1).less(less2, dest2 ) `.
As of now, even if called like so:
```
.coffee('coffee-subdir1/**/*.coffee', public/js/destination1.js) 
.coffee('coffee-subdir2/**/*.coffee', public/js/destination2.js) 
```
only last one 
```
Starting 'coffee'...
Running CoffeeScript: 'coffee-subdir2/**/*.coffee'
Finished 'coffee'
```
Would be executed.

PS. Search part could be dropped if `src` was checked for it's file type (in commands/Utilities.js: buildGulpSrc function )

**Comment by JeffreyWay** [comment]
Will fixed soon, if that's the case.
