### ISSUE TITLE
latest version breaks coffee compilation (and maybe other things too?)

### ISSUE THREAD

**Issue by fidgetwidget** [laravel/elixir#172]
Not sure if there is a dependency missing, or something changed that isn't documented, but when I did an npm update recently, my coffee files were no longer being output. I changed my coffee mix call to blank so it would do the default behaviour, and still nothing.
I changed my package.json from 
laravel-elixir: *
laravel-elixir: 1.*
and it started working again.
is there something that changed that I should know about?

**Comment by GrahamCampbell** [comment]
Yeh, this is the expected behaviour. There are many duplicate issues you can take a look at. :)

**Comment by fidgetwidget** [comment]
But all of the issues are closed... can you link me to one?

**Comment by GrahamCampbell** [comment]
Yes, they're closed, because it's not a bug.

**Comment by fidgetwidget** [comment]
the fact that 
.coffee()
doesn't work anymore isn't a bug?

**Comment by GrahamCampbell** [comment]
Please just read the other closed issues. It DOES still work, but it does NOT output individual files from 2.x.

**Comment by fidgetwidget** [comment]
I read through all the closed issues that had the word "coffee" in them... and didn't see anything about it.
Is there a new task then that does what I am looking for?

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/elixir/issues/168

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/elixir/issues/160

**Comment by fidgetwidget** [comment]
Ok thank you. I did see #160, but I guess I just didn't make sense of it.
I'll close this and open a different one ;)

**Comment by GrahamCampbell** [comment]
Also, that cat in your avatar is very cute. :)
