### ISSUE TITLE
No way to prevent concatenating of assets (the old behaviour)

### ISSUE THREAD

**Issue by fidgetwidget** [laravel/elixir#174]
It would be nice to have a way to get the pre 2.0 behaviour for those of us that were using it for a variety of reasons.
Also, the fact that this change from 1 to 2 wasn't documented is frustrating. Dropping functionality in favour of new functionality should be documented... shouldn't it?

**Comment by fidgetwidget** [comment]
One other thing about this - we already had a way to merge multiple files with the scripts and styles commands, so I am at a loss as to why you made this change to begin with.
It didn't ADD anything.

**Comment by astroanu** [comment]
Dropping functionality in favour of new functionality should be documented... shouldn't it? 

+1

**Comment by JeffreyWay** [comment]
I'm sorry it wasn't noted in the 5.1 upgrade guide.

You can make multiple calls to `mix.sass()` or `mix.less()`. 

```
elixir(function(mix) {
    mix.less(["app.less", "app2.less"], 'public/css/app.css')
       .less('other.less', 'public/css/other.css');
});
```
