### ISSUE TITLE
throws Error: EEXIST on less 

### ISSUE THREAD

**Issue by astroanu** [laravel/elixir#175]
when doing this

    elixir(function(mix) {
        mix.less("app.less", "public/css/home.css");
    });

throws Error: EEXIST, mkdir '/home/www/public/css/home.css'

works when the css directory is deleted. I think it's trying to create a directory before checking if it exists.

**Comment by JeffreyWay** [comment]
Hmm, I can't reproduce this. Works fine on my end (and haven't received any similar reports).

What version of Elixir and Gulp are you using? And what OS?

**Comment by astroanu** [comment]
sorry.. i'm on centOS7.
updated both global and local gulp, elixir before running the default task.

**Comment by JeffreyWay** [comment]
Either way, this wouldn't be an Elixir-specific issue. Elixir defers to Gulp for that sort of stuff.
