### ISSUE TITLE
Make watchify optional

### ISSUE THREAD

**Issue by waldemarfm** [laravel/elixir#179]
Is there a way to bypass use of watchify? We develop our apps in a Homestead VM mounted through NFS to increase performance, and since the latest update that included watchify the browserify watcher is not triggering anymore. It's an NFS related issue since it works fine when turned off.

I've done some research and it's an issue with `chokidar` needing an explicit option `usePolling` to be set as true. Since there's no way to pass options to watchify directly from the elixir mix call, then setting a flag to bypass watchify would be great.

I tried setting `elixir.config.watchify = false` manually in the gulpfile similar to the sourcemaps flag, but it made no difference.

**Comment by JeffreyWay** [comment]
You can't override watchify at the moment, but a PR to make the options configurable is welcomed.
