### ISSUE TITLE
CoffeeScript with Browserify

### ISSUE THREAD

**Issue by kalaomer** [laravel/elixir#183]
browserify can't use coffee files files itselfs. Is there any change for integartion with [coffeeify](https://github.com/jnordberg/coffeeify)?

**Comment by JeffreyWay** [comment]
Not at the moment. You'd need to make your own task for the time being.

**Comment by vinnizworld** [comment]
@kalaomer I have created one task for this. It's available on npm. https://www.npmjs.com/package/elixir-coffeeify
