### ISSUE TITLE
Allow wildcards for toplevel files

### ISSUE THREAD

**Issue by atrauzzi** [laravel/elixir#184]
When I'm building SASS, JavaScript or TypeScript, I usually like to rely on each tool's features for modularity.  What this means is that I usually end up with a handful of top-level entry point scripts and the combining happens preprocessor/transpiler-side not, via a concatenation done by Elixir.

It would be nice if I could tell Elixir to look at a specific directory and trigger the corresponding build once for each file in that directory and then automatically map each output to the destination directory.

The example usage would basically be globbing support:

```
mix.sass("page/*");
```

Imagining that the directory in my example had `full.scss` and `page.scss`, then the output directory would end up with `full.css` and `page.css` based on the output of running SASS once for each file caught in the glob.

Rationale: Right now it seems like I have to specify each top-level file individually, which for obvious reasons is more code than having a clean convention for built-entrypoints.  It also encourages people to modularize in the scope that the preprocessors/transpilers are aware of, rather than relying on outside concatenation.

**Comment by atrauzzi** [comment]
Note: It appears as though some form of globbing is supported, but output appears to combine it all into one file, rather than one for each top-level globbed?

**Comment by JeffreyWay** [comment]
Yeah - it got changed with the 2.0 release of Elixir. If you pass a glob (or an array of paths), they'll all be merged into one.

If you want multiple files, you would need to call `mix.sass()` multiple times.

**Comment by atrauzzi** [comment]
@JeffreyWay - This issue is a feature request for that functionality.  I don't want to have to call `mix.sass` multiple times.  Why not have it recognize a directory filled with top-level scripts?

**Comment by dn5** [comment]
Come on, this is set as closed yet there are number of packages that have over 100 subfolders with `package-*` notation. Is there a way to accomplish this?

**Comment by davejamesmiller** [comment]
For anyone else looking to do this, I found a workaround is to the the 'glob' module directly: http://stackoverflow.com/a/39673313/167815. Still, I've love if it was built into Elixir instead.
