### ISSUE TITLE
Add support for gulp-cached

### ISSUE THREAD

**Issue by sharedmit** [laravel/elixir#186]
Most of the time files like `bootstrap` don't change, recompiling them every time my app css changes takes a lot of time + resource, `gulp-cache` avoids this by passing only files that changed. Sure I can use different task for `bootstrap` and the like but it would be nice if this is available out of the box

**Comment by JeffreyWay** [comment]
Okay, I'll look into adding that. Otherwise, a PR is appreciated.

**Comment by huglester** [comment]
@JeffreyWay maybe watchify integration solved this?

**Comment by JeffreyWay** [comment]
It solved it for Browserify work, but I think that's it.

**Comment by sharedmit** [comment]
oh I didn't know this was solved?
