### ISSUE TITLE
Use `path-exists` instead of `fs.exists`

### ISSUE THREAD

**Issue by arthurvr** [laravel/elixir#190]
There are still some uses of `fs.exists` in the code. That methods is being deprecated: https://github.com/nodejs/io.js/issues/103. It's still in use in the following files:

* https://github.com/laravel/elixir/blob/9dd7da00ab988e116cd08fd9fea4b8e4ffd9fb19/Config.js#L68
* https://github.com/laravel/elixir/blob/e4de1fd996d33d0a043d00d5b0069278566d1354/ingredients/version.js#L111

Let's see if the uses of it are valid (it's deprecated for a reason), if so, the [`path-exists`](https://github.com/sindresorhus/path-exists) module is an option as replacement.

**Comment by JeffreyWay** [comment]
PR appreciated. :)
