### ISSUE TITLE
Less files do not compile when referencing 'paths'

### ISSUE THREAD

**Issue by kestrelhawk** [laravel/elixir#192]
I set up a `gulpfile.js` in the root folder of my Laravel project, as follows: 

    var elixir = require('laravel-elixir');

    var bowerDir = './vendor/bower_components/';

    var lessPaths = [
        bowerDir + 'bootstrap-material-design/less',
    ];

    elixir(function(mix) {
    mix
        .less("material.less", 'public/assets/css/', {paths: lessPaths});
    });

My `material.less` file contains the following: 

    @import "material";

I run the `gulp` command and receive no errors:

    [00:13:29] Using gulpfile ~/workspace/gulpfile.js
    [00:13:29] Starting 'default'...
    [00:13:29] Starting 'less'...
    [00:13:29] Running Less: resources/assets/less/material.less
    [00:13:30] Finished 'default' after 940 ms
    [00:13:30] gulp-notify: [Laravel Elixir] Less Compiled!
    [00:13:30] Finished 'less' after 1.13 s
    [00:13:30] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
    not found: notify-send

However, the resultant `material.css` file is blank, and contains only the following line: 

    /*# sourceMappingURL=material.css.map */

Interestingly enough, if I grab the contents of the `./vendor/bower_components/bootstrap-material-design/less/material.less` file and paste it into my `material.less` file (contained in `resources/assets/less` folder), the final `material.css` file is compiled successfully. 

Just for reference, I'm using the [bootstrap-material-design](https://github.com/FezVrasta/bootstrap-material-design/tree/master/less) add-in. I also attempted to compile the `./vendor/bower_components/bootstrap-material-design/less/material.less` using the `lessc` command which worked successfully. 

To temporarily resolve this issue, I've changed my `gulpfile.js` to the following: 

    ...
    .less("material.less", 'public/assets/css/');
    ...

I've also referred to the entire path of the bower component in my own `material.less` file, as follows: 

    @import "./vendor/bower_components/bootstrap-material-design/less/material.less";

I can confirm the above workaround creates the CSS file with all the relevant compiled CSS within. Are my steps above incorrect or is there a deeper issue regarding the less paths? 

Thanks

**~Kevin**

**Comment by eduardostuart** [comment]
Check #213
