### ISSUE TITLE
Glitches in notifications on Ubuntu

### ISSUE THREAD

**Issue by atrauzzi** [laravel/elixir#194]
![screenshot from 2015-07-01 19 00 15](https://cloud.githubusercontent.com/assets/115199/8467416/8d891180-2023-11e5-9413-a28f04173f3c.png)

I get multiple notifications when Elixir tasks are running.  Some will show a success message, other times it will show the above.  It should just be showing one at the end, not flashing several times with mixed messages.

**Comment by AppSynergy** [comment]
I've seen that quite a bit too. 

Example:

```bash
$ gulp | grep notify
[12:16:42] gulp-notify: [Laravel Elixir] CoffeeScript Compiled!
[12:16:43] gulp-notify: [Laravel Elixir] Sass Compiled!
[12:16:48] gulp-notify: [Laravel Elixir]  
[12:16:48] gulp-notify: [Laravel Elixir]  
[12:16:49] gulp-notify: [Red!] Your PHPUnit tests failed!
```

Of which, the first "blank" notification simply displays "Laravel Elixer", and the second one appears as described above.

Suspect at least one of them is actually coming from https://github.com/Crinsane/laravel-elixir-bower.

**Comment by JeffreyWay** [comment]
This should be fixed in the latest release of Elixir. It'll only trigger one notification per task.

**Comment by atrauzzi** [comment]
Yay!

**Comment by AppSynergy** [comment]
Nice
