### ISSUE TITLE
Pass options to gulp-uglify

### ISSUE THREAD

**Issue by chaosfinity** [laravel/elixir#195]
It would be nice to have some way to pass an options object to gulp-uglify to gain some control over the minification

```javascript
// file ingredients/scripts.js:55

var mergeRequest = function(scripts, outputDir, baseDir, babel, uglifyOptions) {
    ...

    uglifyOptions = uglifyOptions || elixir.config.uglifyJsOptions;

    request.minifier = function (){
      return require('gulp-uglify')(uglifyOptions);
    };

    ...
};


```

**Comment by JeffreyWay** [comment]
Yep - added in a local commit. Coming soon. :)

**Comment by cvitko** [comment]
I would appreciate this as well, I need option to preserve comments when minifying scripts. Some js plugins and libraries require in license to keep author and copyright notice.
Here is a discussion on this topic: http://programmers.stackexchange.com/questions/45033/can-i-minify-javascript-that-requires-copyright-notice

Thanks

**Comment by heivoll** [comment]
As far as I can see, this is not committed anywhere. I need it too, as uglifying breaks my AngularJS app unless I can set tamper: false in the config. 
Pretty sure this should be reopened?

**Comment by cbrown-tribpub** [comment]
In case someone stumbles on this page and wants to see a working example (as of laravel-elixir 6.0.0-9):

```
elixir.config.js.uglify.options = {
  mangle: false,
  report: 'gzip',
  compress: {
    drop_console: true,
    hoist_funs: false
  }
}
```
