### ISSUE TITLE
rubySass errors

### ISSUE THREAD

**Issue by satahippy** [laravel/elixir#198]
I have some problems, when i'm trying to use rubySass
some use cases:

#### 1. Compile one file

```javascript
elixir(function(mix) {
	mix.rubySass('app.scss', 'public/css/');
});
```
#### 2. Compile several files

```javascript
elixir(function(mix) {
	mix.rubySass(['app.scss', 'app1.scss'], 'public/css/');
});
```

#### 3. Compile entire directory

```javascript
elixir(function(mix) {
	mix.rubySass('/', 'public/css/');
});
```

In case (1) everything is good

In case (2) we get an error:
`Error: Errno::ENOENT: No such file or directory @ rb_sysopen - resources/assets/sass/app.scss,resources/assets/sass/app1.scss`

In case (3) we get another error:
`err: [TypeError: Arguments to path.join must be strings] }`

The problem is that the gulp-ruby-sass as a source directory takes a string, but elixir passes the array

(1) works, because of the js implicit types converting (array to string):
`(string)['app.scss'] -> 'app.scss'`

(2) doesn't work, because of 
`(string)['app.scss', 'app1.scss'] ->  'app.scss,app1.scss'`

(3) doesn't work, because `path.join` expects a string as argument
but it gets an array: https://github.com/sindresorhus/gulp-ruby-sass/blob/master/index.js#L55

**Comment by JeffreyWay** [comment]
In Elixir 3.0, the Ruby version of the Sass task has been deprecated. It looks like libsass handles it just fine now.
