### ISSUE TITLE
Make CSS Path Customizable

### ISSUE THREAD

**Issue by puredazzle** [laravel/elixir#199]
Thanks for a great library. 

It would be great if it would be possible to make the CSS path custom. So that the folder hosting the sass/less files could be `/styles` or whatever the user feels for. These lines in https://github.com/laravel/elixir/blob/master/ingredients/commands/CompileCSS.js#L79-L80 would need to be updated. Would be happy to assist with a pull request, if you could point out a direction.

**Comment by vinkla** [comment]
+1 This will make it a lot easier to integrate Elixir into other projects with other directory structures.

**Comment by AppSynergy** [comment]
Yep, +1

**Comment by mikaelmattsson** [comment]
+1

**Comment by JeffreyWay** [comment]
Already added in a local commit. :)

**Comment by vinkla** [comment]
@JeffreyWay Awesome!
