### ISSUE TITLE
Browserify won't import jQuery

### ISSUE THREAD

**Issue by chrisblackwell** [laravel/elixir#201]
Browserify doesn't want to compile using Elixir. I get the error message 

` The code generator has deoptimised the styling of "../resources/components/jquery/dist/jquery.js" as it exceeds the max of "100KB"`

Right now I only have these two lines in my scripts file:
```
window.$ = window.jQuery = require('../../components/jquery/dist/jquery');
var bootstrap = require('../../components/bootstrap/dist/js/bootstrap');
```

If I take the jQuery line out, it works just fine. After doing some research, this looks like a problem with Babel. Since you can't turn off Babel on the Browserify call, this is a problem.

**Comment by JeffreyWay** [comment]
If jQuery isn't playing nicely with Babel, you'll need to blacklist "useStrict", I think.

https://babeljs.io/docs/usage/options/
