### ISSUE TITLE
Please add vueify option

### ISSUE THREAD

**Issue by torniker** [laravel/elixir#203]
Here is the package itself: https://github.com/vuejs/vueify

**Comment by FROLoff** [comment]
+1

**Comment by michaeljcalkins** [comment]
As a temporary workaround you can do this: http://stackoverflow.com/questions/30788135/how-can-i-use-elixir-vueify

```
 1. Install ````sudo npm install laravel-elixir-browserify vue vueify --save````
 2. In your ````gulpfile.js```` add the following:

        var elixir = require('laravel-elixir');
    
        var vueify = require('laravel-elixir-browserify').init("vueify");
    
        elixir(function(mix) {
            // resources/assets/js/main.js
            mix.vueify('main.js', {insertGlobals: true, transform: "vueify", output: "public/js"});
        });

 3. Be Happy =D

**Laravel Elixir Browserify Extension Doc
[Click Here][1]**


  [1]: https://www.npmjs.com/package/laravel-elixir-browserify
```

**Comment by tasarsu** [comment]
+1 a native solution will be appreciated

**Comment by JeffreyWay** [comment]
Upgrade to Laravel Elixir 3, and you add this transformer pretty easy.

### 1. Install Vueify

```
npm install vueify --save-dev
```

### 2. Tell Elixir About Your Transformer

```js
// Gulpfile.js

elixir.config.js.browserify.transformers.push({
    name: 'vueify'
});

elixir(function(mix) {
    mix.browserify('main.js');
});
```

### 3. Follow Vueify Instructions

```js
// main.js
var Vue = require('vue')
var appOptions = require('./app.vue')
var app = new Vue(appOptions).$mount('#app')
```

https://github.com/vuejs/vueify#usage

**Comment by tasarsu** [comment]
Thank you very much

**Comment by michaeljcalkins** [comment]
Just had a chance to confirm this works ty!

**Comment by tasarsu** [comment]
In order to watch vue files I added this code at the bottom of gulpfile.js and it worked like a charm

<pre>elixir.Task.find("browserify").watch("resources/**/*.vue");</pre>

**Comment by juukie** [comment]
Thanks for adding this!

**Comment by ekandreas** [comment]
Thanks tasarsu!

**Comment by acacha** [comment]
This code:

```javascript
elixir.config.js.browserify.transformers.push({
    name: 'vueify'
});
```

is not used here: https://github.com/laracasts/Custom-Components-using-Vueify/blob/master/gulpfile.js

Maybe the info is out of date at this issue?

**Comment by w0bbes** [comment]
@acacha Exilir comes standard with Vueify. Check the config.js for elixir within the node_modules
