### ISSUE TITLE
PHPunit on Windows

### ISSUE THREAD

**Issue by mnshankar** [laravel/elixir#205]
Hi,
As of now, elixir task 'tdd' does not work on windows.
I would like to recommend a minor fix to file
node_modules\laravel-elixir\node_modules\gulp-phpunit\index.js
around line 85.

(this presumes the user has installed git tools and added the location to the included unix tools in their path variable)

```
if (os.platform() === 'win32') {
	command = 'bash vendor/bin/phpunit';
}
```

Thanks!

**Comment by JeffreyWay** [comment]
This would needed to be submitted to the gulp-phpunit project. We don't maintain that.
