### ISSUE TITLE
Browserify only catches first change to a file

### ISSUE THREAD

**Issue by ben-joostens** [laravel/elixir#206]
I'm running into some strange behaviour where only the first change to a file is picked up by browserify, everything else is ignored.

**gulpfile.js**:

```
    mix.browserify('app.js', 'public/js/app.js')
```

I'm requiring a local module in **app.js** like so:

```
var notifications = require('./components/notifications/notifications.js');
var calendar = require('./components/calendar/calendar.js');
```

When running ```gulp watch```, everything works as it should, and when I make changes to one of the required components, it will work, but only the first time I edit that specific file. On subsequent saves, nothing happens. So I can change 3 different files one time and it will compile each time, but when I save one file twice, it will fail on the second.

I'm using elixir version 2.3.13, everything else is up to date too.

**Comment by ben-joostens** [comment]
After a bit of digging around I've found that I apparently had to set polling to true for watchify, since I'm saving on a samba share.

ingredients\** browserify.js** L#57:

changed
```var browserify = watchify(browserifyStream(data));```
to
```var browserify = watchify(browserifyStream(data), {poll: true});```

Seems to be working ok now.. but is there any way to pass the option in my gulpfile?

Some related issues that led me to the fix:
https://github.com/substack/node-browserify/issues/1180
https://github.com/substack/watchify/issues/162

**Comment by JeffreyWay** [comment]
You can now pass options to Watchify in Laravel Elixir 3.0.

cddafe7d3f485d96f080003c5ef3ccf13489b149
