### ISSUE TITLE
Unicode chars being escaped in string interpolation with sass.

### ISSUE THREAD

**Issue by JavoByte** [laravel/elixir#208]
I'm trying to compile bootrstrap with elixir but the breadcrumbs separator, defined in bootstrap like this:

`content: "#{$breadcrumb-separator}\00a0";`

results in a separator like `/\00a0` . That happens because the resulting css has this:

`content : "/\\00a0"`;

I saw this problem happened to someone else and resolved it modifying bootstrap code as described [here](http://laravel.io/forum/07-02-2015-laravel-51-elixir-bug). However, I think I shouldn't edit bootstrap's code as `node_modules` is in `.gitignore`.

**Comment by JeffreyWay** [comment]
That forum link doesn't seem to be working for me. 

I'm not sure that this is an Elixir issue??

**Comment by JavoByte** [comment]
Indeed, it seems the link is down. It was working yesterday :/ . If not an elixir issue, who's fault is this??

**Comment by JordanDalton** [comment]
@JavoByte did you ever find out a solution? I encountered this very problem today.

**Comment by JavoByte** [comment]
Nope,  I tried but no luck . Only solution until now is avoiding use
interpolation

**Comment by gaomd** [comment]
@JeffreyWay I can confirm I have the same issue, this StackOverflow (not mine) question might help: http://stackoverflow.com/questions/31527982/laravel-elixir-5-1-escapes-chars-with-string-interpolation

**Comment by gaomd** [comment]
So it's a upstream bug, this link leads to the solution: https://github.com/sass/libsass/issues/1115
