### ISSUE TITLE
Call to undefined function elixir()

### ISSUE THREAD

**Issue by Gouvi** [laravel/elixir#209]
I'm using Lumen. I have elixir installed and running properly, however when the view tries to call the elxir() function it just bums out on me saying "Call to undefined function elixir()". Let me know if I have got this wrong but Laravel or PHP so to speak would be looking for the function call elixir() correct? I can't quite grasp the concept on how it would perform this operation.

Any insight to help troubleshoot would be great!

Thanks

**Comment by GrahamCampbell** [comment]
We don't define that function for you. You need to do that.

**Comment by GrahamCampbell** [comment]
Here's the one laravel uses for reference: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L682.

**Comment by Gouvi** [comment]
Thank-you!
