### ISSUE TITLE
gulp produces error Cannot find module './config'

### ISSUE THREAD

**Issue by mhh1422** [laravel/elixir#211]
Hi,

When issuing the gulp command, it fails returning the message "Cannot find module './config'", and the trace is within the laravel-elixir module.

Checking the index.js, at line 29, I can see it is requiring ./config.js (lcase c), but the file is actually Config.js (ucase c). Changing that line according to the file name fixed the problem and gulp worked fine!

I am wondering if this is a typo, or I have to create the config file manually and put it somewhere, as previously everything used to work as expected, but this problem started to appear recently.

**Comment by zerojargon** [comment]
I can confirm this. Spent a while trying to work it out, but came to same conclusion.

**Comment by JeffreyWay** [comment]
Fixed. https://github.com/laravel/elixir/commit/156d0d60358e464e378a8eae6f71bc9b0c692570
