### ISSUE TITLE
Laravel elixir calling task according to watch expression

### ISSUE THREAD

**Issue by jadjoubran** [laravel/elixir#212]
I'm sorry if this is not the right place to ask this question.

But I'd love to provide a pull request if this is indeed a missing functionality that you deem useful.

Here's the [stackoverflow question](http://stackoverflow.com/questions/31439385/laravel-elixir-calling-task-according-to-watch-expression) for your reference.

====

Say we have this (simplified) elixir in gulpfile.js:

    mix
    .bower()
    .less('test.less');

The problem is then whenever any file is changed, both `bower` and `less` tasks are executed.  
Is there a way to only execute less when a file in a certain watch path has changed and only execute bower when for example the bower.json file has changed?

The real problem is that with other tasks, my watch process is becoming extremely slow and bower is running everytime I update a less file (which is irrelevant).

Thanks!

**Comment by JeffreyWay** [comment]
That might be an issue with the Bower extension you're using. That's not part of the Elixir core. When you do `mix.less()`, it only watches the source files you give it for changes. Nothing else.
