### ISSUE TITLE
browserify() error after update

### ISSUE THREAD

**Issue by huglester** [laravel/elixir#214]
Hello!

I get this, when compiling `app.js` with browserify:
```bash
EuropeCookie.js: Unexpected token (7:15)
```
Line 7 of EuropeCookie is:
```bash
    cookieName = 'europeCookie';
```

when I leave the constructor(), and comment all those 'class vars', the compilation passes.

What could be the problem?

Switching to 2.3.x version of Elixir - solves the problem

**Comment by laracasts** [comment]
What's the rest of the file look like? There must be some reason why it's saying unexpected token.

**Comment by huglester** [comment]
that is strange, since EuropeCookie.js
has something like this:
```javascript
// var $ = require('../vendor/jquery.js');
var cookies = require("./js.cookie.js");

class EuropeCookie {

    // cookie name for language
    cookieName = 'europeCookie';

    // cookie wrapper (div)
    cookieWrapper = '#europe_cookie_wrapper';

    // cookie closer (<a id="europe_cookie_close">)
    cookieCloser = '#europe_cookie_close';

    // days when europe cookie expires
    expires = 365;


    constructor(expires = null) {
    }
}

export default EuropeCookie;
```

If I remove those class properties (leaving methods at their place), the compilation passes. 
Maybe it has something to do with browserify itself?

**Comment by JeffreyWay** [comment]
At the top of your Gulpfile, can you add `elixir.config.js.browserify.transformers.babelify.options.stage = 0`?

Then try it again. I think it's because you're using experimental ES6/7 features.

**Comment by huglester** [comment]
Hello,

at some point it did help.

Now I same error.
After adding: elixir.config.js.browserify.transformers[0].options.stage = 0

I get this error: 
```
[10:30:14] gulp-notify: [Laravel Elixir] Browserify Failed!: [BABEL] /Users/huglester/Projects/app-opal/public/addons/default/themes/webaslt/js/src/app.js: Unknown option: base.stage while parsing file: /Users/huglester/Projects/app-opal/public/addons/default/themes/webaslt/js/src/app.js
```

so it does not accept this option?

Maybe it should be default? I believe ECMA6 support would be a good addition by default

**Comment by tronghiep92** [comment]
@huglester try ```elixir.config.js.browserify.transformers[0].options.presets.push('stage-0');```
and run ```npm install --save-dev babel-preset-stage-0```
