### ISSUE TITLE
Unable to extend Elixir with custom extensions.

### ISSUE THREAD

**Issue by antoinerey** [laravel/elixir#217]
Hello !

I'm trying to extend Elixir with some custom tasks. But I keep getting :

![capture d ecran 2015-07-28 a 17 06 11](https://cloud.githubusercontent.com/assets/3336873/8935039/fd3439e2-354a-11e5-89a2-9408d174af59.png)

Here is the code :

```javascript
elixir.extend('templates', function() {

  gulp.task('templates', function() {
    return gulp.src('front/**/*.html')
      .pipe(minifyHtml())
      .pipe(ngHtml2js({ moduleName: 'templates' }))
      .pipe(concat('templates.js'))
      .pipe(gulp.dest('public/js'));
  });

  return this.queueTask('templates');

});


elixir(function(mix) {

  mix.sass('app.scss')
    .scriptsIn('front')
    .templates()
    .version([
      'public/css/app.css',
      'public/js/all.js',
      'public/js/templates.js'
    ]);
});
```

- The task works perfectly fine without extending Elixir.
- I'm using Elixir 3.0.5
- I also tried with Elixir 3.0.0, same issue.

**Comment by JeffreyWay** [comment]
You're using the old syntax for creating extensions. If you want to do that, stick with Elixir ^2.0.0.

Otherwise, use the new syntax.

http://laravel.com/docs/5.1/elixir#writing-elixir-extensions
