### ISSUE TITLE
Any way to use Babel with `mix.scriptsIn()` ? 

### ISSUE THREAD

**Issue by antoinerey** [laravel/elixir#218]
Hello !

Is there any way to compile ES6 using `mix.scriptsIn()` ?

I would like to concat JS files from a whole directory, AND compile the ES6 code inside it. I can't find any solution to my issue. Should I set something to the `elixir.config` ?

**Comment by laracasts** [comment]
I don't think you can.

If you're not careful, mix.scriptsIn() can hurt you. There's no specific order that the files get concatenated. So it's generally better to explicitly order the files you want merged.
