### ISSUE TITLE
phpspec not working in 3.x?

### ISSUE THREAD

**Issue by huglester** [laravel/elixir#220]
Hello,

I have this in `gulpfile.js`: 
```json
.phpSpec(['**/*.php'])
```

and I get this error when run gulp:
`TypeError: Object #<Object> has no method 'phpspec'`

**Comment by JeffreyWay** [comment]
Can you do an `npm update` and give it another try? Looks like there was a typo.

**Comment by huglester** [comment]
Yes, it is working now :) was a little away. Thanks
