### ISSUE TITLE
Possible bug with gulp watch in elixir version 3

### ISSUE THREAD

**Issue by unitedworx** [laravel/elixir#227]
When you call .styles or .scripts or generally any recipe a second time then their files are not being watched when running "gulp watch"!

consider the below setup with elixir

```
var elixir = require('laravel-elixir');
elixir(function(mix) {
    mix
        .styles([
            "resources/lib/bootstrap/dist/css/bootstrap.css",
            "views/css/app.css"
        ], 'public/css/frontend.css', './')
        .styles([
            "resources/lib/bootstrap/dist/css/bootstrap.css",
            "views/admin/css/app.css"
        ], 'public/css/backend.css', './');
});
```

now when your run gulp watch and edit the file views/css/app.css elixir will run again but if your make a change to views/admin/css/app.css then elixir wont do anything as if it's not watching that file!
```
gulp watch
```

After paying around i figured that removing the below block of code solves the problem! What i think is happening is that only files in the first styles recipe are watched and not on the second one! not 100% sure what this block of code is trying to prevent. not a JS expect but i am sure you can replicate and solve this quickly 

file: laravel-elixir/tasks/watch.js line:34-36
```
            if (index > 0) {
                return task.name !== tasks[index - 1].name;
            }
```

**Comment by ianhawes** [comment]
I can confirm that commenting out lines 34-36 fixes the same issue I had.
