### ISSUE TITLE
Phpunit problem

### ISSUE THREAD

**Issue by extra90** [laravel/elixir#229]
When I updated to version 3.0.0, all phpunit tests are failing. But when I run manually command phpunit it works fine. Here is the error message:

    Could not load "C:\...\tests\ExampleTest.php".
    ParsePI: PI php never end ...
    Start tag expected, '<' not found

**Comment by rdok** [comment]
Same here, but on Ubuntu system.    
**Command:** `gulp tdd`  (Both on homestead and local machine have same output)

**Output:**
```
Could not load "/home/vagrant/Code/../tests/functional/admin/DashboardTest.php".
ParsePI: PI php never end ...
Start tag expected, '<' not found
[05:30:27] Could not load "/home/vagrant/Code/.../tests/functional/admin/DashboardTest.php".
ParsePI: PI php never end ...
Start tag expected, '<' not found`=
```

**Comment by JeffreyWay** [comment]
Okay - putting this on hold, until Mike fixes it.

**Comment by mikeerickson** [comment]
@JeffreyWay @rdok  I will be addressing this issue over the wekeend

**Comment by a-komarev** [comment]
Got this error:
```sh
*** Debug Cmd: ./vendor/bin/phpunit --colors --debug -c -bootstrap /home/ell/development/elixir3/tests/ExampleTest.php ***

Could not read "-bootstrap".
```

If call manually and remove -bootstrap it starting to produce output:
```sh
ParsePI: PI php never end ...
Start tag expected, '<' not found
```

**Comment by mikeerickson** [comment]
Hey Gang

This issue has been resolved and is available from npm (version 0.8.4 or greater)

@JeffreyWay @rdok @a-komarev

**Comment by a-komarev** [comment]
```json
  "name": "gulp-phpunit",
  "version": "0.8.4",
```

Still got the same error :'(

```sh
       *** Debug Cmd: ./vendor/bin/phpunit --colors --debug -c "/home/ell/development/unit/tests/ExampleTest.php" ***

Could not load "/home/ell/Development/sitterland/tests/ExampleTest.php".

ParsePI: PI php never end ...

Start tag expected, '<' not found
```

**Comment by mikeerickson** [comment]
What platform are you running?
Can you please share your elixir call?

**Comment by dvigueras** [comment]
I'm having the same problem, 

gulp version: 3.9.0
gulp-phpunit: 0.8.4
laravel-elixir: 3.1.1

```
gulp
[18:44:13] Using gulpfile ~/devel/tests/psr2/gulpfile.js
[18:44:13] Starting 'default'...
[18:44:13] Starting 'phpUnit'...

Fetching PhpUnit Source Files...
   - tests/**/*Test.php

[18:44:13] Finished 'default' after 12 ms
[18:44:13]

       *** Debug Cmd: ./vendor/bin/phpunit --colors --debug -c "/Users/daniel/devel/tests/psr2/tests/ExampleTest.php" ***

Could not load "/Users/daniel/devel/tests/psr2/tests/ExampleTest.php".

ParsePI: PI php never end ...

Start tag expected, '<' not found

[18:44:13] Could not load "/Users/daniel/devel/tests/psr2/tests/ExampleTest.php".

ParsePI: PI php never end ...

Start tag expected, '<' not found
[18:44:13] { [Error: Command failed: ] killed: false, code: 1, signal: null }
[18:44:13] gulp-notify: [Red!] Your phpUnit tests failed!
[18:44:13] Finished 'phpUnit' after 348 ms
```

**Comment by mikeerickson** [comment]
I posted 0.8.5 late last night to address some additional issues.  Could you please give it a whirl

If still an issue, please supply the exact call to the mix command, and if you can, send your config file as well. 

I will try to reproduce with your exact calls

**Comment by a-komarev** [comment]
I've tried even like this:
```js
var elixir = require('laravel-elixir');
elixir(function(mix) {
    mix.phpUnit();
});
```

So, mix is pretty clean.

**Comment by mikeerickson** [comment]
Ok, I will have another look when I get home. Something is interfering. With the code you supplied, that's pretty barebones (where are you calling with your configuration file)

**Comment by wlepinski** [comment]
The flag -c used on gulp-phpunit should receive a configuration file and not the file with the TestCase (watched test files).

As a workaround I just changed: ```gulp.src(options.src)``` to ```gulp.src('./phpunit.xml')``` to run all tests.

**Comment by wlepinski** [comment]
I think a good solution would be figure out a way to pass the changed file to the options.pluginOptions.testClass property but the gulp-phpunit skip some conditions if, for example, the configuration file is provided. 

I'll fork the gulp-phpunit to gulp-phpunit-elixir and made the necessary changes to get it working with exilir.

**Comment by abstractFlo** [comment]
I have the same Problem and i'll fix it temporaly with this extension for elixir

```
var Elixir = require('laravel-elixir');
var Task = Elixir.Task;
var gulp = require('gulp');
var phpunit = require('gulp-phpunit');
var notify = new Elixir.Notification;

Elixir.extend('phpunitTest', function() {

    new Task('phpunitTest', function() {
        gulp.src('phpunit.xml')
            .pipe(phpunit('', {notify: true, debug: true}))
            .on('error', function(e) {
                notify.forFailedTests(e, 'phpunitTest');
                this.emit('end');
            })
            .pipe(notify.forPassedTests('phpunitTest'))
    })
        .watch('tests/**/*Test.php')
        .watch('phpunit.xml', 'tdd')
        .watch('/tests/**/*.php', 'tdd');

});

```

Place this snippet to `root/elixir-plugins/phpunitTest.js` and on gulpfile `require('./elixir-plugins/phpunitTest.js'); over the elixir function.

and then call inside elixir function

```
mix.phpunitTest();
```

now you can run `gulp tdd` and all is working correct

I hope there comes a fix on elixir for this problem ;)

**Comment by nealstammers** [comment]
Thanks @abstractFlo - that worked a treat!

The only thing I had to do additionally was:

```
npm install gulp-phpunit --save-dev
```

**Comment by bakerstreetsystems** [comment]
I'm having the same issue as OP. Here is my package.json file:

{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "gulp-phpunit": "^0.8.4"
  },
  "dependencies": {
    "laravel-elixir": "^3.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}

Any updates?

**Comment by hungtruongquoc** [comment]
I put 'phpunit.xml' as the first parameter for the mix.phpunit.

**Comment by TommyC81** [comment]
@hungtruongquoc Thanks, that fixes the problem for me as well!

Everyone else, give it a try: mix.phpUnit('phpunit.xml');

**Comment by a-komarev** [comment]
It's working for me too.
@hungtruongquoc thank you.

**Comment by henriquebremenkanp** [comment]
I had the same issue here on OSX 10.10.5. 
Using mix.phpUnit('phpunit.xml') made it work.

**Comment by JeffreyWay** [comment]
@mikeerickson - So is this an Elixir issue, or a problem with the gulp-phpunit plugin?

**Comment by extra90** [comment]
Using mix.phpUnit('phpunit.xml') work for me too. :)

**Comment by wlepinski** [comment]
> I think a good solution would be figure out a way to pass the changed file to the options.pluginOptions.testClass property but the gulp-phpunit skip some conditions if, for example, the configuration file is provided.

@JeffreyWay The problem of passing the phpunit.xml as the gulp source is that every time I change a file all tests will run. The best i think is figure out a way to pass a --filter attribute during the call to phpunit. Passing up the name of the file that was changed. This way, only the tests inside the testcase changed will be executed.

**Comment by JeffreyWay** [comment]
I'd love a pull request if any of you are up on the issue. I haven't been following this one closely.

**Comment by wlepinski** [comment]
I started working on this last week but I haven't finish the PR yet.

**Comment by mikeerickson** [comment]
@JeffreyWay  @wlepinski I will have a look at this sometime this week, but might not be until weekend as I am on a tight deadline at work before I can get to it :-)

**Comment by jordonbaade** [comment]
@JeffreyWay @mikeerickson I've added a PR to both repositories that should correct this issue.

Definitely failed with my first attempt but I think this solves things from both sides.

Feedback would be lovely, thanks!

**Comment by jhmilan** [comment]
Some problem here (elixir 3.0.0, gulp-phpunit 0.8.4) and it worked by using mix.phpUnit('phpunit.xml');

The weird thing (not sure if I should open a new issue or just comment here) is that phpunit looks like it is run twice. No matter whether is run through `gulp tdd` or `gulp phpUnit`. Output is duplicated. Any ideas? could it be a bad set up?

**Comment by jordonbaade** [comment]
Just a quick FYI, my commit will not fix the situation until @mikeerickson changes the priority in gulp-phpunit.  Until then people will still need to use .phpunit('phpunit.xml').

@jhmilan I'm not sure, but I believe this is due to something gulp-phpunit has in place that spits out phpunit progress as it happens,  If you look at the two they'll contain the same timestamps and memory usages leading me to believe it's not actually running twice.

**Comment by jhmilan** [comment]
@jordonbaade I think you're right. Looks like it is run once but output is duplicated. I'll dig into it.

**Comment by jordonbaade** [comment]
Looks like @mikeerickson took care of it so this commit should now be working.

Huzzah!

**Comment by mikeerickson** [comment]
I am curious (I didn't review this code) what was wrong with the current release of Elixir and gulp-phpunit.  

I ask because I tested with a fresh install of Laravel today and didn't have any issues (worked out of the box)

**Comment by jordonbaade** [comment]
If you tested after implementing your changes to priority in gulp-phpunit, and within the last 19 hours it's because Jeffrey added my commit to add the configurationFile option in Elixir for gulp-phpunit before you made your commits to gulp-phpunit.

If you tested before your changes I have no clue because all my testing showed that configurationFile was unusable, but as soon as you fixed it everything should have worked since configurationFile was already implemented on Elixir's side.

I think I've explained this a few times, but elixir's phpunit() option is passing the php test files and not the phpunit.xml file, which worked fine with an older version of gulp-phpunit, but didn't work with the recent version which always pulled gulp.src even when it wasn't an xml file.

**Comment by mikeerickson** [comment]
Ok, so I am guessing mine was within your 19 hour timeframe.  All is working well so we can put this to rest.

**Comment by mikeerickson** [comment]
FTR, my fixes today including making sure the first parameter was an .xml file before setting it as a configuration file. 

So at this point, out of the box w/ gulp-phpunit is:

This will set -c flag 

mix.phpUnit('pathTo.xml')

     and this will also set -c flag

mix.phpUnit('', {configurationFile: 'pathTo.xml'})



This will not set -c flag

mix.phpUnit('./tests/**/*.php')

**Comment by oldtimeguitarguy** [comment]
So right now on my end, I can use mix.phpUnit('./phpunit.xml') and call gulp manually to execute all tests. gulp tdd does nothing. Is this how it is for everyone else too, or am I missing something?

**Comment by AragornYY** [comment]
@oldtimeguitarguy I got the same problem. I manually adjusted `laravel-elixir/package.json`, made **`"gulp-phpunit": "0.9.0"`**. Please note, `gulp-phpunit@0.9.1` is buggy and notifies 'success' when you have failed tests, so **don't use `^0.9.0` for now**. And then remove old `gulp-phpunit` and install `gulp-phpunit@0.9.0`.

**Comment by michaelGregoire** [comment]
@AragornYY That didn't seem to do the trick with regard to gulp tdd. Even after doing that, gulp tdd doesn't run any tests.

**Comment by AragornYY** [comment]
@michaelGregoire What's the output after you run `gulp tdd`?

**Comment by michaelGregoire** [comment]
@AragornYY 

    [13:48:32] Using gulpfile ~/Code/l5beauty/gulpfile.js
    [13:48:32] Starting 'tdd'...
    Watching for tests...
    [13:48:32] Finished 'tdd' after 26 ms

**Comment by michaelGregoire** [comment]
Strange... it began working as soon as I edited the routes file.

**Comment by oldtimeguitarguy** [comment]
Really? Weird. I've been getting the same errors you have. Maybe I'll edit my routes file...

**Comment by AragornYY** [comment]
@michaelGregoire That's how `gulp tdd` works. It's like `gulp watch`, sits in background just watching, and only runs tests every time you edit and save changes on any file in your `tests` or `app` directory.

**Comment by michaelGregoire** [comment]
I guess I assumed it would run the tests when you first start it.

**Comment by richardbenson** [comment]
Hi there, for the uninitiated and new to npm etc, how long before this patch will be available with an npm update?  Not pushing, just have no idea how long these things usually take.

**Comment by Jmrich** [comment]
Not sure if anyone else is running into this issue, but I can't get laravel-elixir to pull in gulp-phpunit 0.9.0. Laravel-elixir is says it is version 3.2.6 in the package.json but it is still trying to pull 0.8.4 of gulp-phpunit. Manually changing the version in elixirs package.json file still wont pull in 0.9.0. Not sure if I need to wait a little while or if it is something else.

**Comment by mikeerickson** [comment]
@Jmrich you can install gulp-phpunit latest"

$ npm install -S gulp-phpunit@0.9.0
