### ISSUE TITLE
Is it possible to use elixir on shared hosting?

### ISSUE THREAD

**Issue by DenisAlliswell** [laravel/elixir#231]
Hello!

Is it possible to use elixir on shared hostings? 
I mean, if I install node.js, gulp and elixir on local machine and then just copy it with laravel project to hosting is it going to work?

Many thanks in advance!

**Comment by remkobrenters** [comment]
First of all, this is not an issue but a question, second: you're not supposed to use gulp on your production server. You run it on your development or deployment server and push the results (created asset files) to your production server.

**Comment by unitedworx** [comment]
for shared hosting i think you wont be able to ssh into the server and install all those dependancies and run gulp. I think for shared hosting your best bet is to use elixir locally and push the generated files along with your code when you deploy/upload your project on-line.

In a dedicated server or virtual server environment that you have full control of you are free to add "gulp --production" as part of your deployment commands to make sure that each time you deploy your styles and script are minified as well! (when you run gulp or gulp watch locally they are not minified to speed up the process)

**Comment by remkobrenters** [comment]
Still wouldn't run minifying scripts on the production server. Although a minified version should behave exactly as unminified this is not a guarantee. Testing with a unminified version on your deployment system and then hoping for the best when you minify in production is not advisable. A best workflow would be to test the exact same versions and markup before pushing to production.

**Comment by DenisAlliswell** [comment]
I thought it works like on the fly generating assets before request or something. 
Now it's clear. I generate assets on local machine, load them to production server and all set.

Thanks guys @remkobrenters, @unitedworx !
