### ISSUE TITLE
Issue with watchers

### ISSUE THREAD

**Issue by Ryuske** [laravel/elixir#233]
In version ^2.0.0 this works (last line):

```
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir.config.sourcemaps = false;

elixir(function(mix) {
    mix.scripts(['lib/ga.js', 'lib/xay1jab.js', 'lib/jquery.js', 'lib/jquery-ui.js', 'lib/purechat.js'], 'resources/assets/js/lib.js')
        .scripts(['lib.js', 'main.js'], 'public/js/main.js')
        .scripts(['lib.js', 'main.js', 'validation.js', 'user/password.js', 'user/register.js'], 'public/js/user.create.js')
});

elixir.config.registerWatcher("default", "resources/**");
```

however in the latest version it errors saying:
TypeError: Object #<Object> has no method 'registerWatcher'

but running the gulp watch command without the last line wasn't doing anything, and I couldn't find any information about setting up the watcher for things besides extensions. So, it's probably not an error, but I couldn't find any documentation about how to setup the files to be watched with the latest version.

**Comment by JeffreyWay** [comment]
Read the release notes here:

https://github.com/laravel/elixir/releases

There is no registerWatcher method in v3.

I might add a generic mix.watch() method for special situations like this.
