### ISSUE TITLE
Watch with multiple browerify

### ISSUE THREAD

**Issue by rleger** [laravel/elixir#234]
When I use "gulp watch" with multiple browserify tasks it only runs the last one regardless of the file that was modified.
It use to work fine on 2.x

```
mix.browserify('vue/views/vue-first.js', 'public/js/v-first.js');
mix.browserify('vue/views/vue-second.js', 'public/js/v-second.js');
mix.browserify('vue/views/vue-third.js', 'public/js/v-third.js');
```

When watching, only vue-third will be run even if I modified vue-first.

Don't know gulp so I didn't really looked into it..

**Comment by rleger** [comment]
I should mention, vue-third.js will be compiled 3 times.

**Comment by JeffreyWay** [comment]
The way the browserify task is setup makes this difficult. Do you really need to call it multiple times? People typically have a single entry point, like `mix.browserify('main.js')`.

**Comment by rleger** [comment]
I see, the thing is I have multiple pages using vuejs. (I use laravel for the routing)

Each page has its own specific view instance. They don't (need to) talk to each other.

At first I used a single entry point, but then it compiles everything down to a single file. Each page would then load the entire javascript app when it really doesn't need to. Right now I only have 3 pages (with a couple of components) but I'm worried it will become a bigger issue as the app grows. I'm aware browser caching will soften the problem though.

Furthermore, I had to do some javascript trick to check whether #vue-first was present on the page to avoid vue throwing an error on vue-second and vue-third instances.

All in all it seemed easier to compile different files and only load the one needed for each page.

Worst case scenario I could downgrade to 2.x

I'd be glad to hear any other suggestion you have for handling such a scenario.
Thanks!

**Comment by phaza** [comment]
I also call it multiple times. For instance I like to split my js into what goes in `<head>`, what goes before `</body>`. And the same for `/admin/`

**Comment by acoustep** [comment]
I would also like this feature. I tend to have a separate Javascript file for front end and the admin area of the websites I build.

**Comment by JeffreyWay** [comment]
PRs welcome.
