### ISSUE TITLE
Gulp watch not working when looking in parent folder

### ISSUE THREAD

**Issue by gizburdt** [laravel/elixir#235]
Hi,

Sorry for the title, I didn't know for sure what the best name was. This is my `gulpfile.js`:

```
mix.less([
    '../vendor/bootstrap/less/bootstrap.less',
    '../vendor/font-awesome/less/font-awesome.less',
    '../base/less/variables.less',
    '../backend/less/variables.less',
    '../backend/less/style.less'
], 'public/assets/backend/css/backend.css');
```

When running `gulp watch` and saving `style.less`(within `assets/backend/less/style.less`), it doesn't do anything. I think it because of the `../`. 

`gulp` runs completely.

**Comment by JeffreyWay** [comment]
Can you do an `npm update` and try again? That should look in `resources/assets/vendor/...` for those first two files.

**Comment by gizburdt** [comment]
Thanks for the reply, but it didn't solve my problem :(

When I save resources/assets/backend/less/style.less, `gulp watch` doesn't see a change and nothing is compiled. Is gulp watching all files, or just the files in mix.less?
