### ISSUE TITLE
Multiple elixir calling does not work anymore

### ISSUE THREAD

**Issue by Ertenal** [laravel/elixir#238]
Since the last version you cannot define multiple elixir functions. For example, if your gulpfile.js looks like this:

```js
var elixir = require('laravel-elixir');

elixir(function(mix) 
{
	mix.sass('admin.scss', 'public/test');
});

elixir(function(mix) 
{
	mix.sass('main.scss', 'public/test');
});
```

then only the last elixir function works. This was not the case in earlier versions where both the elixir functions got executed.

It seems that the reset of tasks, defined in node_modules\laravel-elixir\index.js on line 17 is doing this.

Is there a workaround for this?

**Comment by JeffreyWay** [comment]
Hmm - wasn't aware that anyone was calling the elixir() function more than once. What's your use-case for doing that? If it makes sense, we can not reset the tasks.

**Comment by Ertenal** [comment]
I've created one application for an admin panel and more generic stuff that i can include in every other application i use. 

This 'core' application uses exlixir to compile the admin assets and the other applications use it to compile their assets.

For now i use require to add a local gulp file like this:

```js
var elixir = require('laravel-elixir')

require('gulpfile.local.js');

// Basic core stuff
elixir(...
```

and the local file:

```js
var elixir = require('laravel-elixir')

// Application stuff
elixir(...
```

**Comment by eduardostuart** [comment]
Same here...

My extensions:

```
var Elixir    = require('laravel-elixir');

Elixir.extend('fonts',  require('./fonts') );
Elixir.extend('images', require('./images') );
Elixir.extend('swf',    require('./swf') );
```

My gulpfile.js

```
Elixir(function(mix) {
    mix.version(["css/app.css", "js/main.js"])
        .copy('./public/css/app.css.map', './public/build/css/app.css.map');
});

// Fonts (Extension)
Elixir(function(mix){
    mix.fonts();
});

// Swf  (Extension)
Elixir(function(mix){
    mix.swf();
});

// Images  (Extension)
Elixir(function(mix){
    mix.images();
});
```

Only the last one (images) is called.

I`m using "version": "3.1.2".

**Comment by eduardostuart** [comment]
```javascript
// Next, we'll reset all tasks. This is mostly for tests.
// Elixir.tasks = Elixir.config.tasks = [];
```
Like @Ertenal said - removing `line 17`... solve this problem `(node_modules/laravel-elixir/index.js)`
