### ISSUE TITLE
Update rev-manifest.json in place?

### ISSUE THREAD

**Issue by wayneashleyberry** [laravel/elixir#239]
Would it be possible to update an existing `rev-manifest.json` in place, as opposed to deleting it and creating a new one? We're using this in production and it causes errors for the second that it's not there... there are other workarounds that we're looking into but I was just wondering if it's possible?

**Comment by JeffreyWay** [comment]
I think that's just how the Gulp plugin works.

**Comment by wayneashleyberry** [comment]
@JeffreyWay there is an option to merge into an existing `rev-manifest.json`, maybe this could be exposed in elixir?

> By default, rev-manifest.json will be replaced as a whole. To merge with an existing manifest, pass merge: true and the output destination (as base) to rev.manifest():

https://github.com/sindresorhus/gulp-rev#asset-manifest
