### ISSUE TITLE
How to develop a forked version locally?

### ISSUE THREAD

**Issue by wlepinski** [laravel/elixir#240]
This is the first time I'm trying to develop a gulp-plugin.

I'm trying to resolve the bug #229 so I forked laravel/elixir and npm link it. After that I changed the package.json and replaced the gulp-phpunit with gulp-phpunit-elixir (my version). I also npm link the gulp-phpunit-elixir on my machine.

After that I created a test project and npm link laravel-elixir to get the local version. I also had to npm link laravel-elixir inside laravel-elixir project because some tasks requires it. So far so good everything was pointing to the local version of everything.

But every time I run the gulp on my test project I get:

```
[10:30:29] Using gulpfile ~/laravel-elixir-testproject/gulpfile.js
[10:30:29] Task 'default' is not in your gulpfile
[10:30:29] Please check the documentation for proper gulpfile formatting
```
I found a similar issue (https://github.com/gulpjs/gulp/issues/833) but the solution provided didn't work for me.

What I'm doing wrong? What is the proper way to develop laravel-elixir locally?

Thanks in advance.

**Comment by wlepinski** [comment]
Hmnn.. When I npm link gulp on every module involved seems to work.

**Comment by JeffreyWay** [comment]
Honestly, I'd rather just get the gulp-phpunit or Elixir repo patched.
