### ISSUE TITLE
mix.version is not fetching files from /public

### ISSUE THREAD

**Issue by kayyyy** [laravel/elixir#241]
See this thread on Laracasts: https://laracasts.com/discuss/channels/elixir/elixir-is-not-versioning-files?page=1

I am using Elixr ^3.0.0 and Laravel 5.1 on Homestead.

**Comment by Francismori7** [comment]
I can replicate the issue.

Files in the gruntfile must be referenced with the public/ path, however the elixir() helper method does not work with public/.

This leads to misunderstandings and counter-intuitive programming methods. Also breaks backwards compatibility.

**Comment by JeffreyWay** [comment]
Okay - I brought that base directory back.

https://github.com/laravel/elixir/commit/b407d80c27be381b90e9df76957a0e435b3ba8a8

**Comment by kayyyy** [comment]
:+1:
