### ISSUE TITLE
Elixir 3 BC

### ISSUE THREAD

**Issue by dbpolito** [laravel/elixir#244]
Old versions of elixir i was able to compile several scss files separately with only one rule, something like this used to do the trick:

```
min.sass('**/*.scss', outputDir + 'css');
```

Now if i do that, it forces to group into a app.css file...

This option is a great feature because you can have one `global.scss` file that loads every page and simply have others like `home.scss`, etc...

**Comment by dbpolito** [comment]
Actually this also would be nice to have for css and js too...

One rule that goes to that folder and minify each one separately and move to output folder, that way we could have one rule to group some files, and another to compile the others separately.

**Comment by JeffreyWay** [comment]
That was changed in Elixir 2, at Taylor's request. You can compile separately by making multiple calls to mix.sass().
