### ISSUE TITLE
Sass is not respecting updated assets path

### ISSUE THREAD

**Issue by spiritix** [laravel/elixir#247]
In my gulpfile.js i have the following function which gets called for each module (custom folder structure).

```javascript
....
    app.preProcess = function(mix, outputPath) {
        mix.sass('*.scss', outputPath);
        mix.babel('*.jsx', outputPath);
    };
....

elixir(function(mix) {
    ....
    _.forEach(modules, function(module) {
        ...
        elixir.config.assetsPath = config.modulePath + module;
        app.preProcess(mix, config.outputPath + module);
        ...
    });
    ....
});
```

This does work for JSX files but not for Sass files, regarding to console output it always takes the path from the first module for all modules.
A very ugly hack like this resolves this issue:

```javascript
    app.preProcess = function(mix, outputPath) {
         var sassPath = '../../../../../../../' + elixir.config.assetsPath + 'sass/';

         mix.sass(sassPath + '*.scss', outputPath);
         mix.babel('*.jsx', outputPath);
    };
```

**Comment by eduardostuart** [comment]
```javascript
var Elixir  = require('laravel-elixir');

// https://github.com/laravel/elixir/blob/master/tasks/sass.js#L56
Elixir.config.assets.css.sass.folder = "/my/sass/folder/";

Elixir(function(mix) {
    mix.sass( 'main.scss', 'public/assets/css');
});
```

**Comment by spiritix** [comment]
I see, but if you look at the Config.js there is no section "assets":
https://github.com/laravel/elixir/blob/master/Config.js#L161

Therefore if I try to set the folder like you suggested I get the following error:
```TypeError: Cannot read property 'css' of undefined ```

If I try to set the path like this it works:
```
var Elixir  = require('laravel-elixir');
Elixir.config.css.sass.folder = '/my/sass/folder/';
```

But the Sass folder just gets appended to the "elixir.config.assetsPath" folder instead of replacing it.
So I still have to do like ```Elixir.config.css.sass.folder = '../../../../';``` etc. to get it working.

Anyway the problem is not that Sass is not respecting the "assetsPath" (it does), but it's not respecting an updated path. 
See this example to demonstrate what I mean:

```
_.forEach(modules, function(module) {
    elixir.config.assetsPath = 'my/assets/path/' + module;
    mix.sass('*.scss', 'output/path/');
    mix.babel('*.jsx', 'output/path/');
});

// First iteration
Fetching Sass Source Files...  - my/assets/path/module1/sass/*.scss
Fetching Babel Source Files...  - my/assets/path/module1/js/*.jsx

// Second iteration
Fetching Sass Source Files...  - my/assets/path/module1/sass/*.scss
Fetching Babel Source Files...  - my/assets/path/module2/js/*.jsx

// Third iteration
Fetching Sass Source Files...  - my/assets/path/module1/sass/*.scss
Fetching Babel Source Files...  - my/assets/path/module3/js/*.jsx
```

See the problem is Sass always uses the path from the first iteration. 
Looks like gulp or whatever is storing the path initial somewhere else.
