### ISSUE TITLE
[Bug] Laravel Elixir minify css incorrectly in production mode

### ISSUE THREAD

**Issue by letrunghieu** [laravel/elixir#248]
What I did:

1. Install Laravel, no modification in `gulpfile.json` 
2. `npm install` inside the laravel folder
3. Uncomment the first line in `resources/sass/app.scss` to include the bootstrap in my `app.css` file.
4. `gulp --production`

My `public/css/app.css` content is:

    /*!
     * Bootstrap v3.3.5 (http://getbootstrap.com)
     * Copyright 2011-2015 Twitter, Inc.
     * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
     *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css*/html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%} ...

When the expected is:

    /*!
     * Bootstrap v3.3.5 (http://getbootstrap.com)
     * Copyright 2011-2015 Twitter, Inc.
     * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
     */
    /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css*/
     html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%} ...

This bug cause the rest of my sass files become one commented line. If I run `gulp` without the production flag, everything works well.

P/S: I ran these steps on two computers, both running Ubuntu 14.04 OS.

**Comment by JeffreyWay** [comment]
Hmm - that's really weird. Surprised no one else has reported this.

The issue must be with the minification plugin we use. Will sell..

**Comment by fredericseiler** [comment]
I tested libsass and ruby sass from command line, and the result is (thankfully) the same as node-sass.

Where did you find the "expected" result ?

From [what I found](http://sass-lang.com/documentation/Sass/Tree/CommentNode.html#invisible%3F-instance_method), if there is a loud comment, it will be untouched (and keeped multiline) in the compressed output but still appended right next to the previous declaration (no new line or carriage return added).

I don't know if it's good or bad (for me, as long as the licenses are in the output...), but if you think it's wrong, you can [contribute directly](http://sass-lang.com/community#Contribute) to the Sass project.

**Comment by letrunghieu** [comment]
Thank you @fredericseiler for pointing that it is not a bug of elixir. I think I'll have more discussion in the SASS repository.

**Comment by frodeknutsen** [comment]
Elixir should probably have {zindex: false} as default pluginOptions for cssnano to fix this issue.

**Comment by frodeknutsen** [comment]
You guys can fix this "bug" if you disable the z-index normalization feature by default in Elixir. Please get this sorted asap.

**Comment by JeffreyWay** [comment]
We already did a couple days ago.
