### ISSUE TITLE
Version clean-up deletes files while copying the versioned folder

### ISSUE THREAD

**Issue by jj-meyer** [laravel/elixir#249]
If .copy() is called after .version(), the cleanup performed by the del() function .on 'end' of .version(), removes files while being copied.

Given the following in my gulpfile.js:
```javascript
...
var pub = function(fileorpath) {
	if (typeof fileorpath !== 'undefined') {
		return elixir.config.publicPath + '/' + fileorpath;
	}
	return elixir.config.publicPath;
};

...

elixir(function(mix) {
    mix
    .sass(['bootstrap.scss','app.scss'],pub('css/style.head.all.css'))
    .scripts(['../../node_modules/bootstrap-sass/assets/javascripts/bootstrap.js','app.js'],pub('js/style.foot.all.js'))
    .version([pub('css/*.css'),pub('js/*.js')])
    .copy(pub('build'),www())
    ;
});
```

When running gulp, the following error is thrown;

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, lstat 'public/build/css/style.head.all.css'
```

The offending code is in ./laravel-elixir/tasks/version.js.

```javascript

            .on('end', function() {
                del(files.paths, { force: true });

```

If the ```javascript  del(files.paths, { force: true }); ``` is commented or removed, the process completes, but the pre-versioned files are not cleaned up.

I propose the solution would likely be to wait for the version() cleanup to complete before continuing with the next task.

**Comment by JeffreyWay** [comment]
Generally, people call mix.version() as the very last task.

I was under the impression that your copy() task wouldn't trigger until that on('end') section completes. Hmm, not sure.
