### ISSUE TITLE
Make the use of build directory when using the elixir helper function optional.

### ISSUE THREAD

**Issue by darwinluague9001** [laravel/elixir#254]
Is it possible to add a config file that will turn on/off the use of build directory when using the elixir helper function?

**Comment by SamuelMS** [comment]
+1.

This would be invaluable to us as well. Our applications are already configured to use the ```/public/build``` directory as the home of our app's front-end code, so when Laravel uses the helper function ```{{ elixir('styles/somefile.css') }}``` and thus forcefully appends a second ```/build``` directory to the already correct versioned file paths in ```rev-manifest.json```, it immediately fails to find the files.

**Comment by laracasts** [comment]
You can do:

```js
mix.version('public/js/foo.js', './other');
```

...and this will make "./other" your build directory. Jus make sure that this is a unique directory.

**Comment by darwinluague9001** [comment]
Hi Jeffrey there are scenarios that I don't want to version my assets during development but during production only. Because sometimes it causes errors especially if I had a lot of assets to compile and sometimes its makes the compilation slow.

What I did right now is I make a config file for elixir.

```
function elixir($file)
    {
        if (!config('elixir.build')) {
            return '/'.$file;
        }

        static $manifest = null;

        if (is_null($manifest)) {
            $manifest = json_decode(file_get_contents(public_path().'/build/rev-manifest.json'), true);
        }

        if (isset($manifest[$file])) {
            return '/build/'.$manifest[$file];
        }

        throw new InvalidArgumentException("File {$file} not defined in asset manifest.");
    }
```

**Comment by SamuelMS** [comment]
@laracasts Sure, I can do that to set the build directory -- and the versioned files will end up in the right location.

My issue, however, is that my index.php file is already in the build directory -- and the ```elixir()``` helper function appends ANOTHER ```/build``` directory to this path, so I end up with Laravel looking for my files in ```root/build/build``` instead of ```root/build```.

Again: the problem is where Elixir is telling Laravel to LOOK, not where the files are placed.

**Comment by GeorgeKagan** [comment]
Anyone encountering this issue in late 2016, the `elixir()` function now accepts a second parameter `$buildDirectory` which defaults to 'build', just pass an empty string. Saved me a lot of workarounds!
