### ISSUE TITLE
Issues installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by andjonno** [laravel/elixir#255]
We cannot seem to install laravel-elixir package on ubuntu 14.04. Seems to fail on trying to install optional dependency `fsevents`. See output below. Note we've only just started having this issue recently.

```
forge@prod:~/example.com$ gulp --production
module.js:338
    throw err;
          ^
Error: Cannot find module './lib/api/node.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/forge/ambi-landing.staging.rgg.agency/node_modules/laravel-elixir/node_modules/babelify/node_modules/babel-core/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
forge@prod:~/example.com$ npm install laravel-elixir
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
/
```

**Comment by JeffreyWay** [comment]
Hmm - and you've tried deleting the node_modules directory, and reinstalling?

**Comment by andjonno** [comment]
Yes we have, didn't fix it unfortunately. This is on a server freshly provisioned by laravel forge. Have tried new instance as well. Still no good.

**Comment by mottihoresh** [comment]
Running ```sudo npm install -g npm@latest``` and ```sudo npm install``` seemed to solve the issue for me

**Comment by bahjaat** [comment]
Something to do with this?
`sudo ln -s  /usr/bin/nodejs  /usr/bin/node`

**Comment by alwinkpc** [comment]
Same problem here. Could this be related to this? https://github.com/strongloop/fsevents/issues/80

**Comment by diegopan** [comment]
Same problem here and fixed with @bahjaat 's : sudo ln -s /usr/bin/nodejs /usr/bin/node

Thanks

**Comment by derrekbertrand** [comment]
If you are here using Ubuntu LTS or Linux Mint:

Ubuntu (and thus Linux Mint) hold back their versions of npm, so you must make sure to update npm via itself. Do this via @mottihoresh 's answer. Also you must be able to type `node -v` and get your node version; if not you'll have to make a symlink as in @bahjaat 's comment.
