### ISSUE TITLE
Gulp Watch (Initial)

### ISSUE THREAD

**Issue by lloy0076** [laravel/elixir#260]
## SUMMARY

When I do "gulp watch" it only does "watch" - this is probably correct behaviour but to get "gulp" to do the initial copies, I need to do "gulp && gulp" or run it simultaneously.

## EXPECTED BEHAVIOUR

That running "gulp watch" would run all the tasks once and  *then*  start the watch.

## POSSIBLE SOLUTIONS

*Expected behaviour?*

This might be expected behaviour if the documentation here:

* http://laravel.com/docs/5.1/elixir#running-elixir

...is correct. If so I think the documentation would be improved if it said, "This does not run the initial gulp task described above."

*If it is a bug?*

If the behaviour is not correct, then I suppose it should run the equivalent of running all the tasks and then watching.

## DETAILS OF MACHINE / VERSIONS ETC

I'm on Windows 10 in a MinGW terminal. Windows updated to 22 August 2015 AU-CST.

**gulp versoin**

```
% gulp version
[13:31:21] CLI version 3.9.0
[13:31:21] Local version 3.9.0
```

**gulpfile.js**
```
% cat gulpfile.js
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.sass('app.scss');
    mix.scripts(['jquery.min.js', 'angular.js', 'lodash.js',
                 'angular-ui-router.js', 'ui-bootstrap-tpls.min.js',
                 'restangular.js', 'app.js'], 'public/js', null);
    mix.version("js/all.js");
});
```

**elixir version**

```
% cd node_modules\laravel-elixir && cat package.json
{
  "name": "laravel-elixir",
  "version": "3.2.5",
  "description": "Laravel Elixir Core",
... truncated output
```

(there is more but I think just the version is enough information).

I haven't tested this on Windows.

I don't believe the actual PHP Laravel version is relevant but composer.lock says:

**composer version**
```
% cat composer.lock
...truncated output
        {
            "name": "laravel/framew
            "version": "v5.1.10",
...truncated output
```

**Comment by JeffreyWay** [comment]
Yeah, this is expected behavior.
