### ISSUE TITLE
`gulp watch` fails to detect changes on Homestead VM

### ISSUE THREAD

**Issue by szainmehdi** [laravel/elixir#261]
I can't imagine why this would be the case, but I've been unable to get `gulp watch` to respond to file changes while running on the Homestead VM. My only clue so far as been this line:

```
npm WARN optional dep failed, continuing fsevents@0.3.8
```

Looking into [fsevents](https://www.npmjs.com/package/fsevents), I found:
> Native Access to Mac OS-X FSEvents

My uneducated assumption at this point is that `gulp watch` is only intended to work 100% on OS X, but that doesn't seem it would be the case to me. 

@JeffreyWay Do you have any insight on this?

Here's my elixir config FWIW:

```javascript
var elixir = require('laravel-elixir');

elixir.config.css.sass.pluginOptions = {
    includePaths: [
        'resources/assets/vendor/bootstrap-sass/assets/stylesheets',
        'resources/assets/vendor/',
    ]
};
elixir.config.js.browserify.watchify.enabled = true;
elixir.config.js.browserify.transformers.push({
    name: 'stringify',
    options: {
        extensions: ['.tpl', '.html', '.txt'],
        minify: true
    }
});

elixir(function(task) {
    task.sass('home.scss')
        .sass('app.scss')
        .browserify('main.js', null, null, {
            paths: [
                './resources/assets/js',
                './node_modules',
                './resources/views'
            ]
        })
        //.version(['css/app.css', 'js/main.js']);
});
```

**Comment by szainmehdi** [comment]
Also, this is what I have in my `package.json` file:

```javascript
{
    // [...] 
    "dependencies": {
       // [...] 
       "laravel-elixir": "~3.2"
       // [...] 
    }
}

**Comment by szainmehdi** [comment]
For what it's worth, gulp's built-in watcher works.

```js
gulp.task('watcher', function() {
    gulp.watch(['resources/assets/js/**/*.js'], gulp.start('browserify'));
});
```

**Comment by szainmehdi** [comment]
Sorry for the bits and pieces of info, but it turns out that turning `watchify` **off** in elixir's config fixes the problem for me.

```js
elixir.config.js.browserify.watchify.enabled = false;
```

**Comment by JeffreyWay** [comment]
I think Homestead should work fine, though I run Gulp locally - to make things as quick as possible.

If anyone else has experienced this, please chime in. Otherwise, closing, as it doesn't seem to be affecting anyone else here.

**Comment by DanielHudson** [comment]
Try this: `elixir.config.js.browserify.watchify.options.poll = true;`

https://github.com/substack/watchify

> opts.poll enables polling to monitor for changes. If set to true, then a polling interval of 100ms is used. If set to a number, then that amount of milliseconds will be the polling interval. For more info see Chokidar's documentation on "usePolling" and "interval". This option is useful if you're watching an NFS volume.

**Comment by GeorgThomassen** [comment]
With a fresh Laravel 5.3 install gulp watch still doesn't detect changes when running in a new Homestead box.

**Comment by GeorgThomassen** [comment]
A functional fix:
https://github.com/laravel/elixir/issues/598
