### ISSUE TITLE
How to run the tests from this repo?

### ISSUE THREAD

**Issue by rafaelbeckel** [laravel/elixir#267]
Hi there,

I just cloned this repository and I'm trying to run the tests.

Running `npm test` returns `"Error: no test specified"`.

So I opened package.json and saw it's, well, expected:
```
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
Then I saw "mocha" and "chai" in "devDependencies", so I `cd`'ed to `elixir-test-dir` and tried to run `mocha`. It outputs:
```
GulpPaths.js:7
    beforeEach(() => paths = new GulpPaths());
                ^
SyntaxError: Unexpected token )
```

Ok, it uses fat arrow syntax. So I tried to run it with Babel:
`mocha --compilers js:babel/register`

Returns:
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'laravel-elixir'
```
Maybe some reference error. Let's try from project root:
`mocha --compilers js:babel/register elixir-test-app/`

Oh, it runs!!
```
  0 passing (4ms)
```
Is that the expected result?

**Comment by JeffreyWay** [comment]
`cd` to the "elixir-test-app" folder, and run `mocha --harmony`.

**Comment by rafaelbeckel** [comment]
--harmony gives me the same error of using Babel. It can't find laravel-elixir package in GulpPaths.js file.

Am I missing something?

```bash
$ mocha --harmony
module.js:338
    throw err;
          ^
Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../elixir-test-app/test/GulpPaths.js:2:17)
    ...
```

**Comment by JeroenNoten** [comment]
Did you find a solution? I have exactly the same issue.

**Comment by vinkla** [comment]
The tests doesn't seem to work? I'm also getting the same error as @rafaelbeckel.
