### ISSUE TITLE
Support gulp-rev options

### ISSUE THREAD

**Issue by miraage** [laravel/elixir#269]
`gulp-rev` provides `merge` option which is useful.
Currently we are unable to use it, for example in loops.

**Comment by JeffreyWay** [comment]
PR?

**Comment by miraage** [comment]
@JeffreyWay how do I launch tests? :sweat_smile:

**Comment by rafaelbeckel** [comment]
@miraage same here: https://github.com/laravel/elixir/issues/267 =D

**Comment by JeffreyWay** [comment]
`cd` to the "elixir-test-app" folder, and run `mocha --harmony`.
