### ISSUE TITLE
baseDir option also for sass and less tasks

### ISSUE THREAD

**Issue by glukash** [laravel/elixir#271]
It would be very nice to have baseDir option for sass and less tasks like the one on scripts task.

**Comment by JeffreyWay** [comment]
Either update your config object, or start the path with a period.

mix.sass('./public/sass/thing.scss');

**Comment by bhulsman** [comment]
@JeffreyWay I've tried any combination, but mix.less(['./resources/themes/default/assets/less/theme.less'], 'public/assets/themes/default/css') nor mix.less(['themes/default/assets/less/theme.less'], 'public/assets/themes/default/css', './resources') is working.

It keeps looking in the /resources/assets/less directory. Could you help me out here?
