### ISSUE TITLE
'Version' task can't be watched

### ISSUE THREAD

**Issue by ppoffice** [laravel/elixir#275]
![image](https://cloud.githubusercontent.com/assets/8849362/9711261/d04c641e-5574-11e5-9125-61f9c328f608.png)

![image](https://cloud.githubusercontent.com/assets/8849362/9711241/b5d3c1a4-5574-11e5-9f44-a9b5c3b5c80d.png)

I used gutil to log watchers and find that 'Version' task watchers may be wrapped twice in an array.

**Comment by ppoffice** [comment]
I think I located the issue here: https://github.com/laravel/elixir/blob/master/tasks/version.js#L71

`src` here is an array-like object, so `Array.isArray` will return `false` and paths will be wrapped redundantly.

Same watching problem can be found in other built-in tasks.

**Comment by SimonJ** [comment]
Maybe its the same problem as this : https://github.com/laravel/elixir/issues/253

**Comment by JeffreyWay** [comment]
Yeah - #253 covers. So closing this one.
