### ISSUE TITLE
Error Install Elixir 

### ISSUE THREAD

**Issue by pedox** [laravel/elixir#282]
it's very annoying to me, sincerely i don't have any problem install elixir, and i try to create project then run `npm install --verbose` all running normal but stuck on some package 

and i also attach logs below

    129047 info postinstall gulp-sass@2.0.4
    129048 verbose unlock done using /Users/pedox/.npm/_locks/gulp-sass-6eb28d2e4dcb5031.lock for /Users/pedox/project/wew/web/node_modules/laravel-elixir/node_modules/gulp-sass
    129049 verbose about to build /Users/pedox/project/wew/web/node_modules/laravel-elixir
    129050 verbose unlock done using /Users/pedox/.npm/_locks/laravel-elixir-de9d40b91791fff3.lock for /Users/pedox/project/wew/web/node_modules/laravel-elixir
    129051 verbose stack Error: shasum check failed for /var/folders/9z/f2hh9glx04d58drjx69sfl840000gn/T/npm-89779-a50f1558/registry.npmjs.org/recast/-/recast-0.10.32.tgz
    129051 verbose stack Expected: e38ead717aef1a2412d5a77cffe9f6d27e5b46ff
    129051 verbose stack Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    129051 verbose stack From:     https://registry.npmjs.org/recast/-/recast-0.10.32.tgz
    129051 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
    129051 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
    129051 verbose stack     at emitNone (events.js:72:20)
    129051 verbose stack     at ReadStream.emit (events.js:166:7)
    129051 verbose stack     at endReadableNT (_stream_readable.js:893:12)
    129051 verbose stack     at doNTCallback2 (node.js:429:9)
    129051 verbose stack     at process._tickCallback (node.js:343:17)
    129052 verbose cwd /Users/pedox/project/wew/web
    129053 error Darwin 14.4.0
    129054 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
    129055 error node v4.0.0
    129056 error npm  v2.14.2
    129057 error shasum check failed for /var/folders/9z/f2hh9glx04d58drjx69sfl840000gn/T/npm-89779-a50f1558/registry.npmjs.org/recast/-/recast-0.10.32.tgz
    129057 error Expected: e38ead717aef1a2412d5a77cffe9f6d27e5b46ff
    129057 error Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    129057 error From:     https://registry.npmjs.org/recast/-/recast-0.10.32.tgz
    129058 error If you need help, you may report this error at:
    129058 error     <https://github.com/npm/npm/issues>
    129059 verbose exit [ 1, true ]
    129060 verbose unbuild node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/node_modules/regexpu

**Comment by JeffreyWay** [comment]
Sorry, not sure. Can't reproduce.
