### ISSUE TITLE
Help: how disable notifications on elixir 3.28?

### ISSUE THREAD

**Issue by jfoliveira** [laravel/elixir#284]
I've just upgraded Elixir from 2 to 3.2.8 and I'm a bit confused as [NPM displays version 3.2.8](https://www.npmjs.com/package/laravel-elixir) whereas [GitHub releases pages](https://github.com/laravel/elixir/releases) displays version 3.0 as the latest.

Anyway, I'm assuming 3.2.8 brings me the latest code - including the changes mentioned on pull request #246.

To disable notifications in Elixir 2, I used to have this in my gulpfile:
```node
process.env.DISABLE_NOTIFIER = elixir.config.production;
```
This worked like a charm in Elixir 2, but no longer works after upgrade to 3.2.8.
I also tried:
```node
elixir.config.notifications = {message: !elixir.config.production};
```
```node
elixir.config.notifications = {};
```
```node
elixir.config.notifications = false;
```
```node
process.env.DISABLE_NOTIFIER = elixir.config.production;
```
None of these options work now.
Would you please provide an example on how to disable notifications in 3.2.8?

**Comment by jfoliveira** [comment]
Anyone?

**Comment by NicolasParada** [comment]
`process.env.DISABLE_NOTIFIER = true;`

**Comment by jfoliveira** [comment]
@NicolasParada thanks for replying, but as I mentioned on my original comment, I've already tried that and it used to work with Elixir 2.* but it's no longer working with 3.2.8.

Which Elixir version are you using?
Are you able to successfully disable notifications with this approach?

**Comment by NicolasParada** [comment]
Yep. 3.2.8 and worked fine.

**Comment by jfoliveira** [comment]
Based on your testimonial I decided to investigate further and came up with a hack that works:
```node
if (process.argv[2] == '--production') {
    process.env.DISABLE_NOTIFIER = true;
}

var elixir = require('laravel-elixir');
```

It seems Elixir and `gulp-notify` just read `process.env.DISABLE_NOTIFIER` while bootstrapping, that's why I need to set `DISABLE_NOTIFIER` value before loading Elixir.

Thanks @NicolasParada!
