### ISSUE TITLE
when running gulp sass and gulp scripts is does not create .version files

### ISSUE THREAD

**Issue by SimonJ** [laravel/elixir#285]
Hey,

It seems like when running `gulp sass` and `gulp scripts` and using the .version, it does not genereate new version files.

are you guys having same issue?.

/Simon

**Comment by SimonJ** [comment]
cc @johnbrowe

**Comment by JeffreyWay** [comment]
It won't version your files if you only run `gulp sass`. You have to do `gulp` or `gulp watch`.
