### ISSUE TITLE
Add support for Browserify plugins

### ISSUE THREAD

**Issue by angusfretwell** [laravel/elixir#286]
As per https://github.com/substack/node-browserify#plugins

Should simply be a matter of duplicating the code which handles custom transforms (i.e. adding `config.browserify.plugins`).

Happy to submit a PR if this seems sensible?

**Comment by angusfretwell** [comment]
PR [here](https://github.com/laravel/elixir/pull/287) if you're interested.

**Comment by JeffreyWay** [comment]
Closing, as we have a pr.
