### ISSUE TITLE
Minification on gulp version.

### ISSUE THREAD

**Issue by crynobone** [laravel/elixir#288]
My typical use case for development is that we mainly going to use development mode for gulp, via either `gulp` and `gulp watch`. 

During deployment however, it would be great if we could just add the the generated styles and scripts (commit to git) and only require to run `gulp version --production` to generate builds/version assets and uglify it at the same time.

Alternatively, it would be nice if we have a dedicated option parameter for this, e.g `gulp version --minify` etc.

**Comment by JeffreyWay** [comment]
I'm not sure if I fully understand what you're asking.

**Comment by crynobone** [comment]
If i commit all unbuild asset and only run `gulp version --production` during deployment on production environment. I would expect the output is minified. The current behaviour at the moment, the build asset output none uglify/minify version.

**Comment by JeffreyWay** [comment]
Yeah, it doesn't work like that. Versioning happens *after minification. So, if you just call `gulp version`, that won't hit the CSS minifier. You have to do `gulp --production`.
