### ISSUE TITLE
Feature request: implement image files versioning

### ISSUE THREAD

**Issue by Zyava** [laravel/elixir#292]
Versioning for css and js files is a great feature. However, sometimes when developers work on the project they need to replace an image with another one. Due to human nature developers can put new image with the same name which means because of CDN and browser cache some users will still see the old image for a long time. The only possibility to prevent this is version image files too. There are already some gulp packages which can help with that https://www.npmjs.com/package/gulp-rev-all and 
https://github.com/farrrr/laravel-elixir-css-url-adjuster.

**Comment by DanielHudson** [comment]
You can already version image files see: http://laravel.com/docs/5.1/elixir#versioning-and-cache-busting

For eg: 

```
mix.version([
			'public/css/*.css',
			'public/img',
			'public/font',
			'public/js/*.js',
		]);
```

**Comment by Zyava** [comment]
@DanielHudson sorry, but you are wrong. Documentation says nothing about versioning images. Also, image names should be substituted with versioned one in the generate css files too...

**Comment by DanielHudson** [comment]
Works for me, and updates paths in the css as well :+1:

Have you tried it?

**Comment by Rjs37** [comment]
I am having one weird issue with versioning my images.

```
mix.version([
    'public/assets/img/**/*'
], 'public');
```
Results in just the img sub directories being versioned. The top level images stay unversioned. 

```
mix.version([
    'public/assets/img'
], 'public');
```
Deletes all the img sub directories and just version controls the top level images. Happens even if I don't override the output directory.

Any suggestions on how I can get both sub directories and the top level versioned?

**Comment by Rjs37** [comment]
Also whilst it does update the image references in my css, to get my relative paths in my css working properly, I had to remove the initial backslash as it adds an extra one at the start of the path.
i.e. /assets/img/image.png becomes //assets/img/image.png

**Comment by Elbandi** [comment]
the problem is: [vinylPaths() fill the files](https://github.com/laravel/elixir/blob/master/tasks/version.js#L28) with files and directory names too, and [del](https://github.com/laravel/elixir/blob/master/tasks/version.js#L52) call will delete the non empty directory too.

**Comment by JeffreyWay** [comment]
So there is or isn't an issue here?

**Comment by Elbandi** [comment]
if we accept, using "dir/**/*.*" is a good solution, this need to be document somewhere, because it's unclear. (eg "you need to call mix.version, with filename path, if you need wildcard use /**/*.* ")

the other solutions are to filter out the "non-empty" directory from files.paths, or modify the del function to  add a "do-not-delete-nonempty-dir" feature.
