### ISSUE TITLE
Elixir mix.sass can't compile sass variables and mixins

### ISSUE THREAD

**Issue by DimitriMikadze** [laravel/elixir#296]
If i right some plain css in variables.scss file it compiles correctly, but if i right just some simple sass like $black: #1d1d1d; the bundle.css file is empty, although gulp-notify says Sass Compiled! its some bug with elixir ?    

    mix.sass([
        '../admin/sass/variables.scss'
    ], 'public/admin/css/bundle.css');

**Comment by SimonJ** [comment]
Are you using gulp watch?

**Comment by DimitriMikadze** [comment]
My gulpfile.js looks like this.

elixir(function(mix) {

    mix.styles([
       '../bower/bootstrap/dist/css/bootstrap.min.css',
       '../bower/font-awesome/css/font-awesome.min.css'
    ], 'public/admin/css/dep.css');

    mix.sass([
        '../admin/sass/variables.scss',
        '../admin/sass/mixins.scss'
    ], 'public/admin/css/bundle.css');

    mix.scripts([
        '../admin/app/**/*.modules.js',
        '../admin/app/**/*.js'
    ], 'public/admin/js/app.js');

});

When i use gulp watch commend it only watches scripts and styles i don't know why, its another problem i guess, but when i use only gulp it compiles all of them, but sass compiled version is empty.

**Comment by SimonJ** [comment]
Are you on windows or mac?

**Comment by DimitriMikadze** [comment]
I'm on mac

**Comment by SimonJ** [comment]
hm try remove your node_modules and do a `sudo npm install` and see if that fix it

**Comment by JeffreyWay** [comment]
I assume that, when you set a variable, you actually use that variable at some point?
