### ISSUE TITLE
Watch custom sass folder

### ISSUE THREAD

**Issue by ido567** [laravel/elixir#297]
I'm using this task to compile all sass files from angular folder to public/css/app.css.
It works well, but the default folder is been watched instead of angular.

````javascript
elixir(function (mix){
    mix.sass('./angular/**/*.scss', 'public/css/');
});
````

After digging into the source code I found out that the watch directory comes from this config _assets.css.sass.folder_, how can I override it?

**Comment by JeffreyWay** [comment]
Elixir.task.find('sass').watch('some/path')

**Comment by ido567** [comment]
Thanks! It will be nice if we could pass the watch directory as parameter to the sass function

**Comment by shanecp** [comment]
If anyone comes across this in the future, the new syntax is,

`elixir.Task.find('sass').watch('some/path/*.scss');`

Note the uppercase 'T' and the wildcard in the path. It didn't work for me when I just had a directory path.

**Comment by briedis** [comment]
@shanecp Dude, the timing could not be better! Thanks :)

**Comment by kamil-kielczewski** [comment]
Fo mi it works when i put this line [elixir.Task.find('sas....] at end of my gulpfile.js :)

**Comment by Daskul** [comment]
how about for browserify? this is not working elixir.Task.find('browserify').watch('someDir') ?

**Comment by kamil-kielczewski** [comment]
I don't have this problem with brwserify - only with sass. Browserify look on files to watch without any problems and additional lines of code (like this one I mention before) in gulpfile.js.

**Comment by blogui91** [comment]
It worked for me in this way: 
    elixir.Task.find('sass').watch('resources/assets/**/*.scss', ['sass'])

**Comment by gavmck** [comment]
I'm getting find is not a function? Have I got this in the wrong place?

```
_laravelElixir2.default.Task.find('sass').watch('resources/assets/*/.scss', ['sass']);
                             ^

TypeError: _laravelElixir2.default.Task.find is not a function

```

**Comment by cmosguy** [comment]
@gavmck I am getting the same thing, I cannot seem figure how to get elixir to watch my files.  I have tried this:

```javascript
elixir(function (mix) {
    mix.sass(['./sass/style.scss'], '../style.css');

    mix.scripts([
        "jquery.js",
        "app.js"
    ], './js');

});

elixir.Task.find('sass').watch('./sass/*/.scss', ['sass']);
```

@JeffreyWay what do we do here?

**Comment by JeffreyWay** [comment]
@cmosguy - It should already watch ./sass/*/*.scss for changes, so you don't have to do that manually.

If it's not working for you, are you using Vagrant/Homestead or anything like that?

**Comment by cmosguy** [comment]
@JeffreyWay No not using that at all... I am in phpstorm on Windows machine.

**Comment by randohinn** [comment]
Tried this in relation to the workaround for #594 for custom path. Also getting `find is not a function`.

**Comment by cmosguy** [comment]
@randohinn I was unsuccessful in using your PR.  I could not figure out how to rebuild the npm package.   Can someone please build this into the registry or please push out an update that works?  @JeffreyWay please?

My fingers are getting fatigued from repetitively doing `gulp`.  I am not sure I understand what the `gulp watch` on the on my custom `./sass` directory is broken, but please fix!!

**Comment by JarvisH** [comment]
I had the same issue, that changes in sass files did not trigger the watch task. The problem was: at one point I had moved my gulp file into `/resources/assets`. Adding this line at the top of the gulp file fixed it:  `elixir.config.assetsPath = './';`

**Comment by shanecp** [comment]
Seems the syntax is changed again. Try this,
```
Elixir.tasks.byName('sass').forEach(function (task) {
 	task.watch('some/path/*.scss');
});
```

From https://github.com/laravel/elixir/issues/578

**Comment by etiennemarais** [comment]
Actually @shanecp that doesn't work for me. Adding the assetsPath config solved it:

```
var elixir = require('laravel-elixir');

elixir.config.assetsPath = './';

elixir(function (mix) {
	
	mix.sass([
		'app.sass'
	], 'css/app.css');

});
```

Then my sassfile lives inside of `./sass/app.sass`
