### ISSUE TITLE
Minifying a CSS file breaks URLs in imports

### ISSUE THREAD

**Issue by REBELinBLUE** [laravel/elixir#298]
I have a CSS file with

```@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);```

When notifying the CSS file is bought inline but the links in that file

`https://fonts.gstatic.com` end up getting changed to `../../fonts.gstatic.com`

This seems to be an issue with `gulp-minify-css` http://stackoverflow.com/questions/32001352/gulp-sass-compiles-google-fonts-css-into-the-file-breaks-protocol-relative-link

but it doesn't look like you can pass additional parameters to `gulp-minify-css` from elixir?

**Comment by oleynikd** [comment]
+1 Have the same issue!!!

**Comment by Lednerb** [comment]
+1 same problem here. 

First i thought it was a sass problem.

**Comment by thesnackalicious** [comment]
Same issue here.

**Comment by oleynikd** [comment]
Dear @JeffreyWay any plans to fix this? It's pretty annoying... Thanks.

**Comment by JeffreyWay** [comment]
If you need to pass options to the minifier, you can now do:

```
elixir.config.css.minifyCss.pluginOptions = { processImport: false };
```

**Comment by JeffreyWay** [comment]
If there's an argument to make that `processImport: false` option a default, let me know.

**Comment by Lednerb** [comment]
In my opinion the 'laravel way' of working with stylesheets is to use sass or less to create them and do the different imports.

For own or vendor css files you have to use `mix.styles([])` so there is not really a need for `processImport: true`.

`processImport: false` should be the default.

**Comment by JeffreyWay** [comment]
I agree. I'm going to plan on making this a default, unless anyone else chimes in...

**Comment by REBELinBLUE** [comment]
👍 thanks @JeffreyWay

**Comment by thesnackalicious** [comment]
@JeffreyWay: I think you should make `processImport: false` the default, as importing Google Fonts inside SASS stylesheets is something that happens regularly and it's liable to trip people up otherwise (took me a little while to find the cause of the issue).

Thanks for being prompt and fixing this.

**Comment by JeffreyWay** [comment]
Okay, done.

**Comment by Lednerb** [comment]
:+1: thanks!

**Comment by smartsal** [comment]
@JeffreyWay  this @import thing still seems to be an issue. 

For anybody else having this problem, this doesn't work anymore 
`elixir.config.css.minifyCss.pluginOptions = { processImport: false };`

but this does work (@import is present in the optput file)
`elixir.config.css.minifier.pluginOptions = { processImport: false };`

Still the fonts are not being imported though, but that might be a separate problem.
