### ISSUE TITLE
SourceMaps when --production

### ISSUE THREAD

**Issue by oleynikd** [laravel/elixir#301]
Dear @JeffreyWay 

First of all - thank you for such a great tool.

I've notices that when you `gulp --production` you still have a `/*# sourceMappingURL=... */` on minified CSS files. Maybe it's not a good behavior for "production"?

**Comment by nivv** [comment]
@oleynikd I've had this thought as well. I just ignore it when pushing to git

**Comment by JeffreyWay** [comment]
Sourcemaps are turned on my default. So they don't get turned off (currently), if you pass the `--production` flag.

You guys think we should make it reflect the environment?

**Comment by oleynikd** [comment]
Dear @JeffreyWay yes!!! Sourcemaps are not meant to be in production... right?

**Comment by cyberdummy** [comment]
Agreed, I do not expect source maps to be built in the production environment.

**Comment by Lednerb** [comment]
I also think that the source maps are'nt needed for production.

For debugging it's great, but what advantage does it have on production?
Do you use it?

**Comment by oleynikd** [comment]
Great. Thank you @JeffreyWay

**Comment by Lednerb** [comment]
Thank you @JeffreyWay but i think theres something missing.

When i run `gulp --production` i still get a source map for `all.css` but the sourcemap  for `.scripts` is not rendered as well as my second `.sass` gulp task.


That's my gulp definition:
```
mix.sass([
        'app.scss',
        './bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss',
        './bower_components/font-awesome/scss/font-awesome.scss',
    ]);

mix.styles([
        './bower_components/bootstrap-select/dist/css/bootstrap-select.css',
        './public/css/app.css',
        'fonticon.css',
    ]);

mix.sass('pdf.scss');
```

**Comment by JeffreyWay** [comment]
Having trouble reproducing. And you're sure you're using the latest version of Elixir?

**Comment by Lednerb** [comment]
Sorry, you're right.

Everything works well. Seems that i used an older version within homestead or so.

Thanks for your fast response!
