### ISSUE TITLE
Sass compile not instant

### ISSUE THREAD

**Issue by tormjens** [laravel/elixir#302]
No matter which project I use Elixir on, the compilation of sass-files take a long time (approx 0.5 - 2sec). While this is not a long time in normal load time, when you're writing your styles and expect to see your changes quickly this is annoying as hell.. 

If i do a "vanilla" gulpfile with just the regular gulp-sass this is compiled almost instantly, so I really can't see how this is an improvement of any sort on my workflow other than that my gulpfile.js is thinner. 

I even see it on videos on Laracasts that the compilation is slow, so I guess this is something that just "is", and not something that's in my head. 

I like the concept of Elixir since the gulpfile is super-intuitive to write, but in action it just performs horrible. 

Are there have any plans to speed up compile time for sass? I have not tested with less.  

### Here are my test results:

The directory structure and contents of app.scss is the same for both projects.

I pull in Bootstrap so they get something to chew on.

```scss
@import "node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss";

body {
	background: red;
	color: white;
}
```

##### package.json
```json
{
  "devDependencies": {
    "bootstrap-sass": "^3.3.5",
    "gulp": "^3.9.0",
    "gulp-sass": "^2.0.3",
    "gulp-sourcemaps": "^1.5.2"
  }
}
```

##### gulpfile.js
```javascript
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('sass', function (){
	gulp.src(['./resources/assets/sass/app.scss'])
		.pipe(sourcemaps.init())
		.pipe(sass({style: 'compressed', errLogToConsole: true}))
  		.pipe(sourcemaps.write('./'))
		.pipe(gulp.dest('./public/css/'))
});

gulp.task('default', ['sass']);
```

##### Terminal result
```shell
➜  Vanilla  gulp
[11:39:21] Using gulpfile ~/Scripts/Gulp/Vanilla/gulpfile.js
[11:39:21] Starting 'sass'...
[11:39:22] Finished 'sass' after 11 ms
[11:39:22] Starting 'default'...
[11:39:22] Finished 'default' after 9.2 μs
```

##### package.json
```json
{
  "devDependencies": {
    "bootstrap-sass": "^3.3.5",
    "gulp": "^3.9.0",
    "laravel-elixir": "*"
  }
}
```

##### gulpfile.js
```javascript
var elixir = require('laravel-elixir');

elixir(function(mix) {
	mix.sass('app.scss');
});
```

##### Terminal result
```shell
➜  Elixir  gulp
[11:34:54] Using gulpfile ~/Scripts/Gulp/Elixir/gulpfile.js
[11:34:54] Starting 'default'...
[11:34:54] Starting 'sass'...

Fetching Sass Source Files...
   - resources/assets/sass/app.scss


Saving To...
   - public/css/app.css

[11:34:55] Finished 'default' after 349 ms
[11:34:56] gulp-notify: [Laravel Elixir] Sass Compiled!
[11:34:56] Finished 'sass' after 1.48 s
```

**Comment by JeffreyWay** [comment]
So this is an issue about your Sass taking a second or so to compile? Sorry - if it's an issue, just use regular Gulp. It's never been a concern for me.

**Comment by tormjens** [comment]
Wow, ok. Thought I'd report av performance issue, but I'll keep myself from doing it in the future. Sorry.

**Comment by JeffreyWay** [comment]
It's sort of like comparing the performance of a PHP page, versus using Laravel to render the page.

Elixir is doing more things, so it can't be as fast. When you call `mix.sass()`, it's:

- Compiling Sass
- Scanning and autoprefixing CSS3 properties, where needed
- Applying dedicated minification
- Concatenating all relevant files
- Adding sourcemaps
- Displaying notifications

It may take a second. Sorry if you thought I was being snarky, but I can't help if that's "annoying as hell."

**Comment by MozMorris** [comment]
@JeffreyWay could we look at making the auto-prefixing & minification steps optional in development?
