### ISSUE TITLE
mix.browserify is not using babelify?

### ISSUE THREAD

**Issue by FutureKode** [laravel/elixir#303]
I understood from the docs that using mix.browserify would also use babelify? Or is that not the case?

I'm seeing instances of array.find() not being converted to es5 so I'm guessing babelify is not being applied?

**Comment by muratsplat** [comment]
Can you share  your gulp file...

Some scenories can be  maked forced to you  to create custom elixir extensions..

In need I have writen my  elixir extention by working Angular + Babel..

**Comment by hownowbrowncow** [comment]
`Array.find` will not be compiled into another format. It is supported by chrome 45, firefox 25, and safari 7.1. Other browsers have not implemented this spec yet.

If you need support for other browsers then you need to include a polyfill. You can use `require('bable/polyfill')` or ES6 version `import 'babel/polyfill'` to polyfill all ES6 features.

Although not very informative, more info can be found http://babeljs.io/docs/advanced/caveats/.

**Comment by FutureKode** [comment]
Thanks guys, so I need to add the polyfill then. This is my gulpfile:

``` var elixir = require('laravel-elixir');

elixir.config.assetsPath = 'OrderingApp';
elixir.config.publicPath = 'public/ordering_assets'

elixir(function(mix) {
  mix.sass('app.scss')
      .copy('OrderingApp/fonts','public/ordering_assets/fonts')
      .copy('OrderingApp/images','public/ordering_assets/images')
      .styles([
        '../node_modules/react-select/dist/default.css'
      ], 'public/ordering_assets/css/vendor.css')
      .scripts([
        '../bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix.js',
        '../bower_components/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js'
      ], 'public/ordering_assets/js/scripts.js')
      .browserify([
        'OrderingApp/js/app.js'
      ], 'public/ordering_assets/js/app.js')
});
```

**Comment by FutureKode** [comment]
I'm not sure how to use the polyfill with elixir

**Comment by muratsplat** [comment]
You think that you create your extention to work with Elixir..

JS World is more complex and everyday something is changed :dancers: 

An Examle: 
https://gist.github.com/muratsplat/db1cc9b98e1d8cd27e48

I wasn't found a way to use ng-Annotate(AngularJS) with work Elixir..

**Comment by hownowbrowncow** [comment]
@FutureKode To use the polyfill in your code put `import 'babel/polyfill';` at the top of your main application file. Given your shared gulpfile, that seems to be `OrderingApp/js/app.js`. This is an example from a project i am working on.

```
import SpaceShooter from './game';
import BootState from './states/boot-state';
import LoadingState from './states/loading-state';
import MenuState from './states/menu-state';
import GameState from './states/game-state';
import 'babel/polyfill';

const game = new SpaceShooter();

game.state.add('boot', BootState);
game.state.add('loading', LoadingState);
game.state.add('menu', MenuState);
game.state.add('game', GameState);
game.state.start('boot');
```

**Comment by nivv** [comment]
@FutureKode  I'm having the same problem. The arrow functions are not compiled either. I'm also using vueify.

Below isn't transformed.
```
setTimeout(() => this.loader.stop(), 500);
```

Therefore the uglify command when using `--production` fails.

My gulpfile: https://gist.github.com/nivv/13306204294f79c742cb

**Comment by JeffreyWay** [comment]
By default, we use Babel stage 2. 

Think I can close this now.

**Comment by oleynikd** [comment]
@JeffreyWay could you please give us some working example with babelify? Thanks.

**Comment by brianlmerritt** [comment]
Our working browserify supports ES6 via babel, and also includes stringify to convert html templates into require-able objects. 

`.browserify('app.js', 'public/js/bundle.js', null, {transform: 'stringify'})`

package.json loads the required modules to make this happen:

` "dependencies": {
    "aja": "^0.3.4",
    "babel-plugin-object-assign": "^1.2.1",
    "bowser": "^1.0.0",
    "knockout": "^3.3.0",
    "knockout-postbox": "^0.5.2",
    "moment": "^2.11.2",
    "notify-send": "^0.1.2"
  },
  "devDependencies": {
    "browserify": "^10.2.4",
    "browserify-shim": "^3.8.9",
    "gulp": "^3.8.8",
    "laravel-elixir": "*",
    "stringify": "^3.1.0"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },`

**Comment by brianlmerritt** [comment]
Oops - sorry, remember to add babel-polyfill in your package.json if you are going to require/import that
