### ISSUE TITLE
BrowserSync won't inject CSS when using .version()

### ISSUE THREAD

**Issue by eurobob** [laravel/elixir#309]
I suppose this is probably to be expected, but it would be useful to combat this.

I'm using .version() to cache-bust. Maybe the elixir asset function could be altered to only get a versioned file in a production environment?

**Comment by JeffreyWay** [comment]
Not sure if there's a way around this.

Possibly, the elixir function could be changed. That would be for a different repo, though. Closing, and will talk with Taylor about it.

**Comment by kevnk** [comment]
With the workaround below, you can have versioned files on production and css injection without page reload on your local development environments: 

**gulpfile.js**
```js
var elixir = require('laravel-elixir');
var inProduction = elixir.config.production;

elixir(function(mix) {
    var versionedFiles = ['js/all.js'];
    if (inProduction) {
      versionedFiles.push('css/app.css');
    }

    mix.version( versionedFiles );
});
```

**example.blade.php**
```php
<?php if (getenv('APP_ENV') == 'local'): ?>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
<?php else: ?>
    <link rel="stylesheet" href="{{ elixir('css/app.css') }}">
<?php endif ?>
<script src="{{ elixir('js/all.js') }}"></script>
```

**Comment by njbarrett** [comment]
@kevnk Your workaround is a good solution. Thanks.
