### ISSUE TITLE
Disabling notifications

### ISSUE THREAD

**Issue by lucasmichot** [laravel/elixir#313]
Would it not make sense to provide either a command line argument, either another option to completely disable notifications ?
The only way to disable them ATM is to add `export DISABLE_NOTIFIER=true;`, but it's hard-coded and it also disables them in local environment, which is a pity.

Disabling notifications with the `--production` flag is set or with a custom `--disable-notify` flag would be IMO valuable

**Comment by JeffreyWay** [comment]
Will be added soon.

**Comment by vinkla** [comment]
+1 This would be a great feature!

**Comment by igorsantos07** [comment]
Would it make more sense to simply disable the usage of `gulp-notify`? That's a dependency that's actually useless in production environments... I just wrote about this on #334.

**Comment by bradmsmith** [comment]
An option to notify on failure only (not success) would be great!

**Comment by lucasmichot** [comment]
> An option to notify on failure only (not success) would be great!

Good idea @bradmsmith  ! But shall be probably its own Github issue

**Comment by eschmid72** [comment]
On a server I got several of this error message.

```
[18:27:31] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    notify-send must be installed on the system.
```
-> check first if `notify-send` is available before using `gulp-notify`.

**Comment by vinkla** [comment]
Any update on this? Possible to turn off yet?

**Comment by FWSimon** [comment]
Think you can disable it with `process.env.DISABLE_NOTIFIER = true;` @vinkla

**Comment by vinkla** [comment]
Awesome! Thank you.

**Comment by FWSimon** [comment]
No problem @vinkla :+1:

**Comment by zWaR** [comment]
@eschmid72 not sure with OS you're on, but on a linux box this solved my issue:
```bash
sudo apt-get update
sudo apt-get install libnotify-bin
```

See also this: https://laracasts.com/discuss/channels/general-discussion/gulp-notify-error-in-notifier-error-in-plugin-gulp-notify-not-found-notify-send

**Comment by ThatTomPerson** [comment]
It would be nice of you could set a verbosity for the notifier 

So you could have messages off but errors on etc

**Comment by alexw23** [comment]
:+1:

**Comment by crabmusket** [comment]
I'm still seeing notification warnings after adding `Elixir.config.notifications = false` to my Gulpfile. I'm running Elixir 6.0.0-1 in the `node:5` Docker container. I ended up just installing `libnotify-bin` inside the container.

**Comment by Promixius** [comment]
@FWSimon your a life saver, adding that to the gulpfile removed all those ugly notifications.
