### ISSUE TITLE
v3.4.1 - vueify doesn't work

### ISSUE THREAD

**Issue by oleynikd** [laravel/elixir#314]
Updated to `laravel-elixir` v3.4.1, run `gulp` = broken app. All `.vue` requirements are missing (empty) in `bundle.js`. However browserify does not produce any error.

Rollback to v3.3.4 - everything works fine.

**Comment by JeffreyWay** [comment]
Can't reproduce. If you can give me some simple steps to test this out...

**Comment by JeffreyWay** [comment]
Okay, closing unless more feedback comes in.

**Comment by marcvdm** [comment]
I ran into the same problem. My issue was that i manually pushed the vueify transformer onto the elixir config in my gulpfile. But after i updated to the latest elixir it was already in the config so i had 2 of the same transformers. I guess it then broke it.

My fix was just to remove my manual push into the config.

**Comment by oleynikd** [comment]
Aha, great tip. I'll try this. Thanks.
