### ISSUE TITLE
vueify not really important  package!

### ISSUE THREAD

**Issue by a-moses** [laravel/elixir#315]
why [vueify](https://github.com/laravel/elixir/blob/master/package.json#L61) is default  package on elixir ?!?

or their is any command to install "clean version" if i don't want Vue in my Project ?

**Comment by parsnick** [comment]
> why vueify is default package on elixir ?!?

Some people will use it and including it by default has no detrimental effect, so why not?

vueify is simply a transform that works on .vue files, so unless you have some very unusual use case where you're using browserify to require() .vue files but you *don't* want them to be treated as vue components, you won't notice it's there.

**Comment by a-moses** [comment]
so now insert all packages for react and for all other  JavaScript UI  ?

if you use any JavaScript framework you can install to your Project and don't force it as a default

**Comment by JeffreyWay** [comment]
Elixir is an opinionated tool. 

@a-moses The same argument could be made for Elixir using Browserify at all. Why not Webpack? 

As @parsnick noted, the Vueify transformation will not add any weight to your compilation. It's a convenience for those who use it.
