### ISSUE TITLE
Elixir watch takes over a minute to start

### ISSUE THREAD

**Issue by davestewart** [laravel/elixir#322]
My experience on other Node projects is that this is because it's watching a folder with 1000s of files in it - is it watching the root folder?

I've now switched to a normal Gulp file where I can better control things and watch runs instantaneously.

EDIT: I'm on Windows 10, though I've found a large amount of files affects Win & Mac

**Comment by JeffreyWay** [comment]
I don't know. Can you give me more information? What does your gulpfile look like?

**Comment by davestewart** [comment]
It's pretty basic (I think this is the one, I backed up all the settings as I was retrying things due to the other issue I raised earlier).

```js
process.env.DISABLE_NOTIFIER = true;

// libs
var gulp	    = require('gulp'),
    elixir		= require('laravel-elixir'),
    livereload  = require('laravel-elixir-livereload');

// config
elixir.config.cssOutput		= 'public/assets/css';
elixir.config.jsOutput		= 'public/assets/js';
elixir.config.sourcemaps	= false;

elixir(function(mix) {
	mix
		.sass(['app.scss', 'kiosk.scss', 'media.scss'], 'public/assets/css')
		.scripts(['kiosk.js'], 'public/assets/js/kiosk.min.js')
        .livereload();
});

```

**Comment by JeffreyWay** [comment]
Can't reproduce this. I suspect it might be related to that livereload third-party plugin you're using.

Can you try it with Elixir's native `browserSync()` option, and see if that changes anything?
