### ISSUE TITLE
Automatic concatenation in v2.+

### ISSUE THREAD

**Issue by davestewart** [laravel/elixir#323]
I just upgraded from 1.0 to 3.0 to get live reload working and found that all my css files were getting everything concatenated into them.

So this, in 1.0 would build separate files:
```js
elixir.config.cssOutput = 'public/assets/css';
elixir(function(mix) {
	mix.sass(['app.scss', 'kiosk.scss', 'media.scss'])
});
```

But in 2 (with adjustments)...

```js
elixir(function(mix) {
	mix.sass(['app.scss', 'kiosk.scss', 'media.scss'], 'public/assets/css');
});
```

...would concatenate them all... but strangely still output 3 files, but each with different output. My 20-line app file would end up with 500+ lines of CSS from kiosk, yet kiosk would be different from app, as would media. 

This seems to be an (undocumented) breaking change from 1.0 (which shipped with my L5) so took me a while to finally work out what was going on.

As well, there's no documentation on methods and parameters, just the rather long-winded docs on [laravel.com/docs/5.1/elixir](http://laravel.com/docs/5.1/elixir). It would be really good to see method signatures and parameters to understand what changes I make to the JS will affect a black-box plugin.

Back to actual SCSS practice, I do all my concatenation in SCSS itself by using partials, which all need to compile into their own CSS files for different parts of the app:

- app (2 partials)
- kiosk (4 partials)
- media

As such, I don't see why you would need to concatenate multiple SCSS files in gulp?

Anyway, as functionality isn't going to change for little old me, perhaps you could add an example to the documentation to explain how to build all these files separately.

Thanks.

**Comment by JeffreyWay** [comment]
Hey, Dave - 

If you want separately compiled files, you have to call the `sass` method multiple times.

```
mix.sass('one.scss')
     .sass('two.scss');
```

**Comment by davestewart** [comment]
HI Jeffrey, yep, got that. Was just suggesting you update the docs to highlight the difference between v1 of the plugin :)
