### ISSUE TITLE
Unmet peer dependency for vueify@4.0.1

### ISSUE THREAD

**Issue by patrikkernke** [laravel/elixir#324]
If I install the laravel-elixir version 3.4.2 there are errors for vueify@4.0.1:
Is there a solution for this dep-error?

![image](https://cloud.githubusercontent.com/assets/1510671/10730798/75394eb2-7bf2-11e5-820b-6da96f5d6ce6.png)

**Comment by takumiabe** [comment]
same problem in my environment with:
```
// package.json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "*", // -> 3.4.2
  }
}
```
and I can avoid this error with v3.4.1.

**Comment by JeffreyWay** [comment]
If you're using vueify, you may need to install some of its dependencies manually. Otherwise, Elixir seems to be installing just fine.

**Comment by SamuelMS** [comment]
It's worth mentioning that these missing peer dependencies are preventing our developers from being able to use ```npm shrinkwrap```, which is somewhat disconcerting as we don't use vueify at all. We've reverted to version 3.4.1 in the meantime.

**Comment by stevestock** [comment]
+1
