### ISSUE TITLE
Separate docs on larvel.com 

### ISSUE THREAD

**Issue by EHLOVader** [laravel/elixir#325]
Is there a way the versions of elixir can have their docs on laravel.com with the major versions of elixir, not Laravel? 

I ask because there are major changes in behavior from v1 through v2 and even more changes for developers of packages going into v3.

**Comment by JeffreyWay** [comment]
Probably not. The transition from v1 to v3 was pretty quick. Things are normalizing now, so the API will change very little from here on out.

**Comment by EHLOVader** [comment]
Thanks for the response. I am not sure how often this will happen going forward, but the differences in v1 and v3 have come up in chats or troubleshooting I have helped with.

Not to mention the issues with the semantic versioning in packages, and NPMs way of resolving conflicts between packages which I have run into while trying to support v2 and v3 within packages. 
I guess I just still see value in matching documentation to the version involved.

Would it be a bad idea to jump Elixir up to 5.1 at some point for the sake of being in sync with Laravel if it is so closely tied together?
