### ISSUE TITLE
Support for JSPM

### ISSUE THREAD

**Issue by kohenkatz** [laravel/elixir#326]
I have switched to using JSPM for all of my new projects - it allows me to write in ES6, and it replaces Bower and Browserify with a single tool (that is actually way more powerful than just the combination of those two).

I would like to write a task for `jspm` similar to the `browserify` and `scripts` tasks that uses [gulp-jspm](https://www.npmjs.com/package/gulp-jspm), but I want to know if there is interest in taking a Pull Request for that before I sit down and do the work.

Thanks!

**Comment by JeffreyWay** [comment]
Maybe start writing this as an third-party Elixir plugin? Then, if a lot of people want it in core, we can implement it? That would probably be a good first step.
