### ISSUE TITLE
babelify dependency loads outdated Babel (v5 instead of v6)

### ISSUE THREAD

**Issue by huntwj** [laravel/elixir#335]
Consequently if we're using Babel 6 and corresponding v6-only configuration options, it breaks the v5 compilation.

    [12:23:52] gulp-notify: [Laravel Elixir] Browserify Failed!: 
    [BABEL] /path/to/project/resources/assets/js/app.jsx: 
    Unknown option: /path/to/project/.babelrc.presets 
    while parsing file: /path/to/project/resources/assets/js/app.jsx

.babelrc:

    {
      "presets": [
        "react",
        "es2015"
      ]
    }

Note that the errors occurs both when the v6 options are in .babelrc as well as when they are in package.json.

**Comment by JeffreyWay** [comment]
Updating this today.

**Comment by JeffreyWay** [comment]
Done.
