### ISSUE TITLE
Can't npm install on homestead

### ISSUE THREAD

**Issue by ido567** [laravel/elixir#340]
I've just cloned the repo on fresh install of homestead.
But I get the following errors when trying to "npm install"

![image](https://cloud.githubusercontent.com/assets/2265476/11146906/f9c346f2-8a1a-11e5-8f99-9e50b9f94a4e.png)

**Comment by ellisthedev** [comment]
This happens for the package in general. Seeing it using my custom CentOS 7 Vagrant image.

- Node v5.0.0
- NPM v3.4.0

Looks like it is Vueify is the culprit requiring Babel 5.8.25; Babel deprecated that version and require packages to now use Babel 6.

**Comment by ido567** [comment]
But it's not merged yet.. Do you know any workaround for that?

**Comment by ellisthedev** [comment]
I'm currently adding it to my local package.json to see if I can get this to work. I'll let you know here in a bit.

**Comment by jondcampbell** [comment]
any luck?

**Comment by ellisthedev** [comment]
Adding these to my local package.json work, but I had to roll back to NPM to v3.3.9 via `npm install -g npm@3.3.9` as well as roll back NodeJS to v0.12.7. This may not be suitable for others and may also mean more issues with Homestead installing an incompatible version of NodeJS (v5.0.0)?

**Comment by ellisthedev** [comment]
Okay, so far my fix has been to force the versions of everything. Since I'm using CentOS, and not Homestead, you need to figure out how to compile Node v0.12.7 on Ubuntu. Also, it appears the NPM packages are having issues because of the `peerDependencies` which are no longer included with NPM 3+. So the fix there is to roll back to NPM 2.14.10. Here is what I've done on my CentOS guest VM and on my OS-X host.

## OS-X Host

1. Force Node version with:
  ```
  brew tap homebrew/versions
  brew unlink node
  brew install node012
  ```
2. Force NPM version with:
  ```
  npm install -g npm@2.14.10
  ```

## CentOS 7 Guest

1. Force Node version with:
  ```
  cd /tmp
  curl -O https://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz
  tar --strip-components 1 -xzf node-v* -C /usr/local
  rm -rf node*
  ```
2. Force NPM version with:
  ```
  npm install -g npm@2.14.10
  ```

## `package.json` Updates

I updated by `package.json` to contain the following:

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "3.0.0"
  },
  "dependencies": {
    "bootstrap-sass": "^3.0.0",
    "jquery": "^2.1.4",
    "jquery.maskedinput": "^1.4.1",
    "jssip": "^0.7.6",
    "juicy-cookie": "0.0.3",
    "moment": "^2.10.6",
    "phpjs": "^1.3.2",
    "pusher-js": "^3.0.0",
    "toastr": "^2.1.2",
    "underscore": "^1.8.3",
    "vue": "^0.12.16",
    "vue-resource": "^0.1.16",
    "zeroclipboard": "^2.2.0"
  }
}
```

The thing to notice here is to *force* laravel-elixir 3.0.0. Then you can safely remove your `node_modules` directory and run `npm install` again. This seems to make everything work again.

Now the effort needs to be on figuring out how to get Laravel Elixir updated and working with NPM v3.4.0+ and Node v5.0.0+.

**Comment by ido567** [comment]
I did exactly what you wrote, and I get this error:
```
> websocket@1.0.22 install /home/vagrant/Code/Bubbuy/node_modules/jssip/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/vagrant/Code/Bubbuy/node_modules/jssip/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/vagrant/Code/Bubbuy/node_modules/jssip/node_modules/websocket/build'
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.14.10
npm ERR! path ../esprima-fb/bin/esparse.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../esprima-fb/bin/esparse.js' -> '/home/vagrant/Code/Bubbuy/node_modules/vue/node_modules/envify/node_modules/jstransform/node_modules/.bin/esparse'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v2.14.10
npm ERR! path npm-debug.log.23b68e628f55d92ded2d519f243d71c0
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.23b68e628f55d92ded2d519f243d71c0' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/Bubbuy/npm-debug.log
```

**Comment by JeffreyWay** [comment]
I've bumped the Vueify dependency. So now it should be using Babel 6.

ccac3d4266a1e74dd84f064a92f37838719ced21
