### ISSUE TITLE
Relative image/font paths in css don't work in .version()'ed css file; Configuring .version() buildFolder

### ISSUE THREAD

**Issue by kevnk** [laravel/elixir#341]
After versioning my css into `public/build/css/` for production, the relative paths to background images and fonts no longer work b/c they're in `public/img/` and `public/fonts/`. It all works locally b/c I'm using [this workaround](https://github.com/laravel/elixir/issues/309#issuecomment-156482968) to inject the css locally without page refresh, but having versioned css in production.

I tried moving everything into `public/build/` and run it from there, but then the versioned files move into `public/build/build/` which leaves me with the same issue.

I guess I could drop the css injection and just reload the entire page on local, but that's a pain.

My workaround (when using [this workaround](https://github.com/laravel/elixir/issues/309#issuecomment-156482968) to inject the css locally without page refresh was the following:

1. add custom helpers.php to override laravel helpers.php

**bootstrap/autoload.php**
```php
// Add custom helpers.php before autoloading other files, including laravel's helpers.php file
require __DIR__.'/../app/Http/helpers.php';
require __DIR__.'/../vendor/autoload.php';
```

2. Add `static $buildDir = '';` and modify the function to use it

**app/Http/helpers.php**
```php
<?php

/**
 * Get the path to a versioned Elixir file.
 *
 * @param  string  $file
 * @return string
 *
 * @throws \InvalidArgumentException
 */
function elixir($file)
{

    static $buildDir = ''; // Used to be 'build/';
    static $manifest = null;

    if (is_null($manifest)) {
        $manifest = json_decode(file_get_contents(public_path($buildDir.'rev-manifest.json')), true);
    }

    if (isset($manifest[$file])) {
        return '/'.$buildDir.$manifest[$file];
    }

    throw new InvalidArgumentException("File {$file} not defined in asset manifest.");
}
```

I'm not sure how/if it's possible to configure elixir with .env variables, but that would be ideal so I could set something like: `ELIXIR_CONFIG_VERSIONING_BUILDFOLDER='build/';` so the elixir helper function can use it AND the elixir js uses it. Instead of manually changing it in both places.

**Comment by Flo-Schield-Bobby** [comment]
+1

**Comment by JeffreyWay** [comment]
Can you not use absolute paths in your CSS files for background images and such?

**Comment by kevnk** [comment]
You're right! Absolute paths without the domain - like `/img/my-image.jpg` should totally work... good thinking... 

I still need to do [this workaround](https://github.com/laravel/elixir/issues/309#issuecomment-156482968) for injecting css instead of it refreshing the page — but the image/font paths work with absolute paths.

Thanks for your help @JeffreyWay - keep rocking it!

**Comment by matomoravcik** [comment]
Image path with "/" prefix works, but what should we do in case like this:
i installed datatable package by npm, in datatable css files there are relative paths like "../images/..." and i can't change this urls every time i npm update, there is no sass with path variable so everything i can do is to copy it to build folder? i dont like such workaround because image names used to be simmilar in many vendor packages like "loader.png", "arrow.png" so if i copy datatable images right into public/build/ it may be overriden in future by other same-named assets. is there a way how to workaround this case?

**Comment by robertmain** [comment]
@kevnk I'm glad I'm not the only one that noticed the lack of CSS injection. I thought I was going crazy for a while 😄
