### ISSUE TITLE
Versioned files via CDN?

### ISSUE THREAD

**Issue by snipe** [laravel/elixir#344]
Hi all,

First off, thanks so much for Elixir. You've managed to single-handedly cut out a bunch of development/deployment process overhead in one fell swoop, and I'm very grateful. 

I was curious - and forgive me if I've missed this in the docs - is there a way to use the `<link rel="stylesheet" href="{{ elixir('assets/css/compiled/app.css') }}">` with a CDN? I have all of my static files pulling from S3, and would prefer to not have to load the style sheets from the local web server, but I didn't see anything in the Laravel docs about it. (Local, staging and prod all have their own Cloudfront/S3 buckets, which are set as config variables in the `.env` file, but I'm not sure if I need to build a helper or something to tell `elixir()` to pull from there.

Thanks in advance!

**Comment by JeroenNoten** [comment]
`elixir()` just returns a string starting with `/build/`, so you could possibly store it on your CDN also in a `build` folder and prepend the address of the CDN in front of it.

An other option is to make a helper function yourself, and use that instead of the `elixir()` helper. The `elixir()` helper is pretty simple, so you can copy it, rename the function and adjust it to your needs:
```
    function elixir($file)
    {
        static $manifest = null;

        if (is_null($manifest)) {
            $manifest = json_decode(file_get_contents(public_path('build/rev-manifest.json')), true);
        }

        if (isset($manifest[$file])) {
            return '/build/'.$manifest[$file];
        }

        throw new InvalidArgumentException("File {$file} not defined in asset manifest.");
    }
```

**Comment by snipe** [comment]
Perfect, thanks! (Was thinking I'd just write a helper, but wasn't sure if that was the preferred way.)

![thank-you](https://cloud.githubusercontent.com/assets/197404/11219936/176472fe-8d12-11e5-9fb1-61086ebf6ae2.gif)
