### ISSUE TITLE
Watch runs only once

### ISSUE THREAD

**Issue by mitjarogl** [laravel/elixir#345]
When I run `gulp watch`, it runs only once. I get no warnings or errors and `gulp watch` is still running. I'm using Homestead 2.1.8

**Comment by JeffreyWay** [comment]
If it's still running, that means it's listening for file changes.

Are you saying that:

1. You run `gulp watch`
2. You change a relevant file
3. Nothing happens

Is that it?

**Comment by mitjarogl** [comment]
@JeffreyWay  Yes.

**Comment by Gercoli** [comment]
@mitjarogl are you using elixir within a Laravel project? I've run into this problem while running elixir outside of laravel. The fix involved changing some config options, namely elixir.config.assetsPath

**Comment by mitjarogl** [comment]
@Gercoli Yes, I forgot to mention, that i'm using elixir outside of Laravel project. Folder structure (resources/assets) is same as in the Laravel project

**Comment by mitjarogl** [comment]
@JeffreyWay I've noticed that problem occurs only with homestead environment. If I'm runing `gulp watch` on my local environment(Windows) it works fine.

**Comment by mitjarogl** [comment]
For now I fixed the problem with adding this line `elixir.config.js.browserify.watchify.options.poll = true;`. Now it successfully watches js files on Homestead.

**Comment by schniper** [comment]
The above fix correctly runs gulp watch, but makes a simple gulp command (without watch) hang.
