### ISSUE TITLE
Have tests in tdd run once before watching

### ISSUE THREAD

**Issue by EHLOVader** [laravel/elixir#346]
I have dug all over, and have a way to do it in code, but wanted to have tests run once prior to watching. Currently I have to edit a file to get results right away.

**Comment by JeffreyWay** [comment]
That's expected behavior for 'gulp watch' with Elixir. It starts watching relevant files for changes, and then triggers the necessary task. You could always do `gulp phpunit && gulp watch`.

**Comment by EHLOVader** [comment]
For some reason I feel differently about the tests than I do the assets.

The results of your asset build are viewed in the browser, in fact if you use the newly bundled `browserSync` it opens the browser and the results right away. To view the results of the tests, you view them in the terminal. To require a manual run of the test for the initial state is counter intuitive and makes the `tdd` explicitly different from the `watch` command as a result. 

Even if this is expected behavior now, I would propose at least a way to eagerly run tests when using `gulp tdd`. Something that might even benefit the `watch` command.
