### ISSUE TITLE
Elixir dosen't generate sourcemaps

### ISSUE THREAD

**Issue by phleobon** [laravel/elixir#349]
Hey, 

I don't know if it is actually a misconfiguration problem or just an elixir problem but whenever in run gulp it does not generate the source maps files.

In the command line :
laravel new elixir-test
cd elixir-test
npm install

Then I edit the app.scss file to import bootstrap
run gulp and check the output in public/css but no source map file at all.

I just can't figure out why this is happening as I have used elixir the same way in many projects and has never faced this issue.

**Comment by stueynet** [comment]
Same problem here. Not sure when this started but I don't get sourcemaps for css files. I do get them for js however.

**Comment by andrewhl** [comment]
+1

**Comment by stueynet** [comment]
After upgrading browserify chokes on any React code whatsoever. 

[12:19:41] gulp-notify: [Laravel Elixir] Browserify Failed!: /resources/assets/js/app.js: Unexpected token (9:16) while parsing file: /resources/assets/js/app.js

I tried it with removing all the js in app js and just having a simple React component and still fails.

**Comment by phleobon** [comment]
on npm the latest release is actually 4.0.3

**Comment by stueynet** [comment]
@phleobon updated to 4.0.3 and same issue. No react works at all.

**Comment by phleobon** [comment]
@stueynet Well, my main issue wasn't really about js and I have to admit that I am pretty lame with react aha.

What you may try is to create a new laravel project with less custom code as possible and check if it still don't works.

If yes then you might open an issue for this one.

But just try from the simplest and increase the complexity of your code to see what exactly makes elixir crash.

**Comment by stueynet** [comment]
Yeah I tested with plain vanilla react hello world code and still breaks. Doesn't like jsx. I'll open a new issue.

**Comment by developez** [comment]
Same overhere, I execute succesfully the gulp command but the source maps aren't created. No error message on gulp. Thus, at the bottom of app.css and all.css there is no source map reference.

**Comment by xtrasmal** [comment]
Same hre
