### ISSUE TITLE
Browserify fails on any react jsx code

### ISSUE THREAD

**Issue by stueynet** [laravel/elixir#350]
Since upgrading to the 4.0.0 it appears that Browserify no longer likes an React jsx code. Are there additional dependencies required now that are no longer in Elixir? Previously simply doing this worked well and compiled all of our jsx including ES2015 syntax.

    mix.browserify('app.js');

Now it cant even compile simple jsx.

**Comment by JeffreyWay** [comment]
Babel no longer includes any plugins out of the box. We're just pulling in the ES2015 preset now.

Looks like there's a React plugin you can grab.

http://babeljs.io/docs/plugins/preset-react/

**Comment by stueynet** [comment]
Thanks Jeffrey. Sadly that introduces a bunch of other issues. Looks like React with Elixir not so simple anymore. I will work out a way and share it.

**Comment by CoderFetch** [comment]
@stueynet This _might_ work in your Gulpfile. I don't see why it wouldn't.
Remember to do ```npm install babel-preset-react```!

```javascript
require('babel-preset-react');

elixir.config.js.babel.options.presets = {
    "react"
};

// or elixir.config.js.babel.options.presets.push("react") if "presets" has been defined
```

**Comment by stueynet** [comment]
Thanks @CoderFetch but still the same error...

Delete node_modules and rebuilt with Elixir 4.0.3 and with babel-preset-react with a .babelrc file as well as your suggestion above. 

```
 gulp-notify: [Laravel Elixir] Browserify Failed!: /resources/assets/js/utils/Redirecter.js: "baseUrl" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.) while parsing file: /resources/assets/js/utils/Redirecter.js

```

**Comment by CoderFetch** [comment]
Can I see the code in ```resources/assets/js/utils/Redirecter.js```? Looks like something is wrong in it.

**Comment by stueynet** [comment]
All working now @CoderFetch. Version bump to 4.0.4

**Comment by stueynet** [comment]
Ain't js grand?

**Comment by CoderFetch** [comment]
Yep. Sometimes.
