### ISSUE TITLE
Bad sourcemaps sources

### ISSUE THREAD

**Issue by phleobon** [laravel/elixir#351]
So after issue #349 has been fixed I have been able to see my sourcemaps files again but there is still something not working properly.

In the generated sourcemap file, the sources array is showing a weird directory : "../../../stdin"

and here is what I get in the devlopper console

![screenshot](https://cloud.githubusercontent.com/assets/10886724/11319836/1d6cf100-9085-11e5-8a99-e902613f4715.png)

As in the last issue I am using very simple code. In the app.scss I have just added a color property to the body.

**Comment by phleobon** [comment]
no one else facing this issue ?

**Comment by phleobon** [comment]
Well after another try it seems that everything is normal. That's weird anyway.

**Comment by developez** [comment]
Any clue about how to obtain source maps again created after gulp command?
