### ISSUE TITLE
BrowserSync breaks Vue integration

### ISSUE THREAD

**Issue by CremboC** [laravel/elixir#352]
I have something as follows:
```
<a href="{{ route('alumni.show', null) }}/@{{ alum.slug }}">
```
It produces: `http://localhost:8000/alumni/abbey-hermann`
I'm sure it's quite clear what's going on here. The issue is, using normal `artisan serv` it produces the correct result. However, once you access the app via BrowserSync it breaks it and produces:
`http://localhost:3000/alumni/%7B%7B%20alum.slug%20%7D%7D`

The moment I put a space after the `/` it seems to work again, but obviously this makes all the links incorrect.

**Comment by JeffreyWay** [comment]
I don't think this is an Elixir bug.

**Comment by CremboC** [comment]
Ok, that's a bit rude but sure... Should I report this in the BrowserSync repository instead?
