### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by ecrmnn** [laravel/elixir#354]
Downloaded fresh copy of Laravel Elixir (^4.0.4) and ran into this error.

What am I doing wrong?

```
[15:31:33] gulp-notify: [Laravel Elixir] Browserify Failed!: Couldn't find preset "es2015" relative to directory "/Users/ecrmnn/Sites/Project/resources/assets/js" while parsing file: /Users/ecrmnn/Sites/Project/resources/assets/js/app.js
{ [Error: Couldn't find preset "es2015" relative to directory "/Users/ecrmnn/Sites/Project/resources/assets/js" while parsing file: /Users/ecrmnn/Sites/Project/resources/assets/js/app.js]
  filename: '/Users/ecrmnn/Sites/Project/resources/assets/js/app.js',
  stream:
   Labeled {
     _readableState:
      ReadableState {
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        highWaterMark: 16,
        objectMode: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
[15:31:33] Finished 'browserify' after 789 ms
```

![screen-shot-2015-11-23-at-15 35 01](https://cloud.githubusercontent.com/assets/1481696/11339598/8f0d1256-91fa-11e5-8658-fcf66e1c41ee.jpg)

**Comment by jarichypma** [comment]
I got the same thing as well. This is a Babel issue.

I fixed it like this:

* npm install babel-preset-es2015 --save --no-bin-links
* npm install babel-preset-react --save --no-bin-links
* Add babel presets to package.json

```json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0"
  },
  "dependencies": {
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "bootstrap-sass": "^3.0.0",
    "browserify": "^12.0.1",
    "font-awesome": "^4.4.0",
    "jquery": "^2.1.4",
    "laravel-elixir": "^4",
    "vue": "^1.0.8",
    "vue-resource": "^0.1.17"
  },
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
}
```

**Note 1**
I use --no-bin-links because I'm on Windows, without the install crashes. On Mac and Linux you can probably do without.

**Note 2**
I added the Babel-settings to my package.json, but there are other options.
See the Babel-documentation for more details.

* https://babeljs.io/docs/usage/babelrc/
* http://babeljs.io/docs/plugins/preset-es2015/
* http://babeljs.io/docs/plugins/preset-react/

**Comment by JeffreyWay** [comment]
None of that should be necessary. Elixir already ships with the necessary presets.

https://github.com/laravel/elixir/blob/master/package.json#L31-L32

**Comment by dbbk** [comment]
@JeffreyWay I just started a fresh Laravel app and I do run into this error. The es2015 and react presets need to be npm installed on the app level.

**Comment by normanyung** [comment]
I'm running into the same issue after an upgrade to v4 from v3. My gulpfile is very vanilla:
```
elixir(function(mix) {
  mix.sass('app.scss')
    .browserify('app.js', 'public/js/app.js')
  ;
});
```

my packages.json:
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9"
  },
  "dependencies": {
    "commonmark": "^0.22.1",
    "hammerjs": "^2.0.4",
    "laravel-elixir": "^4.0.4",
    "lodash": "^3.10.1",
    "moment": "^2.10.6",
    "uuid": "^2.0.1",
    "vue": "^1.0.10",
    "vue-async-data": "^1.0.1",
    "vue-resource": "^0.1.16",
    "vue-router": "^0.7.7"
  }
}
```

**Comment by ecrmnn** [comment]
Confirmed working after 
```
npm install babel-preset-es2015 --save
npm install babel-preset-react --save
```

**Comment by jarichypma** [comment]
Hi @JeffreyWay 

Today I tried to get gulp running without loading the babel-presets in my package.json, but I can't get it working. Eventhough the packages are loaded within Elixir, it somehow doesn't seem to work.

It occurs when browserify wants to compile the javascript. It gives the same error every time:

```
gulp-notify: [Laravel Elixir] Browserify Failed!: Couldn't find preset "es2015" relative to directory "/local/path/to/resources/assets/js"
```

I tried it on my win7-machine and on my forge managed digital ocean server, both give the same error. Emptying the npm cache, uninstalling the packages, neither resolves the issue. Only installing the two above mentioned babel-preset packages solve the issue.

Do you have any clue how this can be fixed?

**Comment by JeffreyWay** [comment]
Can you all confirm that you're using the latest versions of Node and NPM?

I don't understand why none of this happens for me..

**Comment by dbbk** [comment]
Are you sure you don't have them installed globally?

**Comment by normanyung** [comment]
running on ubuntu 14.04 managing node with NVM.
```
$ node -v
v4.2.2
$ npm -v
2.14.7
```

**Comment by JeffreyWay** [comment]
I just ensured that I don't have anything installed globally, and then did:

- laravel new app
- npm install
- set Gulpfile to mix.browserify('main.js')
- run gulp

Everything compiled correctly. No errors.

Two things:

1. Can anyone else confirm that they don't encounter any issues?
2. I'm using Node 5.1 and NPM 3.3.12

**Comment by thoughts1053** [comment]
NPM 3 handles peer dependencies differently than v2. All the dependencies are probably flat in your node_modules folder. With v2, I have nested node_modules directories under laravel-elixir.

**Comment by ecrmnn** [comment]
```
node -v
v4.2.1
npm -v
2.14.7
```

Upgrading now to see if it's working here with npm 3

**Comment by jarichypma** [comment]
I upgraded to npm -v 3.4.1. (node is on 4.2.2) and did some additional testing.

I think I might now what the problem is. Usually I install the packages without bin-links (npm install --no-bin-links) as described [the Laravel docs](http://laravel.com/docs/5.1/elixir#installation). When I do install the bin-links it works without any problem.

As long as I install without bin-links, the problem keeps popping up. 
So to me it seems there's two options:

1. Install with bin-links (and don't use --no-bin-links on windows as the Laravel docs suggest)
2. Install without bin-links on Windows (follow the Laravel docs) and manually pull in babel-preset-es2015 and babel-preset-react

**Comment by JeffreyWay** [comment]
Glad to see it's fixed. But that's still weird, though. I wonder why npm 2 is an issue. That's a problem..

**Comment by normanyung** [comment]
If you need another confirmation, upgrading to node/npm 5.*/3.* fixed the issue for me. 

I was intentionally using the node/npm 4.*/2.* branch bc LTS but don't mind switching to 5.*/3.* for the time being.

**Comment by ecrmnn** [comment]
Upgraded to npm 3.4.1, works now.

Maybe add something like this in ``package.json`` ?

```
"engineStrict": true,
  "engines": {
    "npm": "^3.4.1"
  }
```

**Comment by WolfieZero** [comment]
I was having the same issue but with `mix.babel('file.js');` (following [this lesson](https://laracasts.com/series/painless-builds-with-laravel-elixir/episodes/3)) but also having the issue with what the OP said. I did an update so my NPM and Node where all fresh:

    node -v
    v5.1.0

    npm -v
    3.5.1

And my copy of Laravel was build that morning but still ran into the issue. What I did to resolve it was completely remove Laravel and reinstall the project and it worked again. 

So if anybody is still having issues it's probably best to try **deleting `node_modules` folder and reinstalling all local packages via `npm install`** with the newly updated NPM and Node versions.

**Comment by zimonline** [comment]
I get this on a new install of homestead


``` bash
node -v
v5.0.0
```
``` bash
npm -v
3.3.6
```
``` bash
laravel new npmbug
cd npmbug
```
``` bash
cat package.json
```
``` json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "laravel-elixir": "^4.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}
```



``` bash
npm install
...... 
loads of OK stuff then

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/Code/npmbug/node_modules/.bin/acorn'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/npmbug/npm-debug.log

```

**Comment by Rogerkael** [comment]
I had the same error, I downgraded to elixir 3 and everything went fine.

**Comment by boovad** [comment]
I had the same problem. I used this solution:
  npm install babel-preset-es2015 --save
  npm install babel-preset-react --save

Thanks.

**Comment by lesaff** [comment]
I had the same error and installing both
```
npm install babel-preset-es2015 --save
npm install babel-preset-react --save
```
works.

I am using `"laravel-elixir": "^4.0.4"`

**Comment by ricardogobbosouza** [comment]
Please update Node and NPM

Node v5.1.0
```
https://nodejs.org/
```
NPM v3.3.12
```
sudo npm install npm -g
or
npm install npm -g
```

**Comment by ecrmnn** [comment]
Best way to fix this issue is by updating NPM to 3.x.x.

Closing this.

**Comment by thomaswdufour** [comment]
The solution posted by @lesaff worked for me.  Tried running Gulp in between running those commands and it faulted on react.  npm installed babel-preset-react and everything went off without a hitch.

**Comment by ecrmnn** [comment]
@thomaswdufour

**Comment by Rogerkael** [comment]
Updating node to 5.1 and elixir to 4 worked for me

**Comment by Helfull** [comment]
can confirm updating node to 5.1 solves the problem

**Comment by Rogerkael** [comment]
I had this problem running node 4.2.2 with elixir 4, I downgraded elixir to 3 and it get solved, days after upgraded elixir to 4 and node to 5.1 and also solved it as well, I am running Elementary OS freya based on Ubuntu 14.04.

**Comment by Rogerkael** [comment]
I don't know, I haven't used Windows in a long time. This combination works in my system 
![screenshot from 2015-12-01 10 33 48](https://cloud.githubusercontent.com/assets/6810119/11505211/52a3e966-9817-11e5-9906-a82d488e7281.png)

**Comment by normanyung** [comment]
@ecrmnn While one can solve this by upgrading node/npm, I don't think it was @JeffreyWay intention to require everyone to upgrade to npm v3 in order to use elixir 4 so maybe this issue should remain "open"? 

@JeffreyWay will elixir v4 be patched to work on node 4.x/npm2.x or is node/npm 5.x/3.x now a requirement?

**Comment by davidhemphill** [comment]
Is the final consensus that we should update to node 5.1.0? This broke my build today and I've spent quite a bit of time trying to resolve this. :-)

**Comment by raftalks** [comment]
very strange, this issue is not resolved to me after upgrading to node 5.x and npm 3.x, I do get the same error : gulp-notify: [Laravel Elixir] Browserify Failed!: Couldn't find preset "es2015" relative to directory...

**Comment by ecrmnn** [comment]
@raftalks have you tried deleting your ``node_modules`` directory and then run ``npm install`` ?

**Comment by raftalks** [comment]
@ecrmnn Yes! After deleting and re-installing have fixed it now

**Comment by tjwudi** [comment]
@normanyung ++. Everybody has different environment needs. Simply asking people to upgrade to node 5 is **not** a solution.

**Comment by Helfull** [comment]
@tjwudi if you cant upgrade to node5, you could stay with an older version of Elixir.

**Comment by SERVANT14** [comment]
Just throwing this in here. 

With **CentOS 7 (Desktop), Node 4.2.2 and NPM 2.14.7 via [NVM](https://github.com/creationix/nvm) 0.26.1**.

After upgrading to Laravel 5.2, I also went to Elixir 4 (4.1.1). I experienced the same issue after running `npm update`. I then ran these two and gulp in between to verify they were both needed: 

```
npm install babel-preset-es2015
npm install babel-preset-react
```

Gulp ran great after these two. I then did a:

```
npm cache clear
rm -rf node_modules
npm install
```

This was with my `package.json` matching Laravel 5.2's for the Elixir and Bootstrap version specs (have some other packages as well).

After the install, I got the same error:
```
Error: Couldn't find preset "es2015" relative to directory "/.../laravel/resources/assets/js/some-dir" while parsing file: /.../laravel/resources/assets/js/some-dir/home.js
```

Then I **upgraded to Node 5.3.0 and NPM 3.3.12** (`nvm install stable` Yay!)

Ran these guys again:
```
rm -rf node_modules
npm install
gulp
```

Success!

@tjwudi Check out NVM. I've found it useful:
* https://github.com/creationix/nvm
* https://github.com/coreybutler/nvm-windows

**Comment by tjwudi** [comment]
Just to add [n](https://www.npmjs.com/package/n2), this is yet another better node version manager. @SERVANT14

**Comment by mikerockett** [comment]
Not keen on updating Node to v5.

```
$ node -v && npm -v
v4.2.6
3.7.1
```
Running this on Windows, and the error persists.

Do I really need to upgrade to Node 5? Anything else I can do?

**Comment by tiffoknee** [comment]
I'm having this problem after installing the babel presets using latest stable versions of node and npm..

node -v && npm -v
v5.6.0
3.6.0

I ran this:
npm install babel-preset-es2015
npm install babel-preset-react

and tried deleting node_modules and reinstalling. No dice.

`Error: Couldn't find preset "es2015" relative to directory "/Users/../react-common-components" while parsing file: /Users/../react-common-components/MyFile.react.js`

**Comment by zimonline** [comment]
Try install it globally with -g

**Comment by tiffoknee** [comment]
That's what I originally did. I had to install it locally in the common components dir as well to get it working.

**Comment by lloy0076** [comment]
Got the error.

```
[lloy0076@newlines NewLines]$ node -v && npm -v
v0.10.36
1.3.6
```
Fixed:

```
[lloy0076@newlines NewLines]$ vim package.json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "laravel-elixir": "^4.0.0",
    "bootstrap-sass": "^3.0.0",
    "jquery": "~2.2.0",
    "babel-preset-es2015": "~6.5.0",
    "babel-preset-react": "~6.5.0"
  }
}
```

The last two were added by an "npm install FOO --save".

Part of my composer.lock:

```
            "name": "laravel/framework",
            "version": "v5.2.20",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel/framework.git",
                "reference": "d4ff9a1e3e9b2f99f8f3e957876e343d804d944f"
            },
```

**Comment by Eein** [comment]
I figured out a solution to a similar issue with mac.
You shouldn't need to install anything globally, the issue in my case resided with the fact that there was a .babelrc in my home folder. If you delete it, the problem should go away..

My explanation for this problem here: https://github.com/phoenixframework/phoenix/issues/1410#issuecomment-188433791

**Comment by thepianist2** [comment]
tnx jarichypma.

**Comment by geodeveloper** [comment]
Upgrading to 3.x fixed the problem but I had to delete **node_modules** and run again **npm install**

**Comment by callmeNewbie** [comment]
it works in me using installing babel in npm

**Comment by sneakyfildy** [comment]
why the hell is is relative to processed directory I cannot f understand this!

**Comment by daoyuly** [comment]
I fixed it  add .babelrc

**Comment by crabbly** [comment]
I got the same issue and problem was my node and npm outdated versions. 
Updated node to v5.10.1 and npm to v3.8.3.
Using Elixir v6.0.0-1.

**Comment by adamloving** [comment]
In my case, I had a (hidden from view) .babelrc file in a parent directory. I had recently moved some files around. Once I moved this file to the right place, the problem was solved.

**Comment by mariordev** [comment]
I kept getting this error when running gulp: "Browserify Failed!: Couldn't find preset "react" relative to directory..." I have node v4.4.3 and npm v3.8.7.

I was able to fix it by running:

`$ npm install babel-preset-react --save-dev`

**Comment by mrobit** [comment]
@adamloving this was my issue too. Removed the parent `.babelrc` and everything just worked fine.

**Comment by eshcherbakov** [comment]
My solution witch is great work:

.pipe(babel({
    presets: [require('babel-preset-es2015')]
}))

Thanks!

**Comment by steady-daddy** [comment]
@ecrmnn worked for me. Thank you.

**Comment by StefanNeuser** [comment]
The Problem could be solved with the keyword "relative" as mentioned.

**Comment by TrederusMaximus** [comment]
npm install babel-preset-es2015 --save
npm install babel-preset-react --save

Also solved my problem. I am running Laravel 5.2
