### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by aleemb** [laravel/elixir#356]
Two issues, both related to developer experience:

If I define my config as:

    elixir.config = { production: false }

It breaks elixir, likely because `elixir.config` is being overridden. Maybe you can merge/extend `elixir.config` to allow for this?

Having to turn on the production flag is worrying--what if a dev forgets to turn it on before the final push. It would be safer and more sensible to enable production by default and allow for `--development` to be passed in as a flag.

**Comment by JeffreyWay** [comment]
If you over-right Elixir's config object, then that's expected behavior, right? If I do `$ = 'not jquery', then the same is true.

Production takes longer, so I'd rather make --production opt-in.

**Comment by aleemb** [comment]
Regarding config, the below pattern is fairly normal for nearly every JS lib out there,

```
foo = {a: 'apple', b: 'ball'}
bar = {a: 'ant', c: 'cat'}
$.extend({}, foo, bar); // {a: 'ant', b: 'ball', c: 'cat'}
```

I flipped the production logic manually, for anyone else interested:

```
// gulpfile.js
var gutils = require('gulp-util');
elixir.config.production = !gutils.env.dev;   // enable production mode by
                                              // default unless --dev is passed
```
