### ISSUE TITLE
Piping through other commands

### ISSUE THREAD

**Issue by aleemb** [laravel/elixir#357]
In gulp one would normally do something like:

    gulp.src(paths.js)
      .pipe(uglify())
      .pipe(includer())
      .pipe(jshint())
      .dest('public/js/appjs')

I couldn't find any way to achieve this in Elixir, so if I want to pipe the output of `mix.scripts` through a custom task or gulp task like `mix.scripts('foo.js').pipe(includer())`.

**Comment by JeffreyWay** [comment]
Elixir is a custom wrapper. So you're not going to use Gulp things, like `pipe`. You can create a custom extension if you want. Otherwise, just use the API Elixir provides. It should be most common things for you automatically.

**Comment by aleemb** [comment]
That's a bummer, streams piping is Gulp's claim to fame after all. Would still like to hear your thoughts on the recommended approach. Grabbing the output of mix commands for further processing--for example piping the output of `mix.scripts()` to `includer()`--would require knowing the output path of `mix.scripts()` and then processing *everything* in that path, as opposed to only files that were affected by `mix.scripts()`.

**Comment by NitroBAY** [comment]
That's a pity. Are you sure that you couldn't include pipe in your 'custom wrapper' ?
