### ISSUE TITLE
Combine scripts performance and feature enhancement

### ISSUE THREAD

**Issue by aleemb** [laravel/elixir#358]
Following on from the docs example to combine scripts:

```
elixir(function(mix) {
    mix.scripts([
        "jquery.js",
        "app.js"
    ]);
});
```

This processes and combines both scripts. I have `jquery.min.js` which is pre-processed. It would be ideal if I could just combine this because,

1. jQuery and other large libraries don't recommend using pre-processed versions since minifying has been known to introduce bugs.

2. It takes fairly long since the file is sizeable. For this particular example, it's better to load jQuery via CDN but for many other libs such as `bootstrap.mins.js` it is desirable to combine it without having to re-process it.

I am rooting for an elegant and easy way to pipe through elixir commands #357 which would free up developers to do whatever they want until elixir catches up.

**Comment by jp7carlos** [comment]
Sorry if I didn't understand your problem, but couldn't you set "config.production = false", so it won't uglify your files?

**Comment by aleemb** [comment]
@jp7carlos that would be all or nothing, either minify everything or nothing. jQuey, Bootstrap.js or any of their ilk should never be minified whether in production or development mode as it can introduce new bugs and degrade performance.

**Comment by JeffreyWay** [comment]
There's no simple way at the moment to selectively deactivate minification with the `mix.scripts()` method.

One option is we could add a generic `mix.concatenate()` method that does nothing more than combine the given array of files. Would that do the trick for your needs?

**Comment by n7olkachev** [comment]
:+1::+1::+1: for `mix.concat`.

**Comment by aleemb** [comment]
I have since switched back to Gulp for perf and control (Elixir breaks piping/streams which is fundamental to Gulp), however, in my own setup I do have a concat task which has served me well (with an HTTP 2 setup, this is no longer ideal though).

**Comment by aleemb** [comment]
Probably worth mentioning that `gulp-bower` also makes things much easier when dealing with vendor packages since Elixir encourages using bower.

**Comment by jp7carlos** [comment]
It's off-topic, but i use https://github.com/ck86/main-bower-files and elixir together:

    var bower = require('main-bower-files');
    elixir(function(mix) {
        mix.scripts(bower('**/*.js'), 'public/js/bower.js', '/');
    });

**Comment by aleemb** [comment]
@jp7carlos it's actually slightly on-topic. I meant to point to the same package, not gulp-bower. It is indeed very handy.

**Comment by JeffreyWay** [comment]
Elixir encourages using bower?? No it doesn't.
