### ISSUE TITLE
Failed to parse json laravel-elixir/node_modules/browser-sync/node_modules/opn/node_modules/object-assign/package.json

### ISSUE THREAD

**Issue by obonyojimmy** [laravel/elixir#360]
I get below error when trying to install elixir using npm install 

npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /var/www/html3/laravel/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/opn/node_modules/object-assign/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Linux 2.6.32-042stab111.11
npm ERR! command "/usr/local/bin/node" "/usr/bin/npm" "update"
npm ERR! cwd /var/www/html3/laravel
npm ERR! node -v v5.0.0
npm ERR! npm -v 1.3.6
npm ERR! file /var/www/html3/laravel/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/opn/node_modules/object-assign/package.json
npm ERR! code EJSONPARSE

**Comment by JeffreyWay** [comment]
Looks like an issue with installing Browsersync? Can't reproduce. Try deleting your node_modules directory entirely, and re-installing from scratch.
