### ISSUE TITLE
4.0 - Release details

### ISSUE THREAD

**Issue by lucasmichot** [laravel/elixir#364]
It might be worth mentioning in https://github.com/laravel/elixir/releases/tag/4.0 release details that `vue` is already required by `laravel-elixir-vueify`.
There is no need to require it at the root of the project, they might be version collisions and this could be misleading.

    npm uninstall vue && npm install laravel-elixir-vueify

Also giving details that `npm@^3.0.0` is required for `laravel-elixir@^4.0.0` would be good

**Comment by JeffreyWay** [comment]
NPM 3 isn't required for Elixir 4.
