### ISSUE TITLE
No such file or directory as `.../rev-manifest.json`.

### ISSUE THREAD

**Issue by Arcrammer** [laravel/elixir#367]
Does anyone know why this even happens? There should definitely be a more friendly debug message than that. I'm currently completely lost but I'll update if I find the culprit.

UPDATE: Everything is fine now but I still have no idea what caused it. I think I had a misconfigured path in the `config` or something.

ANOTHER UPDATE: I said it was fixed but it's back. 😞

LAST UPDATE: After reverting all of my changes (Gulp-related changes) I was still facing the same problem. However, after adding `.version()` it was working again. Is `.version()` required in Elixir or something?

**Comment by oberoivarun** [comment]
`.version()` is not required. But i've noticed sometimes elixir can skip over a task and jump to the next one. It happens more when i run `gulp watch`. In those cases i try running `gulp` alone and then again `gulp watch` which helps.

**Comment by Arcrammer** [comment]
I've done the same thing, but the error happened when I hadn't even begun to actually make any styles. I was just running `gulp` alone!

**Comment by JeffreyWay** [comment]
Closing, since you got it fixed. And, no, `.version()` is not required.
