### ISSUE TITLE
Feature Request: Include image-min option by default

### ISSUE THREAD

**Issue by shaneparsons** [laravel/elixir#369]
It'd be nice (and not hard) if you guys could include an image-min option by default.

Sure there are a couple plugins out there, but they either don't work, or just don't work the same as the rest of the functions in the gulpfile.. And since minifying images is a pretty common thing, it'd be nice to keep everything nice, clean and straightforward.

**Comment by ricardogobbosouza** [comment]
I did the PR #327 was not accepted.

To minify images use 
```
npm install --save-dev laravel-elixir-imagemin
```
See https://github.com/nathanmac/laravel-elixir-imagemin

**Comment by shaneparsons** [comment]
Yeah laravelielixir-imagemin used to work for me until just recently.. not sure what happened but its useless now.
