### ISSUE TITLE
Document Autoprefixer on Elixir page

### ISSUE THREAD

**Issue by igorsantos07** [laravel/elixir#372]
I had to Google around to find [this commit](https://github.com/laravel/elixir/commit/9dd7da00ab988e116cd08fd9fea4b8e4ffd9fb19), then discover the [Config.js](https://github.com/laravel/elixir/blob/master/Config.js) file to be able to correctly configure Autoprefixer on Elixir. There's not even a mention that Elixir automatically runs autoprefixer. Shouldn't those be mentioned in the docs as well?

**Comment by igorsantos07** [comment]
Actually, I found no way to configure autoprefixer. Even by using the apparently current syntax, it made no difference. Autoprefixer is still changing my CSS with `elixir.config.autoprefix = { enabled: false }`

**Comment by JeffreyWay** [comment]
Agree. A PR to https://github.com/laravel/docs would be appreciated.
