### ISSUE TITLE
Add an easier method to add in custom browserify babelify plugins

### ISSUE THREAD

**Issue by TomCaserta** [laravel/elixir#376]
Since elixir updated to use the newer version of babel that uses plugins a lot of the syntax I used in my files became broken including things like object rest spread. The issue being was it was pulled out into its own plugin and not included under the es2015 preset as its es7.

In order to adjust this setting I saw no other option but to do the following in my gulpfile:

```javascript
var babelify = null;
elixir.config.js.browserify.transformers.forEach(function (transformer) {
  if (transformer.name == "babelify") {
    babelify = transformer;
  }
});
if (babelify !== null) {
  if (!babelify.options.hasOwnProperty("plugins")) {
    babelify.options.plugins = [];
  }
  babelify.options.plugins.push("syntax-object-rest-spread");
  babelify.options.plugins.push("transform-object-rest-spread");
}
else {
  console.error("Could not find the babelify browserify transformer");
  return;
}
```

This is quite a big load of extra code to use just to simply modify the babelify transform to add a few plugins. Is it possible to either add an extra parameter to the browserify command or to use the babel js config via: elixir.config.js.babel

**Comment by parsnick** [comment]
There's only a lot of code because it's so defensive, which is arguably overkill for a build tool. Wouldn't this achieve the same...?

```js
elixir.config.js.browserify.transformers
    .find(transformer => transformer.name === 'babelify')
    .options.plugins = [
        'syntax-object-rest-spread',
        'transform-object-rest-spread'
    ];
```

**Comment by TomCaserta** [comment]
I suppose but I figured that was an internal configuration list so I did not want to have to modify my buildscript again when elixir updates. Also I did not realise ES6 find worked under gulp/node.

**Comment by timothyallan** [comment]
Lifesaver @parsnick with that snippet, thanks :+1:
