### ISSUE TITLE
Sass watcher is watching only single file and not resources/sass/**/*.scss

### ISSUE THREAD

**Issue by OskHa** [laravel/elixir#378]
under `node_modules/laravel-elixir/tasks/sass.js`

`.watch(paths.src.path)` --> should read the wildcard config

**Comment by Prashank25** [comment]
there is a pull request for this already #377 

also this "hacky" way seemed to work as well.
```
mix.sass('*.scss', './public/css/all.css');
```

**Comment by mrcsmcln** [comment]
Here's a more recursive solution:
```
mix.sass('*/**.scss', './public/css/all.css');
```

**Comment by franzose** [comment]
The same applies to compiling LESS...

**Comment by szekeresa** [comment]
Same effect...

submitted to revert.. #384

**Comment by futhr** [comment]
+1 `v4.0.4` and up seems fluked due to this, reverted to `v4.0.3` to get this working again.
