### ISSUE TITLE
Why are tasks being sorted when running `gulp watch`?

### ISSUE THREAD

**Issue by x-yuri** [laravel/elixir#382]
As a result there's no easy way to use `coffeescript` + `browserify`. Moreover, it might take a while to notice.

**UPD** On closer investigation, it depends on what you watch. E.g. if we are turning `1.coffee` into `1.js` and then into `bundle.js` and for both tasks we watch `1.coffee`, the sorting will be in the way. But if `coffee`'s watcher is `1.coffee` and `browserify`'s one is `1.js`, then everything more or less works. Except for the first run when `1.js` doesn't exist. You need to restart `gulp watch` for it to notice it.

Concerning the last issue, it's `gaze` who [fails to properly notify][3] of fs events. The alternatives that were suggested in different issues are [`chokidar`][2] and [`watchr`][1]. And [`gulp-watch`][5] is using the former, so you might consider switching to it [here][4].

But well, that's not what's this issue about. Could we run tasks in the order they are defined? Or run them in the same order as when running just `gulp`? (`default` task)

[1]: https://www.npmjs.com/package/watchr
[2]: https://www.npmjs.com/package/chokidar
[3]: https://github.com/shama/gaze/issues/177
[4]: https://github.com/laravel/elixir/blob/4.0/tasks/watch.js#L40
[5]: https://www.npmjs.com/package/gulp-watch

**Comment by JeffreyWay** [comment]
Fixed.
