### ISSUE TITLE
Add support for task dependencies

### ISSUE THREAD

**Issue by tomzx** [laravel/elixir#383]
It appears that elixir is unable to deal with gulp dependencies. If I have the following gulp.js file

```
elixir(function(mix) {
	mix
		.scripts([
			'a.js'
		], 'public/js/a.js')
		.scripts([
			'b.js'
		], 'public/js/b.js');
});

gulp.task('ci', ['scripts']);
```

and I call `gulp ci`, only the first *scripts* will be executed, thus only generating the `public/js/a.js` file.

After a bit of inspection and debugging, it seems that the `createGulpTasks` function (in index.js) could be reduced to the following and still work

````
var createGulpTasks = function() {
    var tasks = this.tasks;

    tasks.forEach(function(task) {
        gulp.task(task.name, function() {
            return _.where(tasks, { name: task.name })
                .forEach(function(task) {
                    task.run();
                });
        });
    });
};
```

I'm sure the previous code has a reason to exist, thus I'd be interested to know its purpose.

Thanks!

**Comment by JeffreyWay** [comment]
There are comments in the `createGulpTasks` area to clarify why the extra conditions are needed.

Your `gulp.task` dependency example is expected behavior.
