### ISSUE TITLE
Combine Javascript and compiled Coffeescript

### ISSUE THREAD

**Issue by jrhenderson1988** [laravel/elixir#385]
Hi,

Is there a way, using Elixir , to compile a Coffeescript file and combine the output of this with other Javascript files?

I have the following paths in my project:

    resources/assets/coffee/main.coffee
    resources/assets/js/jquery.js
    resources/assets/js/jquery/form.js

I would like to compile `main.coffee` and then combine the resulting file with the `jquery.js` and `jquery.form.js` files and place the output into `public/js/main.js`.

I can achieve this in a bit of a messy way by using `mix.coffee(...)` to compile `main.coffee` (Outputting it into the `resources/assets/js` directory) and then using `mix.scripts(...)` to combine the resulting `main.js` file with the other two.

    elixir(function(mix) {
        mix.coffee(['main.coffee'], 'resources/assets/js/main.js');
        mix.scripts(['jquery.js', 'jquery.form.js', 'main.js'], 'public/js/main.js');
    });

This isn't really ideal since it means creating an intermediate file and since Gulp/Elixir are running asynchronously, it's not guaranteed that the Coffeescript is compiled before combining the scripts, which leads to errors or having to run gulp more than once.

Is there perhaps a way of doing this that I'm missing? If not, perhaps this could be a welcome addition :)

Thanks in advance!

**Comment by JeffreyWay** [comment]
Elixir runs synchronously. So you would compile your CoffeeScript file, and then call either `mix.scripts()` or `mix.combine(['file/paths'])` to concatenate them. Use the latter, if you don't need additional compilation or minification. It's faster.
