### ISSUE TITLE
mix.version breaks image links on Windows

### ISSUE THREAD

**Issue by Inch4Tk** [laravel/elixir#388]
I am using a few relative links to images (e.g. images/loading.gif) in a Vue template file, which gets compiled with mix.browserify before mix.version is called. Because the template gets inserted at runtime, I can not use blades elixir function to replace the path manually. 
However, version is smart enough to recognize these relative paths in the Vue template and replace them with the versioned path. Sadly, on windows, the path contains '\', resulting in the following created link: \build/images/loading-6c1f970cbe.gif. The browser interprets this as: %08uild/images/loading-6c1f970cbe.gif which is an illegal path.
Replacing the following line in the version task:
```javascript
var filePathPrefix = paths.output.baseDir.replace(publicPath, '') + '/';
```
with this line:
```javascript
var filePathPrefix = paths.output.baseDir.replace(publicPath, '').replace('\\','/') + '/';
```
produces correct paths.
I don't think this should have any negative impact on the behavior of the version task.

**Comment by JeffreyWay** [comment]
Sorry for delay. But a PR would be great, if that fixes it for you.

**Comment by head82** [comment]
I think this is a bug. Why was this issue closed?
