### ISSUE TITLE
Feature request: be more verbose

### ISSUE THREAD

**Issue by martinlindhe** [laravel/elixir#389]
Trying to debug some browserify related issue, and it would be nice to have a little more details to go on.

There is this gulp plugin gulp-filelogger [1], which is a gulp pipe that will output file names as they fly by in the gulp pipe, but i cant seem to figure out how to make that work with elixir as-is. 

1: https://www.npmjs.com/package/gulp-filelogger

**Comment by JeffreyWay** [comment]
Elixir already has a bunch of dependencies, so I'd prefer to not add another. Thanks, though!
