### ISSUE TITLE
Issue with elixir in laravel 5.2

### ISSUE THREAD

**Issue by neowill2013** [laravel/elixir#391]
Just installed fresh copy of laravel 5.2 and after npm install
ran make:auth
added some css
ran gulp and following error occured

ErrorException in helpers.php line 294:
file_get_contents(C:\xampp\htdocs\laravel\public\build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\xampp\htdocs\laravel\resources\views\layouts\app.blade.php) (View: C:\xampp\htdocs\resources\views\layouts\app.blade.php)

Then I installed fresh copy of laravel 5.1 and its working fine there.

**Comment by SpadXIII** [comment]
I just ran into the same issue and found 2 simple solutions:

1. In your gulpfile.js add this line: `mix.version(['public/css/app.css']);` if you want to version your css file
2. change `<link href="{{ elixir('css/app.css') }}" rel="stylesheet">` to `<link href="{{ asset('css/app.css') }}" rel="stylesheet">` if you don't want  to version your css file.

**Comment by pYr0x** [comment]
@SpadXIII thanks that was the solution!
