### ISSUE TITLE
Using mix.phpUnit(), got twice notification and found the problem.

### ISSUE THREAD

**Issue by Mombuyish** [laravel/elixir#401]
When I use laravel 5.2, elixir version is 4.0.0
and I used `mix.phpUnit()` I got twice notification, elixir on first (take a image green always) and gulp-phpunit do second notification.

I found laravel-elixir package `Test.js` .on('error', function(e)) ... didn't work correctly, tracing to next I found the problem finally, `gulp-phpunit` was updating. it was a big update and architecture was different, it seems have notification by itself.

I try to use elixir 3.0.0 now, on gulp-phpunit 0.9.*, that's work correctly.

**Comment by Mombuyish** [comment]
when I use 4.0.0 it got errors message:
```
[12:32:40] { [Error: Command failed: /bin/sh -c ./vendor/bin/phpunit --colors --debug -c phpunit.xml
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c ./vendor/bin/phpunit --colors --debug -c phpunit.xml' }
```

**Comment by bonsi** [comment]
I'm having comparable problem: before any phpunit tests are executed, I get a "green" notification. No notification though after phpunit finishes the tests, even when tests are failing. Uninstalling both laravel-elixir 0.4.2 and gulp-phpunit 0.11.* en then reinstalling laravel-elixir@4.1.0 (which requires gulp-phpunit 0.9) fixes these issues for me.

**Comment by mikeerickson** [comment]
You can use 0.11.x and disable gulp-phpunit internal notification flag in options param

{notify: false}

This is outlined in documentation

**Comment by mikeerickson** [comment]
@Mombuyish As I mentioned above (sorry for short response).   This dual notification has related to the fact that gulp-phpunit now emits it own notification (along with additional information displayed to user) 

To work with elixir, you just need to configure the options parameter (second parameter to mix.phpUnit call) as follows

````
elixir(function(mix) {
    mix.phpUnit('',{notify: false});
    //mix.sass('app.scss');
});
````

No need to downgrade to an other version (as you mentioned above).   FWIW, it is encouraged that you use gulp-phpunit 0.11. x or greater (this is reasons elixir uses this as minimum version.   

Changes were made to support other issues and better compatability with Laravel 5.2, Symfony 2.8/3.0 and PHP 5.6 and greater (including PHP 7)

Please let me know if you have any other issues.  Again, I would encourage using 0.11 and apply the simple adjust outlined above.

**Comment by JeffreyWay** [comment]
Closing, as we're now piping out to a shell script.
