### ISSUE TITLE
Not able to install on Win XP due to node-sass 3.4.2 error

### ISSUE THREAD

**Issue by Mohit127** [laravel/elixir#403]
Not able to finish the installation of Elixir as node-sass 3.4.2 error https://github.com/sass/node-sass/issues/1283 stops install process. node-sass 3.4.1 works fine so is there any way to force laravel-elixir to use node-sass 3.4.1.

**Comment by JeffreyWay** [comment]
I don't think so.

Closing, as this doesn't seem to be an issue with the Elixir codebase, itself.
