### ISSUE TITLE
Simplifying gulp watch

### ISSUE THREAD

**Issue by joshmedeski** [laravel/elixir#405]
So I'm working on a rather complicated project with multiple tasks. I don't want to re-run every task in Gulp every time I change a file, just the tasks that are effected by the file that has been changed.

Is this possible with Elixir?

**Comment by JeffreyWay** [comment]
That should already be the case. If you change a Sass file, for example, it's not re-running your entire build process.

**Comment by joshmedeski** [comment]
Thanks Jeffery, I'm going to revisit the method and figure out what's happening. I've been experimenting with the [Laravel Elixir Group](https://www.npmjs.com/package/laravel-elixir-group) plugin and it might be part of the problem.
