### ISSUE TITLE
Feature request: replace babel with typescript

### ISSUE THREAD

**Issue by jclyons52** [laravel/elixir#406]
Having babel run by default on the browserify task is immensely helpful, but would it be possible to replace it with [tsify](https://www.npmjs.com/package/tsify)? Since typescript can handle es6 to es5 compilation there would be no loss of functionality, and it would add the benefits of inline documentation for third party libraries, interfaces and static typing.

**Comment by jclyons52** [comment]
scratch that, it's already pretty easy to do. for anyone looking to use typescript just install tsify and add it as a plugin:

var elixir = require('laravel-elixir');

elixir.config.js.browserify.plugins = [ { name: 'tsify' } ]

elixir(function(mix){
	mix.browserify('main.ts');
});

**Comment by imanghafoori1** [comment]
Helpful Thanks. @jclyons52
