### ISSUE TITLE
Jade support?

### ISSUE THREAD

**Issue by eschmid72** [laravel/elixir#408]
Is `jade` support ever planned? It's much easier to code views with jade language,
and it can be compiled to .php or .blade.php.
**Note**: `jade` is going to be renamed into `pug` = jade 2.0

**Comment by mikeerickson** [comment]
Seeing as most laravel users will be using blade, this seems like quite an edge case.  How about you just create an elixir plugin instead of requiring it to be part of core and included for everybody?

**Comment by JeffreyWay** [comment]
Yep, this is territory for an Elixir extension.
