### ISSUE TITLE
Uglifyjs configuration not in Config.js

### ISSUE THREAD

**Issue by SeBuDesign** [laravel/elixir#409]
Hi all,

I wanted to shut off the mangle of Uglifyjs by setting the configuration option `mangle: false`. Next I noticed that the Uglifyjs configuration is not yet in the Config.js and therefore I can't set the Uglifyjs configuration in the config section in my gulpfile.js.

Is there a specific reason that the Uglifyjs config is not in the Config.js?

Thanks!

**Comment by ChrisWillerton** [comment]
Hi,

I'm having the same issue. It would be awesome if control over Uglify could be added to the config!

Thanks

**Comment by SeBuDesign** [comment]
@ChrisWillerton I created a pull request for this issue :+1:

**Comment by ChrisWillerton** [comment]
Looks good to me @SeBuDesign :)

**Comment by JeffreyWay** [comment]
Merged.
