### ISSUE TITLE
z-index changes

### ISSUE THREAD

**Issue by haheute** [laravel/elixir#412]
I use the 'default' laravel-elixir and gulp setup to compress and version scss to css. For some reason my `z-index:9999;` changes to `z-index:4;`, when I do a `gulp --production` (only with production flag).

Is this an elixir issue or gulp issue? I need the 9999 for an overlay that shall cover some leaflet buttons.

**Comment by CreepGin** [comment]
I can confirm this problem with the new version of Elixir. All my z-index'es turn into 1's when using the --production flag. 

I manually tested stylus and gulp-stylus (with compress: true), they are both converting z-index correctly. I'll do more digging, but right now it looks like some issue with Laravel Elixir.

**Comment by CreepGin** [comment]
Found the culprit. Starting with 4.2, Elixir is using cssnano for compression. Cssnano does zindex rebasing by default. To disable it in the context of Laravel, you need to change the elixir config like so:

```
elixir.config.css.cssnano.pluginOptions.zindex = false;
```

**Comment by hosmelq** [comment]
You can also add it to your elixir.json file
```
{
  "css": {
    "cssnano": {
      "pluginOptions": {
        "zindex": false
      }
    }
  }
}
```

**Comment by haheute** [comment]
Thank you very much for explaining, it works here.

**Comment by frodeknutsen** [comment]
This is the most retarded "feature" I've ever encountered. Can we please set z-index to false by default so people don't have to waste hours investigating this issue?
