### ISSUE TITLE
Elixir PHPUnit notifies green before running tests

### ISSUE THREAD

**Issue by jonlambert** [laravel/elixir#418]
Hey,

Firstly, thanks Jeffrey for a great bit of software!

I have a false-hope bug... When my tests fail, Gulp notifies me that all tests have passed before running the tests, then upon completion fires another notification that the tests have failed. You can reproduce with a fresh installation of L5.2, adding the below to `gulpfile.js`.

Edit: Not sure if `laravel/elixir` is the right place to report this! 

```
elixir(function(mix) {
    mix.phpUnit();
});
```

Gulp version:
```
[21:53:29] CLI version 3.9.0
[21:53:29] Local version 3.9.0
```

Gulp output:
```
[22:02:02] Starting 'phpUnit'...

Fetching PhpUnit Source Files...
   - tests/**/*Test.php

[22:02:02] Finished 'phpUnit' after 4.77 ms


       *** [Version] 0.11.3 Debug Cmd: ./vendor/bin/phpunit --colors=always --debug -c phpunit.xml ***

[22:02:03] gulp-notify: [Green!] Your phpUnit tests passed!
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.


Starting test 'ExampleTest::testBasicExample'.
.

 ...etc...


█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
{ [Error: Command failed: /bin/sh -c ./vendor/bin/phpunit --colors=always --debug -c phpunit.xml
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c ./vendor/bin/phpunit --colors=always --debug -c phpunit.xml' }
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
[22:02:28] Starting 'phpUnit'...

Fetching PhpUnit Source Files...
   - tests/**/*Test.php

[22:02:28] Finished 'phpUnit' after 7.93 ms

```

**Comment by mikeerickson** [comment]
@jonlambert Add this to your gulpfile where you are calling phpunit

  phpunit('',{debug: true, notify: false}) <-- note you can also disable the debug mode here by setting to false

With PHPUnit v0.11 it has built-in notification (for use outside of elixir) this will disable internal notifications.

Let me know if you have any further issues (author of gulp-phpunit plugin module used by elixir)

**Comment by 2601-Srl** [comment]
I have the same problem on a fresh installation of L 5.2 like @jonlambert 

Always two notification: 
* one always saying that test is passed
* another one saying that the test is passed/not passed

After adding what @mikeerickson suggest, the second notification doesn't show, but the first still stays on.

First notification always green
<img width="334" alt="FIRST NOTIFICATION" src="https://cloud.githubusercontent.com/assets/16098557/12578928/2c2cbfc2-c424-11e5-8a3a-9ce55298ecc3.png">

Second notification
<img width="333" alt="SECOND NOTIFICATION" src="https://cloud.githubusercontent.com/assets/16098557/12578935/3b4458bc-c424-11e5-98dc-1832e10aadbd.png">

**Comment by JeffreyWay** [comment]
I'm just going to remove the gulp-phpunit, and pipe to a shell command instead.
