### ISSUE TITLE
sass overwrite z-index values  while in --production

### ISSUE THREAD

**Issue by OskHa** [laravel/elixir#420]
Hi, i hope this is the right place to submit an issue.

after running `gulp --production` sass ignores my `z-index` and sets whatever it wants leads to some UX problems.

Bug found while using following stack:
- elixir
- angular
- angular material ...

PS: already posted same issue for gulp-sass as its damn hard to localize the problem. https://github.com/dlmanning/gulp-sass/issues/432

**Comment by nhowell** [comment]
Ran into this issue today. I assume it's trying to be clever and use the lowest possible z-index value possible for smaller file sizes. However, I'm using some plain CSS files as well which it can't take into consideration.

**Comment by OskHa** [comment]
i was thinking its somewhere in the sass options. unfortunately nothing... im kinda lost...

**Comment by parsnick** [comment]
It's apparently an option of the `cssnano` plugin - see #412.

I agree this is confusing and probably shouldn't happen by default.

**Comment by nhowell** [comment]
@parsnick Thank you! I hadn't discovered that cssnano was the culprit!

**Comment by OskHa** [comment]
Awesome! This should be added to the elixir documentation. All setting types with the elixir.json, config and pipe.

**Comment by JeffreyWay** [comment]
Fixed.
