### ISSUE TITLE
styles task doesn't support autoprefixer

### ISSUE THREAD

**Issue by whipsterCZ** [laravel/elixir#423]
I have found css `autoprefixer` support in

```
Elixir.config.styles.autoprefix: {
            enabled: true,

            // https://www.npmjs.com/package/gulp-autoprefixer#api
            options:  {
                browsers: ['last 2 versions'],
                cascade: false
            }
        },
```

but it doesn`t do anything - is it implemented?

**Comment by JeffreyWay** [comment]
Autoprefixing will be used, if you're using a compiler like Sass or Less. So `mix.sass()` will autoprefix for you.

**Comment by brachycera** [comment]
No Autoprefixing for plain CSS :disappointed:

**Comment by Decadence** [comment]
@JeffreyWay why is `styles` can't have support for autoprefix?

**Comment by Decadence** [comment]
Actually I can't make it work even for `sass`.
