### ISSUE TITLE
`del` task break watch - cleanse task missing

### ISSUE THREAD

**Issue by whipsterCZ** [laravel/elixir#424]
My custom cleanse task **break watch process**.

```
var del = require('del');
elixir.extend("clean", function(path) {
    new elixir.Task('clean', function() {
        del(path);
    })
});
```

**clean** is the last task

```
     ...
    mix.less('application.less','resources/compiled/less/app.css');

    //  simplified -  there are autoprefixer, postcss, urlAdjuster etc... i have tried to get rid of them and they do not cause the problem...

    mix.copy('resources/compiled/postcss/app.css','public/compiled');

    mix.version([  "public/compiled/app.css", ...  ]);

    //This breake watch
    mix.clean([  'public/compiled',  'resources/compiled'   ]);
```

**in watch process**: changing `application.less` will trigger just `mix.less()` but nothing more (it should trigger copy,version and my clean)

Im I doing something wrong, or deleting files and folders mess gulp watch?
Maybe there is problem in order of watching tasks. ( can cleanse outrun copy ?  )

**Comment by JeffreyWay** [comment]
It's because your `del(path)` section isn't returning anything. You need to return the Gulp stream.
