### ISSUE TITLE
[Question] Compile multiple files

### ISSUE THREAD

**Issue by gperdomor** [laravel/elixir#426]
Hi... I have a question...

I have a directory with some files:
<pre><code>assets
    sass
        _mixins.scss
        components.scss
        components-rounded.scss
</code></pre>

With gulp, i can generate <code>components.css</code> and <code>components-rounded.css</code> with:
 <code>gulp.src('./assets/sass/*.scss').pipe(sass()).pipe(gulp.dest('./assets/compiled/css'));</code>

It's possible do the same using elixir without calling <code>mix.sass</code> twice? (one for <code>components</code> and other for <code>components-rounded</code>)

**Comment by JeffreyWay** [comment]
No. You'll need to call the method twice. If you call it once with an array, Elixir will merge the files into one.
