### ISSUE TITLE
Method styles with --production option

### ISSUE THREAD

**Issue by baribadamshin** [laravel/elixir#428]
Hey, there!

When I try combine a few css files in production mode, I'll have empty result file. File is created, but without any data, it's just empty file.
My task is

`
mix.styles([
  'fonts/proxima-nova/regular.css',
  'fonts/proxima-nova/medium.css',

  'fonts/proxima-nova/bold.css'
]);
`

Source from package.json

`
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "^4.0.0"
  }
}
`

**Comment by baribadamshin** [comment]
I think is gulp-cssnano bug

**Comment by OskHa** [comment]
try to define the output file.

```
elixir(function(mix) {
    mix.styles([
        'normalize.css',
        'main.css'
    ], 'public/assets/css');
});
```

**Comment by baribadamshin** [comment]
@OskHa yes, I've already do that, but it's not work. how I said, its cssnano problem

**Comment by OskHa** [comment]
i would check the syntax and cssnano config options. i hvae had also a lot of issue with that library (z-index)

check http://cssnano.co/options

**Comment by OskHa** [comment]
you can set the options either as elixir config within gulpfile.js or inside elixir.json

```
{
  "css": {
    "cssnano": {
      "pluginOptions": {
        "zindex": false
      }
    }
  }
}
```

**Comment by baribadamshin** [comment]
@OskHa Thank you! It works, I've just turn off minifyFontValues option
