### ISSUE TITLE
Calling mix.version many times.

### ISSUE THREAD

**Issue by giolvani** [laravel/elixir#430]
Hello guys!

I am working with modules, and each module have a directory that have a block of gulpfile and each block have a call for 'mix.version'. It works very well, but the manifest file, keeps just references of the last execution.

It breaks my code when I call my script with 
```javascript
<script src="{{elixir('path/to-my/script')}}"></script>
```
Still, if I do not use elixir help, it works very well.

There's is other way to work with gulp and modules, or I am on the way?

**Comment by JeffreyWay** [comment]
I believe, right now, you need to make sure that you only call `mix.version()` once per execution.

**Comment by giolvani** [comment]
Thanks @JeffreyWay, but I really need solve this issue.

May I use another gulp package to mix scripts?
