### ISSUE TITLE
MJML support for Elixir

### ISSUE THREAD

**Issue by CaporalDead** [laravel/elixir#435]
Hi,

it would be nice to have a native integration of MJML in Elixir based on this gulp task : https://www.npmjs.com/package/gulp-mjml .

MJML is a framework to write responsive emails template ( https://mjml.io/ ).

**Comment by huglester** [comment]
wow. this is nice! thanks, never seen this before.

**Comment by JeffreyWay** [comment]
This is a great candidate for a custom Elixir extension. Probably not a candidate for core, though.

**Comment by voydz** [comment]
@CaporalDead  I know this is a bit outdated, but I open sourced a very trivial version of a laravel-elixir-mjml extension over here https://www.npmjs.com/package/laravel-elixir-mjml

**Comment by CaporalDead** [comment]
Thanks @Voydz, I didn't have the time to look at it. I'll check what you've
done asap :).

2016-02-26 8:50 GMT+01:00 Voydz <notifications@github.com>:

> @CaporalDead <https://github.com/CaporalDead> I know this is a bit
> outdated, but I open sourced a very trivial version of a
> laravel-elixir-mjml extension over here
> https://www.npmjs.com/package/laravel-elixir-mjml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/elixir/issues/435#issuecomment-189151632>.
>



-- 
Thomas SIEFFERT
Ingénieur Informatique

« Le peuple n'a jamais eu autant de pouvoir que sur Internet. »
Valentin Lacambre

« Un grand pouvoir implique de grandes responsabilités. »
Benjamin Parker, Spider Man
________________________________

Adoptez l'éco-attitude.
N'imprimez ce mail que si c'est vraiment nécessaire
