### ISSUE TITLE
Uglify options in browserify task

### ISSUE THREAD

**Issue by kuiqiang** [laravel/elixir#437]
It would be great if uglify options are included for the [browserify task](https://github.com/laravel/elixir/blob/master/tasks/browserify.js#L46) (as with the [script task](https://github.com/laravel/elixir/blob/master/tasks/scripts.js#L69)).

That makes more sense because uglify options are needed in the browserify context as well.

**Comment by laracasts** [comment]
Okay. PRs welcomed by anyone!
