### ISSUE TITLE
Copy fails when dot . in directory name

### ISSUE THREAD

**Issue by project707** [laravel/elixir#438]
This doesn't copy the contents of the zone.js directory (5.0.0):
`mix.copy('node_modules/zone.js', 'public/zone.js');`

All other directories and contents copy fine with the above syntax, and if I use gulp to do it it works fine:
```
gulp.task('default', function() {
   gulp.src('node_modules/zone.js/**')
   .pipe(gulp.dest('public/zone.js'));
});
```
I'm actually fairly new to Gulp specifically, so unfortunately I'm not sure why despite having taken a look at tasks/copy.js

**Comment by JeffreyWay** [comment]
Should be fixed in a recent commit.
