### ISSUE TITLE
Integrate TypeScript

### ISSUE THREAD

**Issue by okaufmann** [laravel/elixir#444]
Hi,

I'm using elixir in all my (not only) laravel projects (yes it works well for me). Cause I'm a big fan of TypeScript i decided to create a Plugin for elixir to be able to integrate typescript in the workflow.

https://github.com/okaufmann/laravel-elixir-typescript

Maybe this could be integrated direct in elixir "core" as plugin? I rewrote the plugin based on the coffee-script task so it follows the pattern as far as possible.

Thanks for Feedback.

**Comment by jfoliveira** [comment]
+1 for having TypeScript as a first class Elixir task.
Perhaps you'd better off sending a PR with your existing 
```
index.js
```
at https://github.com/okaufmann/laravel-elixir-typescript/blob/master/index.js

added as 

````
elixir/tasks/typescript.js
```

**Comment by JeffreyWay** [comment]
No plans to add TypeScript to core. It's best as an extension for now. :)

**Comment by neovive** [comment]
I usually don't follow language trends, but with Angular 2 due for release in the coming months, Typescript will likely see a large boost in usage (surpassing CoffeeScript). Typescript support in the Elixir core would be a very nice addition for many users. Something to consider for a future Laravel release.

@okaufmann Thanks for your work. Your extension works great!

**Comment by JeffreyWay** [comment]
If Typescript gets very popular, we'll add it.

In the meantime, I'm removing CoffeeScript as a default in the next release.

**Comment by neovive** [comment]
Makes sense. I'm sure you heard it many times, but Elixir is awesome! Thank you for all of your efforts.
