### ISSUE TITLE
Browserify does not concatenate scripts in order.

### ISSUE THREAD

**Issue by prog-rajkamal** [laravel/elixir#450]
when i use 
 `mix.browserify([ 'jquery.js', 'bootstrap.js', 'main.js' ] ,'app.js'); `
files are sorted by name and then mapped to app.js.
Now `bootstrap.js` is dependent on `jquery.js` and so an error is thrown and code does not work.
changing their names is not an option.
Right now I am using `mix.scripts()` -- which does not sort before concatenation-- for libraies and `mix.browserify` for main.js

**Comment by JeffreyWay** [comment]
If you only want to concatenate those files, use `mix.combine()`.

**Comment by prog-rajkamal** [comment]
@JeffreyWay, thanks for the suggestion.
can yout tell me where I can find docs for `mix.combine()` ? I am using laravel 5.1
