### ISSUE TITLE
Ignore tasks in gulp watch

### ISSUE THREAD

**Issue by aarinsmith** [laravel/elixir#452]
I can't seem to see if there is an easy solution to this anywhere but a feature to specify tasks to ignore from the default `gulp` and `gulp watch` commands would be helpful. Currently have run into a situation where it is beneficial for me to run `gulp tdd` to run unit tests internally on the homestead server but have `gulp watch` watching from outside the server for changes in the asset pipeline. Currently I have set a NODE_ENV to `testing` within homestead and run a check to ignore the phpUnit task based on environment. However it would be ideal to define which tasks are run by default or to be able to flag tasks to ignore.

**Comment by JeffreyWay** [comment]
Hmm - `elixir.tasks` will contain all registered tasks from your Gulpfile. So you might be able to override that. I'm not sure. Never had a request to do that before.
