### ISSUE TITLE
Problem with Scripts SourceMaps

### ISSUE THREAD

**Issue by asolopovas** [laravel/elixir#457]
The source map generated by elixir when it combines JavaScript, has incorrect sourceRoot within sourcemap file that points to ["http://example.com/source/jsFileName1.js","http://example.com/source/jsFileName2.js", 'etc.' ]. I have been able to resolve this issue from within gulpfile.js when used raw sourcemap plugin by adding .pipe(sourcemaps.write({sourceRoot: "relativePathToJS"}). I am on Windows 10. 

It could be done from node_modules\laravel-elixir\tasks\scripts.js line 70 

        .pipe($.if(config.sourcemaps, $.sourcemaps.write({sourceRoot: "path"})))

Where path could be passed as parameter from within elixir. But due to my lack of knowledge in node module develpment I can't create pull request for that.

**Comment by JeffreyWay** [comment]
I don't think this should matter, because we're inlining the original source code directly into the sourcemap file.
