### ISSUE TITLE
Elixir not able to version multiple files?

### ISSUE THREAD

**Issue by arielstt** [laravel/elixir#461]
Hi,

Sorry to get back to an old bug, but I'm having exactly this issue: [https://github.com/laravel/framework/issues/7353](https://github.com/laravel/framework/issues/7353)

I'm currently using laravel-elixir 5.0.0 and gulp 3.9.1. If I just run **_gulp_**, it will miss a file in the manifest, but if I run **_gulp version_** it will generate versions for all files.

Any idea on how to solve this?

**Comment by JeffreyWay** [comment]
Fixed a couple days ago.

**Comment by jonnydowe** [comment]
Hi, I'm having the exact issue stated by the OP with Gulp 3.9.1 and elixir 6.0.0-10.

Here's my gulpfile:

`var elixir = require('laravel-elixir');
 
require('laravel-elixir-vue');

elixir(mix => {
     mix.styles([
     	'app.css',
     	'../../../vendor/bower_components/bootstrap/dist/css/bootstrap.min.css',
     	'../../../vendor/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css'
     	])
    	.scripts(['createbet.js'],'public/js/createbet.js')
    	.scripts([
    		'../../../vendor/bower_components/jquery/dist/jquery.min.js',
    		'../../../vendor/bower_components/bootstrap/dist/js/bootstrap.min.js',
    		'../../../vendor/bower_components/moment/min/moment.min.js',
    		'../../../vendor/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js',
    		'app.js'
    		])
        .version('css/all.css')
        .version('js/all.js')
        .version('js/createbet.js')
});
`
