### ISSUE TITLE
set interval for gulp watch (to decrease CPU usage during "gulp watch")

### ISSUE THREAD

**Issue by denis-chmel** [laravel/elixir#467]
Hi guys,

There's a known issue with gulp: https://github.com/gulpjs/gulp/issues/634
I'm facing it with laravel-elixir (v4.2.1, MacOs 10.11.4).

In brief: gulp.watch() by default polls files every 100ms. That is producing unreasonable and sometimes noticeable CPU load, especially if there are plenty of files to watch. And despite there is a workaround for gulp.watch() -- you may pass {interval: 1000} as one of its argument -- there's no way to make use of it when using laravel-elixir.

The modern mix.browserify() is not affected as at the end it utilizes "chokidar" module, that smartly handles FsEvents. Though mix.sass(), mix.livereload() and mix.scripts() are still using rude gulp.watch(), 

Here's the only gulp.watch() call in elixir:
https://github.com/laravel/elixir/blob/master/tasks/watch.js#L40-L42
It has 2 arguments, and if insert {interval: 1000} between them - CPU load falls, and battery isn't drained too fast.

A quick and simple solution could be to add a new config param (empty by default) like:
elixir.config.gulpWatch.options = {interval: 1000};

I'd implement such if there's no better idea.
What do you think?

**Comment by EHLOVader** [comment]
I think it might make sense to put a `watchOptions` config alongside the `batchOptions` in the config [here](https://github.com/laravel/elixir/blob/master/Config.js#L125-L129) and included prior to the command there. 

Then either providing a watch interface to easily add manual watches and ability to access the events like I have done [here](https://github.com/EHLOVader/laravel-elixir-livereload/blob/master/index.js#L20-L23)

The second half isn't as necessary as it would be possible to implement the watch using global configs if the first is done.

**Comment by JeffreyWay** [comment]
Is there any real value in making the interval configurable? Maybe we should just hardcode 1000 and be done with it. I hate having to make every possible option configurable.

@denis-chmel - Can you submit a PR that hardcodes `interval: 1000` for now? If people squawk, we can add a configuration option later.

**Comment by denis-chmel** [comment]
Thank you, Jeffrey!
