### ISSUE TITLE
 global helper function elixir failed

### ISSUE THREAD

**Issue by 74sharlock** [laravel/elixir#468]
According to the sample in the document:
https://laravel.com/docs/5.2/elixir#versioning-and-cache-busting

I use the elixir method to solve the file path problem:
```html
<link rel="stylesheet" href="{{elixir('css/app.css')}}">
```
But the program throws an exception:
```
FatalErrorException in 594e23f7ce213f7b01e83f27ce57d23d line 0:
Method Illuminate\View\View::__toString() must not throw an exception
```

my laravel version: 5.1
laravel-elixir: 5.0.0

Did I miss something?

**Comment by JeffreyWay** [comment]
Not sure, but this would be a `laravel/framework` issue, since the function lives in that repo.
