### ISSUE TITLE
Disable sourcemaps for one function only

### ISSUE THREAD

**Issue by shaneparsons** [laravel/elixir#472]
It'd be handy to be able to disable source maps for a single function rather than disabling them completely.

I've tried disabling them in the `mix.sass()` function by doing stuff like: `elixir.config.css.sass.pluginOptions.sourceMap = false;`, but it seems to get overwritten by `elixir.config.sourcemaps`.

**Comment by JeffreyWay** [comment]
Don't think that's possible at the moment, and seems like a use case that very few have.
