### ISSUE TITLE
mix.browserify with vueify transformer does not babelify .vue files

### ISSUE THREAD

**Issue by oleynikd** [laravel/elixir#473]
I use
```
elixir.config.js.browserify.transformers.push({
    name: 'vueify',
    options: {}
})
```

and

```
mix.browserify([...], 'public/js/app.js')
```

But in my `.vue` files if I use some of ES6 features they are left unbabelified

Please help! How do I fix this?

**Comment by laracasts** [comment]
Are you installing laravel-elixir-vueify through npm?

**Comment by oleynikd** [comment]
Yes, but I'm using `vueify`not ` laravel-elixir-vueify`
Doing wrong?

**Comment by oleynikd** [comment]
Switched to `laravel-elixir-vueify` - everything works now! Thank you!!! Are there some docs describing this?
