### ISSUE TITLE
npm install -D laravel-elixir does not pull in src/ directory

### ISSUE THREAD

**Issue by SethTompkins** [laravel/elixir#474]
About 5 minutes ago I ran `npm install -D laravel-elixir`, the module that was installed was completely missing the src/ and dist/ directories entirely.

![screen shot 2016-04-08 at 9 54 57 am](https://cloud.githubusercontent.com/assets/3925226/14385737/ffc6d4e2-fd6f-11e5-93c0-e134ad5550ca.png)

**Comment by laracasts** [comment]
Maybe delete your node_modules directory and give it another shot? I just created a fresh Laravel project and pulled in the latest version. The `dist/` directory is there.
