### ISSUE TITLE
Notifications config disabled but not suppressing errors

### ISSUE THREAD

**Issue by billcolumbia** [laravel/elixir#475]
So Elixir seems to be building stuff just fine but I get a big error message: `Unable to post a notification for the current user (USERNAME), as it has no running NotificationCenter instance.`

I have disabled the notification center on this machine via [a dotfile](https://github.com/mathiasbynens/dotfiles/blob/master/.osx#L117)

It doesn't break the build process but I assumed that adjusting the config would turn this feature off and suppress the errors. it does not. Is there a work around? I tried digging and saw you just recently added the option and some logic in `src/index.js`. I thought of hacking on the code to see if I could patch and do a PR but wanted to ask here prior - incase I overlooked something! Here's my config (it's a bit weird as I'm just testing some things before finalizing the JS folder structure:

```js
var elixir = require('laravel-elixir');

elixir.config.assetsPath = './';
elixir.config.publicPath = './app/webroot';
elixir.config.appPath = 'app';
elixir.config.viewPath = 'app/View';
elixir.config.js.folder = './';
elixir.config.js.outputFolder = 'vuestuff';
elixir.config.notifications = false; // This does not appear to suppress notification errors

elixir(function(mix) {
  mix.scripts([
    'main.js'
  ]);
});
```

**Comment by rigor789** [comment]
There's no such config option for `notifications` but since elixir is using `gulp-notify`, you can append
```node
process.env.DISABLE_NOTIFIER = true;
```
on top of your `gulpfile.js`.

That should disable the notifications!

**Comment by billcolumbia** [comment]
Ah nice thanks!
