### ISSUE TITLE
`gulp watch` eventually stops watching files

### ISSUE THREAD

**Issue by hackel** [laravel/elixir#476]
I suspect this issue is probably not caused by Elixir itself, but I'm going to start here.  I'm running Elixir 5.0 on Ubuntu 16.04, though this has been a regular condition through many previous versions, unfortunately.  I use Elixir's `mix.browserify()` method.  When I run `gulp watch`, everything works fine initially.  Then after some (seemingly random) amount of time, it just stops picking up file changes.  Sometimes it can go all day before it quits, others it it happens multiple times per hour.

Any suggestions would be appreciated!

**Comment by JeffreyWay** [comment]
I've noticed this too from time to time. But can't consistently reproduce it, so it's tough to figure out where the issue is... 

If anyone has more information, please chime in.

**Comment by jackmu95** [comment]
I have the same problem but it fails almost always now.

**This is the error message I'am getting:**
```bash
[12:00:00] Finished 'version' after 11 ms
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, chmod '/path/to/file.js'
    at Error (native)

```

**Comment by hackel** [comment]
@jackmu95 That looks like a different, unrelated error to me.  I've never received any actual error message, it just stops listening.  The actual error message is pretty clear.  Is stream.js one of your own files?  Doesn't look like it's a part of Elixir or its dependencies.

**Comment by JeramyNS** [comment]
I get this issue frequently. Exactly the same, works for a while and then it just randomly stops working.
(Tends to stop before I get to a dozen file updates)

Other files are still being watched, just the one being worked on stops being tracked and on two occasions I found that it randomly started tracking changes again.

I would be keen on figuring this out, however I'm not sure how to debug this type of node module. If someone has some tips I'd happily investigate.

**Comment by JeffreyWay** [comment]
We're using polling in the next upcoming release, and I think that will fix this.
