### ISSUE TITLE
cssnano autoprefixer conflicts with gulp-autoprefixer

### ISSUE THREAD

**Issue by huyby** [laravel/elixir#477]
The 'autoprefixer' option for cssnano should be set default to false in Config.js. Otherwise the CSS vendor prefixes set by the autoprefix (gulp-autoprefixer) are reset by the one set by cssnano, which will run when using the --production flag. Probably this won't be noticed until one change the autoprefix 'browsers' setting from the default `['last 2 versions']` to something else like `['last 2 versions', 'Explorer >= 9']`.

If someone needs to fix the issue right away, put this in your gulpfile.js:
`config.css.cssnano.pluginOptions.autoprefixer = false;`

This issue was introduced in 4.2 when minifier was swapped for cssnano.

**Comment by huyby** [comment]
The issue was already addressed and resolved by https://github.com/laravel/elixir/pull/443
But the fix is not in the latest 4.* and 5.* NPM package.

**Comment by vinkla** [comment]
This should be fixed in version 6.0 https://github.com/laravel/elixir/commit/b9091b4f110ab18e48dcc47e80b460ee75fe5703
