### ISSUE TITLE
Gulp watch does not perform mix.copy

### ISSUE THREAD

**Issue by carc1n0gen** [laravel/elixir#478]
I've noticed that watching for changes with `gulp watch` does not execute any `mix.copy` functions, but running `gulp` on its own does.

Is this intended functionality?

**Comment by JeffreyWay** [comment]
It watches the original file itself for changes. 

https://github.com/laravel/elixir/blob/master/src/tasks/copy.js#L30

**Comment by carc1n0gen** [comment]
I know this is closed now, but your comments didn't actually help me at all.

I went back to it and actually found out that `gulp watch` does not perform a `mix.copy` until you actually modify the files that is in the path to be copied.  I didn't realize this because the gulp watch performs an initial compilation of things like less/sass/browserify so I figured it also did an initial copy
