### ISSUE TITLE
Browserify source maps are still referencing a single file

### ISSUE THREAD

**Issue by carc1n0gen** [laravel/elixir#479]
For some reason the source maps generated when using the browserify wrapper for elixir only reference a single large concatenated file.

EDIT:

Here is a snippet of my sourcemap

```
{"version":3,"names":[],"mappings":"","sources":["admin.js"],...
```

There is only one referenced source file, and it's the output file.

**Comment by mrcsmcln** [comment]
+1. This is what Chrome gives me:

![image](https://cloud.githubusercontent.com/assets/4203694/14688022/50f941ae-070e-11e6-8fed-27305b65756a.png)

**Comment by enrichit** [comment]
+1 Same deal here.

I get the same message as @mrcsmcln at first I thought it was a problem with `mix.version` and the versioned source files confusing chrome but removing that didn't have any effect.

My gulpfile is very simple:

    elixir(function(mix) {
      mix.sass('app.scss');
      mix.sass('admin.scss');
    
      mix.browserify('admin.js');
      mix.browserify('app.js');
    
      mix.version([
        'public/css/app.css', 'public/css/admin.css',
        'public/js/app.js', 'public/js/admin.js'
      ]);
    });

SCSS source maps seem to work just fine.

In the mean time I'm going to fallback to gulp, I'll post back once I have a working solution and maybe I'll look into the actual problem if I can find the time.

**Comment by enrichit** [comment]
Here's what I've come up with about an hour of hacking. Unfortunately you don't get all of the Laravel niceness (like the pretty error reporting) and I couldn't get it to work with `mix.version` but given the choice I'd rather have the source maps.

It has source maps, watchify and outputs to 'public/js', just change the rename if you need it to point it somewhere else.

I'll see if I can find the time to look more into this bug but for now it's back to being productive. :bowtie: 

    var gulp = require('gulp');
    var rename = require('gulp-rename');
    var gutil = require('gulp-util');
    var source = require('vinyl-source-stream');
    var browserify = require('browserify');
    var watchify = require('watchify');
    var sourcemaps = require('gulp-sourcemaps');
    var eventstream = require('event-stream');
    
    gulp.task('browserify', function() {
      var files = [
        './resources/assets/js/admin.js',
        './resources/assets/js/app.js',
      ];
    
      var tasks = files.map(function(entry) {
        var outputName = entry.replace(/^.*[\\\/]/, '');
        return browserify({
          entries: [entry],
          debug: true,
          cache: {},
          packageCache: {},
          plugin: [watchify]
        })
          .transform('babelify', {presets: ['es2015']})
          .bundle()
          .on('error', function(e) {
            gutil.log(e);
          })
          .pipe(source(entry))
          .pipe(rename(outputName))
          .pipe(gulp.dest('./public/js'));
      });
    
      return eventstream.merge.apply(null, tasks);
    });

    /**
     * Modified from my previous post.
     */

    elixir(function(mix) {
      mix.sass('app.scss');
      mix.sass('admin.scss');
    
      mix.task('browserify', './resources/assets/**/*.js');
    
      // mix.version([
      //   'public/css/app.css', 'public/css/admin.css',
      //   'public/js/app.js', 'public/js/admin.js'
      // ]);
    });
