### ISSUE TITLE
Unexpected End of File with gulp --production

### ISSUE THREAD

**Issue by timothyallan** [laravel/elixir#484]
I'm using Gulp with Spark and running into some issues. I should note that I have other Laravel projects (without Spark) on this machine also using gulp --production that work just fine. 

I’ve just used the installer from a brand new version of Spark 1.03, using a fresh global install of the Laravel installer as well. 

Everything installs fine, tokens registered, no errors and it works great... until I do gulp --production. Gulp processes everything fine... however, once I run the app in my browser I see that I have a truncated app.js file with an "Uncaught SyntaxError: Unexpected end of input". It just ends...

Run normal gulp again, works great. Nothing has been changed at all from the downloads. I've asked @taylorotwell about it and he's unable to replicate, but mentioned I might want to raise the issue here.

Node, NPM, Composer, Laravel and Spark are all at their latest versions as of today. I've tried Elixer v4, 5, and 6.0.0-1

Any ideas??

![no production flag](https://cloud.githubusercontent.com/assets/1995135/14723654/65f9b1a8-07cf-11e6-8cfa-e573afce7a98.png)
![production flag](https://cloud.githubusercontent.com/assets/1995135/14723655/65f9ef2e-07cf-11e6-9adc-08a9a38868e4.png)

**Comment by JeffreyWay** [comment]
Hmm, not sure. I'll have to install Spark and see what might be the issue.

**Comment by timothyallan** [comment]
I wasn't able to track it down, but I switched to using webpack and everything is working now. Guys in the Spark slack channel weren't able to replicate as well with Gulp, so it might be a lost cause/config issue with my machine.
