### ISSUE TITLE
Notifications are not disabled

### ISSUE THREAD

**Issue by MunGell** [laravel/elixir#490]
Hi guys,

I cannot disable notifications in version 6.0.0-1 with both `elixir.json` and `elixir.config.notifications` configuration override approaches.

It looks like it sets `process.env.DISABLE_NOTIFIER` too late - notifier is already initialised and ignores any further changes of it.

Overriding this variable before elixir import solved the issue for now:

```
process.env.DISABLE_NOTIFIER = true;

var elixir = require('laravel-elixir');
```

**Comment by JeffreyWay** [comment]
Yeah - already fixed, but not tagged yet.

**Comment by MunGell** [comment]
Thanks! Sorry for the duplicate
