### ISSUE TITLE
Gulp fail: "map is not a function"

### ISSUE THREAD

**Issue by jbajou** [laravel/elixir#491]
Hello,

I'm trying to get Gulp running on a raspberry Pi 3 (under Rasbian) and I'm getting some trouble with the minify module.

Here is the error I have after running gulp:
```sh
TypeError: map is not a function
    at minify (/var/www/node_modules/laravel-elixir/dist/tasks/styles.js:62:12)
    at Task.gulpTask (/var/www/node_modules/laravel-elixir/dist/tasks/styles.js:55:161)
    at Task.definition (/var/www/node_modules/laravel-elixir/dist/tasks/styles.js:43:25)
    at Task.run (/var/www/node_modules/laravel-elixir/dist/Task.js:148:25)
    at Gulp.<anonymous> (/var/www/node_modules/laravel-elixir/dist/Task.js:193:67)
    at module.exports (/var/www/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/var/www/node_modules/run-sequence/index.js:88:16)
```
Here are my node, npm and gulp versions:
```sh
$ node -v
v5.4.1
$ npm -v
3.3.12
$ gulp -v
CLI version 3.9.0
Local version 3.9.0
```

### Downgrade node version
I downgraded to a v3 of node because I read somewhere that it could be it. No luck
### reinstall laravel-elixir and gulp
I removed all the node_modules folder and run again `npm install`. No luck
### Install vinyl-map module
From what I understand from the code of `/var/www/node_modules/laravel-elixir/dist/tasks/styles.js` map comes from a require of vinyl-map. I tried to install this module with the following: `npm install vinyl-map`. It installed with success but didn't fix my issue.

## Some thoughts
I do have a few warnings during `npm install`, but since they are only warnings, I'm not sure if it's important or not:
```sh
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

Any idea would be much appreciated, thanks a lot in advance for your help guys!

**Comment by JeffreyWay** [comment]
What does your gulpfile look like?

**Comment by jbajou** [comment]
Hi,

Since my gulpfile is working on my macbook and on a Debian server, I didn't think about showing it! In my debuggin process, I simplified as much as I could:
```js
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.less('app.less', 'resources/css/compiled');
  mix.stylesIn('resources/css/website', 'public/css/website.css');
});
```
It takes the less file and turns it into a nice css file in resources/css/compiled (which I will use later), and we take all css in resources/css/website to create one file in public/css/website.css which is included by the HTML
This produces the error as explained above.

Thanks for your much appreciated help

**Comment by djoks** [comment]
I have this issue to with several plugins.
