### ISSUE TITLE
[6.0] Feature npm scripts

### ISSUE THREAD

**Issue by vinkla** [laravel/elixir#492]
Wouldn't it be awesome if we could simplify the installation processer for newcomers? We can do that by using `gulp` executable in our `package.json` file.

Then we can make the `package.json` in `laravel/laravel` look like this:

```json
{
  "private": true,
  "scripts": {
    "postinstall": "gulp --production",
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "laravel-elixir": "^5.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}
```

This means developers can use `npm run dev` which is an alias for `gulp watch` and `npm run prod` which is an alias for `gulp --production`.

Benefits;
- The `laravel/laravel` package will only have `laravel-exlixir` as its dependency.
- The `gulp` file will be executed after installing the dependencies with `npm install`.
- The users don't have to install `gulp` globally.

@JeffreyWay what do you think? If you think this is a good idea I'm happy to make pull requests.

**Comment by JeffreyWay** [comment]
Yeah, I think that would be a good PR for laravel/laravel.

**Comment by vinkla** [comment]
@JeffreyWay awesome. Then I'm on it!
