### ISSUE TITLE
Gulp with Browserify and ReactJS

### ISSUE THREAD

**Issue by raymondidema** [laravel/elixir#494]
Maybe I am doing it wrong but elixir minifies react.js but not using react.min.js and it showing a warning.

`app.js:1 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.`

gulpfile.js
```
elixir(function(mix) {
    mix.sass('app.scss')
        .browserify([
        'app.js'
    ], 'public/js/app.js')
        .browserSync({
            proxy: 'my-project.local'
        });
});
```

app.js
```
import React from 'react';
import ReactDOM from 'react-dom';
import AirBNBSearch from './airbnb-search/search.js';

// Teardown airbnb search tool, can i create some like that
ReactDOM.render(<AirBNBSearch cities={cities} />, document.getElementById('airbnbSearch'));
```

**Comment by raymondidema** [comment]
Did found a workaround, it is the NODE_ENV

Once i hit this command it works perfect.
`NODE_ENV='production' gulp --production`

**Comment by mrcsmcln** [comment]
Is there any way to emulate this behavior from `gulpfile.js`?

**Comment by krisanalfa** [comment]
@mrcsmcln, I used this in my `gulpfile.js`:

```js
elixir(function(mix) {
  if (elixir.config.production) {
    process.env.NODE_ENV = 'production';
  }

  // ...
});
```

**Comment by mrcsmcln** [comment]
@krisanalfa That works wonderfully! I was using an alias:
```
alias prod="NODE_ENV='production' gulp --production"
```
@JeffreyWay Would you oppose to @krisanalfa's snippet being included in the Elixir core? I'm sure plenty of people would appreciate the performance benefit of minified templates and not having to include certain error messages and devtools in Vue and React, among other libraries/frameworks.

**Comment by krisanalfa** [comment]
@mrcsmcln Yeah, you can also modify your `package.json` file:

```
"scripts": {
  "prod": "NODE_ENV='production' gulp --production",
   "dev": "gulp watch"
},
```

Run it by executing:

```
npm run prod
```
