### ISSUE TITLE
is 4.0 the newest version?

### ISSUE THREAD

**Issue by FWSimon** [laravel/elixir#495]

**Comment by vinkla** [comment]
No, 5.0.

**Comment by FWSimon** [comment]
ahh okay, is there anywhere i can see version here on github?
can only see https://github.com/laravel/elixir/releases

**Comment by vinkla** [comment]
That is a good question. @JeffreyWay do you know?

**Comment by JeffreyWay** [comment]
You can find the latest release info here: https://www.npmjs.com/package/laravel-elixir

I'm finishing up some final things for v6, so that'll be out soon.
