### ISSUE TITLE
Dependency chaos with Node v6.0.0.

### ISSUE THREAD

**Issue by ellisio** [laravel/elixir#496]
This is more of just a heads up, than a bug. Node v6.0.0 released. Some of the dependencies of Gulp use `graceful-fs@3.x.x` and older, which break Gulp. I would add a note to the installation stating that users should be running Node v5.11.0 or less until Gulp is fixed.

**Comment by jrean** [comment]
@ellisthedev 
https://forum.ionicframework.com/t/dont-rush-to-upgrade-to-node-v6/50657

**Comment by JeffreyWay** [comment]
Thanks for this! Good to know.

**Comment by jonnywilliamson** [comment]
Was having this issue until I downgrade back to node 5. Thanks for the info.

![image](https://cloud.githubusercontent.com/assets/2513663/18033054/9799c9e0-6d10-11e6-895c-7764eb9e4beb.png)
