### ISSUE TITLE
Source map issue

### ISSUE THREAD

**Issue by jrean** [laravel/elixir#497]
Hi @JeffreyWay 

Basic workflow:

```
var elixir = require('laravel-elixir');
var htmlmin = require('gulp-htmlmin');
var gulp = require('gulp');

elixir(function(mix) {
    mix.sass([
        'main.scss',
    ], 'resources/assets/css/main.css');

    mix.styles([
        'node_modules/vegas/dist/vegas.css',
        'resources/assets/css/main.css'
    ], 'public/css/app.css', './');

});
```

1) Process the `sass` file and create/update the `main.css` file into the `resources/assets/css` directory.

> This produce `main.css` and `main.map.css`.

```
main.css has at the bottom:

/*# sourceMappingURL=main.css.map */
```

```
main.css.map is as follow:

{"version":3,"sources":["main.css","../../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss","../ .... ..... .....
```

2) Mix the listed `css` files into as `app.css` into the `public/css` directory

> This produce `app.css` and `app.css.map`.

```
main.css has at the bottom:

/*# sourceMappingURL=main.css.map */

/*# sourceMappingURL=app.css.map */
```

```
app.css.map is as follow:

{"version":3,"sources":["vegas.css","main.css"],"names":[],"mappings":"AAAA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA; ... ... ...
```

Can you please help?

Thxs.

**Comment by vinkla** [comment]
@jrean is this related to #453?

**Comment by jrean** [comment]
@vinkla thanks for the link. Not sure if it is related but it seems to be very close.
I tried to provided as much details as possible so the repo managers / contributors can decide.

Thanks :)

**Comment by jrean** [comment]
@JeffreyWay can we have your thoughts on this one, please?

**Comment by JeffreyWay** [comment]
Yeah this is a duplicate and a known issue. So closing this one.
