### ISSUE TITLE
Not a function

### ISSUE THREAD

**Issue by djoks** [laravel/elixir#498]
I have tried several plugins, downlaoded tthem and required them but when I try to run gulp I get:
"TypeError: mix.angulartemplatecache is not a function"

or 

"TypeError: mix.ngtemplates is not a function"

**Comment by vinkla** [comment]
Please provide more information.

**Comment by djoks** [comment]
Well I finally found a work around, seems like the issue was with the "require()" it couldn't require the file, so I had to copy the contents of the packages index.js and paste it in my gulpfile.js before it could recognize the function.

**Comment by djoks** [comment]
Uhm why has this been closed? The issue was never resolved.  That work around is not a perfect solution, Imagine having to dump several packages in your gulpfile.js

**Comment by vinkla** [comment]
> Uhm why has this been closed? The issue was never resolved.

You wrote a comment:

> Well I finally found a work around…

This implies that the issue has been fixed.

**Comment by djoks** [comment]
Nope didn't say the issue has been fixed, a work around as in a temporary solution but it is in no way a perfect solution.

**Comment by vinkla** [comment]
@djoks okay. Please share more information about your issue.

**Comment by djoks** [comment]
It is as I said before I tried to require two packages in my gulpfile.js but I kept getting not a function whenever I tried to call mix.something().  This stopped when I dumped the contents of each package's index.js file into my gulpfile.js.  The packages are: **laravel-elixir-ng-templates** and another similar package.

**Comment by djoks** [comment]
Dunno if it is an issue with elixir or an issue with those specific packages working in elixir.

**Comment by vinkla** [comment]
Yeah, sounds like there might be something with the plugin packages and not this one.

**Comment by djoks** [comment]
However those packages are in use though, and I see 0 open issues on their respective git pages.  Second package is **elixir-angular-template-cache**.
