### ISSUE TITLE
Laravel elixir - gulp not working on Linux 

### ISSUE THREAD

**Issue by somecodergit** [laravel/elixir#499]
I have installed nodejs, npm. But when I run `gulp` it doesn't compile sass file. I'm using Linux Mint. When I run `gulp` it doesn't show any errors or anything at all.
My gulpfile.js is:
`var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.sass('app.scss');
});

`

**Comment by vinkla** [comment]
Please share you `gulpfile.js`.

**Comment by somecodergit** [comment]
I updated it.

**Comment by huglester** [comment]
gulp -v
npm -v
?

**Comment by hackel** [comment]
For fear of stating the obvious, have you put your app.scss in `resources/assets/sass`?  If not, you need to set the correct path in the `assets.css.sass.folder` Config property.
