### ISSUE TITLE
Incorrect elixir paths returned when Laravel project is located in a subdirectory

### ISSUE THREAD

**Issue by bjhansen-ualr** [laravel/elixir#501]
I noticed that when I used the Elixir helper function it returns an absolute path to the root of the server. I have a project that's located in a directory (http://server.test/project) and couldn't get my versioned css and js files to be loaded correctly. 

In Illuminate\Foundation\helpers.php line 349 I changed
`return '/'.$buildDirectory.'/'.$manifest[$file];`
to
`return url($buildDirectory.'/'.$manifest[$file]);`
so that it would return a path relative to where my project is located.

This was the only way I found to get my project to correctly reference my versioned build files.

**Comment by laracasts** [comment]
Sounds like this is a laravel/framework issue. This repo doesn't have that function.
