### ISSUE TITLE
gulp-notify: [Laravel Elixir] Less Compilation Failed: Invalid mapping: 

### ISSUE THREAD

**Issue by mania25** [laravel/elixir#506]
Hello, i've got this following error when i run `gulp` command

> [12:01:58] Using gulpfile E:\Abdurrahman\Kerjaan\SI Rumah Sakit\si-rsia\gulpfile.js
> [12:01:58] Starting 'default'...
> [12:01:58] Starting 'less'...
> 
> Fetching Less Source Files...
>    - resources\assets\less\pages.less
> 
> 
> Saving To...
>    - public\css\pages.css
> 
> [12:01:59] Finished 'default' after 1.66 s
> [12:02:00] gulp-notify: [Laravel Elixir] Less Compilation Failed: Invalid mapping: {"generated":{"line":686,"column":12},"source":"E:/Abdurrahman/Kerjaan/SI Rumah Sakit/si-rsia/resources/assets/less/pages.less","original":{"line":1,"column":null},"name":null} in file undefined line no. undefined
> { [Error: Invalid mapping: {"generated":{"line":686,"column":12},"source":"E:/Abdurrahman/Kerjaan/SI Rumah Sakit/si-rsia/resources/assets/less/pages.less","original":{"line":1,"column":null},"name":null} in file undefined line no. undefined]
>   message: 'Invalid mapping: {"generated":{"line":686,"column":12},"source":"E:/Abdurrahman/Kerjaan/SI Rumah Sakit/si-rsia/resources/assets/less/pages.less","original":{"line":1,"column":null},"name":null} in file undefined line no. undefined',
>   stack: 'Error: Invalid mapping: {"generated":{"line":686,"column":12},"source":"E:/Abdurrahman/Kerjaan/SI Rumah Sakit/si-rsia/resources/assets/less/pages.less","original":{"line":1,"column":null},"name":null}\n    at SourceMapGenerator_validateMapping [as _validateMapping] (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\source-map\\lib\\source-map-generator.js:277:13)\n    at SourceMapGenerator_addMapping [as addMapping] (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\source-map\\lib\\source-map-generator.js:101:12)\n    at SourceMapOutput.add (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\source-map-output.js:88:42)\n    at Selector.genCSS (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\tree\\selector.js:98:16)\n    at Ruleset.genCSS (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\tree\\ruleset.js:393:25)\n    at Ruleset.genCSS (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\tree\\ruleset.js:414:18)\n    at SourceMapOutput.toCSS (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\source-map-output.js:126:24)\n    at SourceMapBuilder.toCSS (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\source-map-builder.js:23:35)\n    at ParseTree.toCSS (E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\parse-tree.js:33:47)\n    at E:\\Abdurrahman\\Kerjaan\\SI Rumah Sakit\\si-rsia\\node_modules\\less\\lib\\less\\render.js:31:40',
>   lineNumber: undefined,
>   fileName: undefined,
>   name: 'Error',
>   showStack: false,
>   showProperties: true,
>   plugin: 'gulp-less' }
> [12:02:00] Finished 'less' after 2 s

i'm using laravel 5.2 and windows 10, here my `gulpfile.js` 

```
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
    mix.less('pages.less');
});

```

please help me, thank you

**Comment by cs45977** [comment]
This is an issue with less 2.7.0  https://github.com/less/less.js/issues/2896

The temporary fix is to use less 2.6.1

`npm uninstall less -save`

`npm install less@2.2.1`

--- at least that is what worked for me

**Comment by mania25** [comment]
okay, but i'm using laravel-elixir which depend on less 2.7.0, or can i just downgrade it?is there will be conflict with laravel-elixir? thank you

**Comment by cs45977** [comment]
@mania25 I cant speak for the long term impact.  I can only say it solved my problem that I was having with laravel spark

**Comment by jbajou** [comment]
downgrading LESS fixed it for me too. It is a good temporary fix. Just downgrade while the less team is patching, and update again as soon as it is fixed.

**Comment by mania25** [comment]
okay i'll give it a try, thank you
