### ISSUE TITLE
Gulp tasks should run in sequence

### ISSUE THREAD

**Issue by alexandrubau** [laravel/elixir#508]
I'm trying to use [Bootstrap](http://getbootstrap.com) for my project and I would like to sandbox all CSS classes with a prefix such as *bs-*. Elixir doesn't provide a solution out-of-the-box for this, therefore I've implemented a custom Gulp task:

```
var prefix  = require('gulp-css-prefix');

gulp.task('prefix-css', function(){

    return gulp
        .src([
            'node_modules/bootstrap/dist/css/bootstrap.css'
        ])
        .pipe(prefix('bs-'))
        .pipe(gulp.dest('resources/assets/css'));
});

elixir(function(mix){

    mix
        .task('prefix-css')
        .styles([
            'bootstrap.css'
        ], 'public/css/all.css')
});
```

It always gives an error, because Elixir doesn't wait for the gulp task to finish. The *bootstrap.css* file will never be there when needed for minifying. I would really like to continue to use Elixir for my project.

Can anyone help me get around this?

**Comment by JeffreyWay** [comment]
Hmm, you might need to instead create an actual Elixir extension.

**Comment by alexandrubau** [comment]
Thanks @JeffreyWay. I'll try to make an extension as provided in the [docs](https://laravel.com/docs/5.2/elixir#writing-elixir-extensions).
