### ISSUE TITLE
PostHTML support

### ISSUE THREAD

**Issue by Grawl** [laravel/elixir#509]
Like PostCSS, [PostHTML](https://github.com/posthtml) is a growing technology and a community filling up with plugins to process HTML (and PHP too) through AST tree with JS code.

It's already [have plugins](http://maltsev.github.io/posthtml-plugins/)
- read images and [add their sizes](https://github.com/maltsev/posthtml-img-autosize) into `<img>` elements,
- [improve accessibility of tabs](https://github.com/jonathantneal/posthtml-aria-tabs) and [add missing `alt` attributes](https://github.com/ismamz/posthtml-alt-always),
- [inline any assets](https://github.com/jonathantneal/posthtml-inline-assets) you want,
- maintain [BEM classnames](https://github.com/rajdee/posthtml-bem) or [use CSS modules](https://github.com/admdh/posthtml-modular-css),
- and even [use PostCSS](https://github.com/posthtml/posthtml-postcss) on inline styles.

It's highly important to implement this technology right now.

**Comment by JeffreyWay** [comment]
It's best for this to be an Elixir extension for now. If it gets a lot of usage, we can then consider adding it to core.
