### ISSUE TITLE
Why same md5 file has different hash version?

### ISSUE THREAD

**Issue by xfight0** [laravel/elixir#510]
Hello developers, I used the code like:
```
mix.version(['dist/css/app.css', 'dist/js/app.js']);
```
I deploy my app in different two host, and gulp generate two app.js file, but the same two js file generate different hash version....
However the same two css file generate same hash version.
Why was that?

**Comment by JeffreyWay** [comment]
I'm not entirely sure what you mean here. Each time you run mix.version(), it'll generate a unique hash for each file.

**Comment by jdavidbakr** [comment]
I think we are having the same issue as @happyhero0 - we have a project deployed to two servers behind a load balancer.  We are not using sticky sessions, which means that sometimes users get their html file from one server and then attempt to get the javascript from another.  However, for some reason the vue compiling puts the templates in a different order on each server, making the md5 hash of the files different, and causing each server to have a different compiled filename.  Re-running gulp on each server builds to the same filename even though they are different on each server.

A possible solution might be to hook into the gulp-rev options and enable setting the revHash to, maybe, the git SHA hash?
