### ISSUE TITLE
gulp/elixir autoreload feature

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [laravel/elixir#512]
@taylorotwell, @JeffreyWay:
 
it's nice to have gulp watch autoreload itself when changing gulpfile.js

this is how I do it:

```

var gulp = require('gulp');
var spawn = require('child_process').spawn;

gulp.task('watch-autoreload', function() {
    var process;

    function restart() {
        if (process) {
            process.kill();
        }
        process = spawn('gulp', ['watch'], {stdio: 'inherit'});
    }

    gulp.watch('gulpfile.js', {interval: 1000}, restart);
    restart();
});

```

may be you'll integrate it in elixir.

**Comment by JeffreyWay** [comment]
Eh, I think most are fine with restarting gulp. You rarely change your gulpfile.

**Comment by Vasiliy-Bondarenko** [comment]
I do quite often changing the test set i want to run from now on.
As you said - seconds add up :)

вс, 15 мая 2016 г. в 21:57, Jeffrey Way <notifications@github.com>:

> Eh, I think most are fine with restarting gulp. You rarely change your
> gulpfile.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/laravel/elixir/issues/512#issuecomment-219290490>
>
-- 
// Vasiliy A Bondarenko
