### ISSUE TITLE
Cannot read property 'pluginOptions' of undefined

### ISSUE THREAD

**Issue by bruno-barros** [laravel/elixir#513]
I'm setting up outside of Laravel.

Part of error output:
´´´
 Cannot read property 'pluginOptions' of undefined
    at gulpTask (D:\www\weloquent-bootstraped\node_modules\laravel-elixir\tasks\styles.js:51:67)
    at null.definition (D:\www\weloquent-bootstraped\node_modules\laravel-elixir\tasks\styles.js:22:25
´´´

My Gulpfile.js

´´´
var elixir = require('laravel-elixir');
var assets = 'src/themes/default/assets';

elixir.config.production = true;
elixir.config.assetsPath = assets;
elixir.config.publicPath =assets;

elixir(function (mix) {
    mix.styles([
       'bootstrap.css',
       'layout.css',
       'modules.css',
       'pages.css'
    ], assets+'/css/_global.css');
});
´´´

Any help?

**Comment by JeffreyWay** [comment]
Which version of Laravel Elixir do you have installed? Check your package.json file.

**Comment by bruno-barros** [comment]
It is ^4.0.0

Maybe it should be only 4.0.0

**Comment by JeffreyWay** [comment]
I can't reproduce this. Maybe try deleting your `node_modules` directory and re-doing `npm install`.

**Comment by bruno-barros** [comment]
Apperantly I'm not installing all dependencies corretly.
I'm running GitBash on Windows, so I did...
Update Elixir to 3.0.0 and ran ´npm install´ with PowerShell that has more privileges than GitBash.
And it works, but not with 4.0.0.
