### ISSUE TITLE
laravel-elixir browserify can not pass {debug: true} option?

### ISSUE THREAD

**Issue by cnweibo** [laravel/elixir#515]
Hi, 
When i use laravel-exilxir to build vuejs with browserify, i can not find a right way to give {debug: true}
option to browserify.
Is this a bug for elixir or i do not know the right usage manner?
Please give a clue.

Thanks~!

**Comment by hackel** [comment]
In my gulpfile, I have:
`elixir.config.js.browserify.options.debug = !elixir.config.production;`

**Comment by cnweibo** [comment]
@hackel ,
Thanks for your quick proposal. You have saved one day for me!
