### ISSUE TITLE
gulp watch recompiles all less targets instead of only the one that changed

### ISSUE THREAD

**Issue by hackel** [laravel/elixir#516]
I have 5 different mix.less() calls in my gulpfile, and when I change a file in any one of them, all of the other unmodified files get rebuilt as well.  This doesn't happen with my two separate browserify calls.  When I modify a file in one, only that particular file gets recompiled.  I don't know if this only works so well because of watchify, but it would be a really nice feature to add when watching less (as well as any other tasks like scss, etc. that I have not tested!).

Edit: I'm running 5.0.0.

**Comment by JeffreyWay** [comment]
This is just how Elixir works for the moment. 

5 mix.less() calls seems like a lot, though. I have one.

**Comment by younes0** [comment]
@hackel same problem here, did you find a workaround?

**Comment by hackel** [comment]
Yeah, 5 is a lot, but I've got separate css output files for backend/frontend, plus a separate print.css for each.  I could definitely bring it down to 4, but I can't imagine having at least two would be that uncommon.

Perhaps something like this could be used, similar to watchify: https://github.com/Craga89/gulp-watch-less

@younes0: Nope, just dealing with it for now!
