### ISSUE TITLE
Wrong path for phpUnit on Windows

### ISSUE THREAD

**Issue by pataelmo** [laravel/elixir#518]
With a fresh install of laravel 5, changing gulpfile.js to run phpUnit fails with the following error:

[12:39:46] Using gulpfile ~\Documents\laravel\learning-laravel5\gulpfile.js
[12:39:46] Starting 'default'...
[12:39:46] Starting 'PHPUnit'...

Triggering PHPUnit: vendor/bin/phpunit --verbose
[12:39:46] Finished 'default' after 64 ms
'vendor' is not recognized as an internal or external command,
operable program or batch file.
[12:39:46] gulp-notify: [Red!] Your PHPUnit tests failed!
[12:39:46] Finished 'PHPUnit' after 100 ms

The fact that unix style paths are being used in windows jumped out at me, so I tested that by running:
vendor/bin/phpunit --verbose
I get:
'vendor' is not recognized as an internal or external command,
operable program or batch file.

However, running:
vendor\bin\phpunit --verbose
I get:
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

Runtime:        PHP 5.6.21
Configuration:  C:\Users\pataelmo\Documents\laravel\learning-laravel5\phpunit.xml

.

Time: 1.91 seconds, Memory: 9.25MB

OK (1 test, 2 assertions)

Is there something I'm missing?  Or at least a hack I can implement to fix the path used by gulp/elixir for phpunit?

**Comment by JeffreyWay** [comment]
Yeah - we can change the directory separators. Submit a pull request if you want, and we'll merge it in.

**Comment by pataelmo** [comment]
Thanks @JeffreyWay.  I think I have a cross OS compatible fix in Pull Request #519.  I'm new to Laravel, so I don't have a stable clean install working on my linux machine to test against, so any validation that I didn't break anything would be great.

**Comment by pascal08** [comment]
This issue is solved in https://github.com/laravel/elixir/pull/519 and can be closed now.

**Comment by pataelmo** [comment]
Agreed
