### ISSUE TITLE
Failed gulp task should terminate further execution

### ISSUE THREAD

**Issue by ignasbernotas** [laravel/elixir#520]
This is something that I'm not entirely sure about, basically whether it's elixir's abstraction layer that fails to stop the execution or gulp itself.

The problem is that when a task fails, it outputs the error message but proceeds to continue. This is a massive issue when running gulp as one of our deployment tasks. Envoyer fails to catch it, build is marked as successful and everything breaks down.

Two cases that actually caused our production environment to go down were SCSS failing to compile and having a typo in a require() path in one of our scripts. In both cases the builds were marked as passed. Obviously these are human errors and were quickly fixed, but I think Envoyer should be able to pick this stuff up.

**Comment by JeffreyWay** [comment]
This is done in the next release, which will be out soon.

Thanks!
