### ISSUE TITLE
gulp less keep folder structure

### ISSUE THREAD

**Issue by yekz** [laravel/elixir#521]
I have folder structure like this:
```
|----themes
      |----default
            |----style
                  |----style.less
      |----anothertheme
            |----style
                  |----style.less
```
By default, run `mix.less('**/*.less')` will only generage one file: `public/css/style.css`

But, what I need is keep folder structure:
```
|----themes
      |----default
            |----style
                  |----style.css
      |----anothertheme
            |----style
                  |----style.css
```
I know I can do like that:
```js
mix.less('themes/default/style/style.less', 'public/css/themes/default/style/style.css')
mix.less('themes/anothertheme/style/style.less', 'public/css/themes/anothertheme/style/style.css')
...
```

after some search, I found this: [Gulp.js - Use path from gulp.src() in gulp.dest()](http://stackoverflow.com/questions/22240977/gulp-js-use-path-from-gulp-src-in-gulp-dest)

but in `/node_modules/laravel-elixir/tasks/shared/Css.js`, I can't pass this option in
```js
gulp.src(options.src.path, ____HERE____)
        .pipe($.if(config.sourcemaps, $.sourcemaps.init()))
```

**Comment by JeffreyWay** [comment]
The current recommendation is to just call mix.less() multiple times, like you've done.
