### ISSUE TITLE
gulp watch folders/new files

### ISSUE THREAD

**Issue by Antonimo** [laravel/elixir#522]
I have homestead on ubuntu 14 and I run gulp from inside homestead.
the site is on the shared folder (~/www)
it works fine if you use the setting
usePolling: true

https://www.npmjs.com/package/gulp-watch
https://github.com/paulmillr/chokidar#api

**Comment by JeffreyWay** [comment]
What's the problem? You didn't say what went wrong...

**Comment by Antonimo** [comment]
oh. new files are ignored when running gulp inside homestead and the files are created in the host pc.

**Comment by JeffreyWay** [comment]
We'll use polling in the next release. Already implemented.
