### ISSUE TITLE
Dont version the build folder

### ISSUE THREAD

**Issue by alexbowers** [laravel/elixir#525]
If you have `mix.version(['*']);`, the build folder gets added to the build. It shouldn't be.

**Comment by alexbowers** [comment]
@JeffreyWay I believe I have reported this in the past, and it was closed and marked as solved, but its still happening.

**Comment by JeffreyWay** [comment]
Which version of Elixir are you using?

**Comment by alexbowers** [comment]
`^5.0.0`

**Comment by claudiodekker** [comment]
It should already do this automatically, but you also manually 'ignore' folders by putting an `!` in front of it like so: `!public/build`
