### ISSUE TITLE
Angular Breaks with --production

### ISSUE THREAD

**Issue by joshmedeski** [laravel/elixir#532]
When I'm compiling JS with the `--production` flag, Something simplifies the Angular functions when it minifies.

The following error occurs:
```
angular.min.js:6Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=app&p1=Error%3A%20%…2F%2Fwww.stdcheck.local%2Fbuild%2Fjs%2Ffront-head-bec67457f0.js%3A4%3A7140)
```

At this point, we've had to deploy our work without minifying. Do you know how to resolve this issue?

**Comment by joshmedeski** [comment]
It could have something to do with the [mangle option](https://github.com/gruntjs/grunt-contrib-uglify#mangle) for Uglify.

How would you change the configuration settings for this?

**Comment by hackel** [comment]
Just thought I would point out that I, and many others, am using Angular with Elixir in production with no issues, so this is very likely not an Elixir issue.

My first thought is that you aren't explicitly defining your injected dependencies, which is a very common issue when minifying angular code.  I use browserify-ngannotate for this purpose, but there are several other ways to solve it, and the best practice is to simply define them explicitly with array notation.

**Comment by JeffreyWay** [comment]
Oh good. Well if this isn't an Elixir issue specifically, I'm going to close this thread.
