### ISSUE TITLE
[Request] Option to reduce notification clutter

### ISSUE THREAD

**Issue by hackel** [laravel/elixir#535]
When running gulp with a fairly complicated gulpfile, I end up with 15-20 different notifications displayed sequentially.  On Ubuntu, these are displayed for ~7s each, rendering them rather ineffective as they are stil showing up long after the build has completed.  I would really love to have an option to collapse all notifications into a single notification at the end of a gulp run (either manual or from gulp watch).  It doesn't really matter to me when the less file has finished compiling vs. browserify vs. scripts merged.  I just want to know when it's all done and I should reload my app.

I'm thinking that with such an option enabled, notifications could be added to a queue, and then at the very end, if there is only one notification in the queue, just display it, otherwise concatenate them all to display something like "Laravel Elixir - Less compiled, Browserify compiled, Scripts merged!"

**Comment by JeffreyWay** [comment]
There will be an option to disable them entirely in the next release.

**Comment by hackel** [comment]
I don't want to disable notifications entirely!  i already do that with DISABLE_NOTIFIER in my CI build script anyway.
