### ISSUE TITLE
Unable to override `elixir.config.batchOptions.timeout` value in v6.0.0-2

### ISSUE THREAD

**Issue by manuelbua** [laravel/elixir#538]
I'm trying to override the default timeout value of `elixir.config.batchOptions.timeout` in this way in my `gulpfile.js`:

    var elixir = require('laravel-elixir');
    elixir.config.batchOptions.timeout = 100;

This works fine for `laravel-elixir-v5.0.0` but it doesn't work in `laravel-elixir-v6.0.0-2`: i can see there was a switch to ES6 between the published versions `v5.0.0` (`2def8c99ddc4aef42de981b175198e550ee8a9d2`) and `v6.0.0-2` (`a0daa5b1adc5a7579259f99a71fed06430ff7270`) so it's difficult to pinpoint what's going on due to things being moved/refactored.

Am i doing it wrong?

Also, since i noticed there are no tags nor github releases for `5.0.0`, `6.0.0-2`, etc.. i suppose there is no standardized practice to produce releases yet or am i missing something obvious?

**Comment by JeffreyWay** [comment]
Hmm, that should definitely work.

We reference that config property in the watch task. Try doing `console.log(Elixir.config.batchOptions)` here to see what it returns.

https://github.com/laravel/elixir/blob/master/src/tasks/recipes/watch.js#L20
