### ISSUE TITLE
Gulp Watch endless loop

### ISSUE THREAD

**Issue by jrean** [laravel/elixir#541]
Hi,

I've stuck for several hours, still trying to understand. Asked on Slack, posted on Laracasts...

```
elixir(function(mix) {

    mix.sass('app.scss', 'resources/assets/css');
    mix.sass('dashmin.scss', 'resources/assets/css');

    mix.styles([
        'node_modules/1.css',
        'node_modules/2.css',
        'node_modules/3.css',
        'bower_components/4.css',
        'bower_components/5.css'
    ], 'resources/assets/css/libs.css', './');

    mix.styles([
        'resources/assets/css/app.css',
        'resources/assets/css/libs.css'
    ], 'public/css/min.css', './');
```

Endless loop.
I don't understand. If one provides an answer please explain with as much as details as possible.
Thank you very much

**Comment by JeffreyWay** [comment]
I think it's because of your "resources/assets/css/libs.css" reference in both `mix.styles()` calls.

**Comment by jrean** [comment]
Thank you @JeffreyWay for the feedback. So can you explain and share with me how to achieve what I'm trying to do?

- Compile `app.scss`
- Compile `dashmin.scss`
- Mix all the libs into a single file
- Mix `app.css` + `libs.css` together

**Comment by jrean** [comment]
Here is the solution I found. It doesn't sound natural at first, but if it is the way it works... Maybe it will help someone:
(I keep track of separate file mainly because of https://github.com/laravel/elixir/issues/497)

```
    mix.sass('app.scss');
    mix.sass('dashmin.scss');

    // Libraries
   // We keep track of the file alone mainly because of the css map "issue" I encounter
   // https://github.com/laravel/elixir/issues/497
    mix.styles([
        'node_modules/1.css',
        'node_modules/2.css',
        'node_modules/3.css',
        'bower_components/4.css',
        'bower_components/5.css',
    ], 'public/css/libs.css', './');

    // Final file
    // We build the final file
    mix.styles([
        'node_modules/1.css',
        'node_modules/2.css',
        'node_modules/3.css',
        'bower_components/4.css',
        'bower_components/5.css',
        'public/css/app.css'
    ], 'public/css/min.css', './');
```

Thank you @JeffreyWay for the input.
