### ISSUE TITLE
Elixir.Task require problem [6.0.0-3 pre-release]

### ISSUE THREAD

**Issue by wesleyhf** [laravel/elixir#544]
```sh
$ gulp
module.js:442
    throw err;
    ^

Error: Cannot find module '../tasks/Task'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/project/node_modules/laravel-elixir/dist/bootstrap/SetDependencies.js:71:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

The require task on SetDependencies.js is incorrect because of case sensitive. https://github.com/laravel/elixir/blob/master/src/bootstrap/SetDependencies.js#L69

And the task.js on my node_modules is lowercase.

![image](https://cloud.githubusercontent.com/assets/2936121/16204261/758abaf0-36f4-11e6-8058-727e516eaf7c.png)

**Comment by JeffreyWay** [comment]
Are you sure you have the latest pre-release? That file is capitalized.

https://github.com/laravel/elixir/blob/master/src/tasks/Task.js

**Comment by nacr-dev** [comment]
+1 on this one

**Comment by nacr-dev** [comment]
@wesleyhf did you solve this?

**Comment by nacr-dev** [comment]
help any one?

**Comment by StefanoMagrassi** [comment]
+1

with the latest release (6.0.0-3) the `Task.js` file under `/tasks` folder is lowercase and so the `require()` in SetDependencies.js isn't resolved.

@JeffreyWay do you compile the sources on your machine before publishing the package to npm?
Because, as you said, in `/src` directory the file has the right name, so it could be an OS-related problem.

For now, I try to roll-back to 6.0.0-1 version

**Comment by StefanoMagrassi** [comment]
I cloned the repository on my computer and compiled the sources: everything went right... 

I also noticed that one devDependency is missing (babel-preset-es2015) in package.json.
I'll send a PR soon.

**Comment by JeffreyWay** [comment]
Looks like the compiled task was lowercase. This will be fixed in the next pre-release.

**Comment by wesleyhf** [comment]
Thanks @JeffreyWay
