### ISSUE TITLE
Elixir is stripping @-webkit-keyframes, request to have autoprefixer configurable.

### ISSUE THREAD

**Issue by rebz** [laravel/elixir#545]
I have several animations occurring on a responsive website and for Safari on iPad I must have the `-webkit` prefix for keyframes. As it stands right now autoprefixer is removing my prefixes for @keyframes. If I want to override this I must edit `/node_modules/laravel-elixir/Config.js` to include the option `remove: false;` since it defaults to `true`.

It would be great if I could slap the following line in my gulp file.
`elixir.config.autoprefix.remove = false;`

Any chance of allowing us to configure autoprefixir?

**Comment by JeffreyWay** [comment]
You already can.

```
Elixir.config.css.autoprefix.options = {}; // <-- options there
```

**Comment by rebz** [comment]
Was missing the CSS part, thanks!
