### ISSUE TITLE
6.0.0-3 Pre-Release - Override versioned files output folder

### ISSUE THREAD

**Issue by rsdev000** [laravel/elixir#546]
Hi

I have this in my gulpfile.js ```.version(['css/app.css', 'js/app.js'], "./public")``` and with laravel-elixir v5.0.0 the versioned files were created in ```public/css/app-ab76c3.css``` and ```public/js/app-a23db2.js```.

How can I get the same behaviour from v6.0.0-3 ?

Cheers

**Comment by JeffreyWay** [comment]
You'll be able to do that in the next pre-release. I already have it implemented locally.

**Comment by rsdev000** [comment]
Thank you very much. I've found another problem and I'll report it in a few minutes.
