### ISSUE TITLE
v6.0.0-3 - Gulp error on scripts task: masonry 

### ISSUE THREAD

**Issue by rsdev000** [laravel/elixir#549]
Have an app that uses the masonry js script ( http://masonry.desandro.com )

Gulpfile scripts:
```
       .scripts([
          scripts.jquery,
          scripts.fastclick,
          scripts.instantclick,
          scripts.masonry,
          scripts.scrolltop,
          scripts.loadcss,
          scripts.loadcsspre,
          scripts.loadcssonload,
          scripts.cookieconsent,
          scripts.cookieconsopt,
          scripts.main
       ], paths.public.js + 'app.js')
```

With laravel-elixir v5.0.0 everything works ok. With v6.0.0-3, gulp throws an error´
```
ERROR in ./resources/assets/vendor/masonry/dist/masonry.pkgd.js
Module not found: Error: Can't resolve 'jquery' in 'c:\Work\www\projects\starter\resources\assets\vendor\masonry\dist'
 @ ./resources/assets/vendor/masonry/dist/masonry.pkgd.js 141:2-71
```

Steps to reproduce
1 - Delete node_modules folder
2 - npm install with laravel-elixir v5.0.0
3 - gulp (no errors, app.xxxxxx.js is generated with masonry and app works as expected)
4 - Delete node_modules folder
5 - npm install with laravel-elixir v6.0.0-3
6 - gulp (throws the error described above. app.js is generated with masonry but not versionated)

Note: After the error, loading js and css resources without the elixir() helper makes the app work as expected

Cheers

**Comment by JeffreyWay** [comment]
Do you only want to concatenate those files together? If so, use `mix.combine()` instead.

**Comment by rsdev000** [comment]
TY. mix.combine() solved the problem. I just want to combine the files, so what´s the difference between scripts() and combine() ?
Upgraded to v6.0.0-4 and could generate versioned files like version 5.0.0, in public/css and public/js but it kept both versioned and unversioned files. What I am missing here?

**Comment by JeffreyWay** [comment]
scripts() is for compilation and concatenation. combine() is for concatenation only.

Give me a code snippet for your versioning question. Not fully following.

**Comment by rsdev000** [comment]
Thank you for the insights. 
After combining the scripts: ```.version(['css/app.css', 'js/app.js'], "./public")``` , the versioned files are created but there are two files in both css and js folders:
Ex: app.css and app-416a797632.css. Is there a way to delete the unversioned file app.css ?

**Comment by JeffreyWay** [comment]
No, we keep the original file so that mix.version() will work the next time too.

**Comment by rsdev000** [comment]
Ok! :) Thank you
