### ISSUE TITLE
buble unmet peer dependency

### ISSUE THREAD

**Issue by ikoolik** [laravel/elixir#551]
Hi there!

Using laravel-elixir 6.0.0-4.

I have stumbled upon a funny issue doing the `npm install` on the codeship CI today. It says:
```
npm ERR! peerinvalid The package buble@0.8.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer buble-loader@0.2.1 wants buble@^0.7.0
```

Everything works ok locally... Kind of.
When I double checked `npm install` locally, I have noticed the very same error, but instead of breaking, the `npm install` ignored it and carried on.

```
│ ├─┬ UNMET PEER DEPENDENCY buble@0.8.5
│ │ ├── acorn@3.2.0 
│ │ └─┬ magic-string@0.14.0 
│ │   └── vlq@0.2.1 
│ ├── buble-loader@0.2.1 
```

So I decided to dive a bit deeper and found out that elixir (6.0.0-4 at the moment) requires "buble": "^0.8.4" and "buble-loader": "^0.2.1". But "buble-loader": "0.2.1" requires "buble": "^0.7.0", which does not fit the "buble": "^0.8.4".

I'm not sure if it's a bug, but it definitely looks like the one to me. I can create a PR with updating buble dependency for elixir, but I am not sure that it's a right way to go.

What do you guys think?

P.S.: I just don't feel like installing two versions of buble is a great idea.

**Comment by JeffreyWay** [comment]
Sure, a PR would be great.
