### ISSUE TITLE
[Proposal] Add ability to combine http/https based stylesheets or js

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel/elixir#553]
It would be really cool to be able to do something like this:

```js
mix.styles([
      'less.css',
      'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css',
      'app.css'
]);
```

**Comment by JeffreyWay** [comment]
Would be cool, but we'd have to create a temporary directory to download all those files... and I'd rather not worry about that for now. 

Maybe in the future.

**Comment by BrandonSurowiec** [comment]
Sounds good.  :)
