### ISSUE TITLE
laravel-elixir@6.0.0-4 error!

### ISSUE THREAD

**Issue by nacr-dev** [laravel/elixir#555]
Hello afther updating to 6.0.0-4, when I run gulp,

I get this error, 

´´´
{lamb} gulp
(node:980) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
C:\Users\nacr\Code\MyApp\node_modules\laravel-elixir-vueify\index.js:3
Elixir.config.js.browserify.transformers.push({
                           ^

TypeError: Cannot read property 'transformers' of undefined
    at Object.<anonymous> (C:\Users\nacr\Code\MyApp\node_modules\laravel-elixir-vueify\index.js:3:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\nacr\Code\MyAPp\gulpfile.js:3:1)
    at Module._compile (module.js:541:32)
´´´

If I use 6.0.0-2 there is no problem.

tks.

**Comment by JeffreyWay** [comment]
And you've installed this extension?

https://github.com/JeffreyWay/laravel-elixir-browserify

**Comment by Eldair** [comment]
Same here, without broserify but with laravel-elixir-vue (using .scripts func)

**Comment by JeffreyWay** [comment]
More information, please.

@Eldair - What do you mean by "it's not good"?

**Comment by Eldair** [comment]
@JeffreyWay when using combination of elixir-vue and laravel-elixir v6.0.0-4 and .scripts func there is an error somewhere in rendering components (which doesn't happen when using elixir-vueify and laravel-elixir v6.0.0-2 with .browserify func). I can only paste partial console output.

**Comment by Eldair** [comment]
Here is the stack right after Vue init
```
warn	@	vue.common.js:1019
Watcher.get	@	vue.common.js:3176
Watcher	@	vue.common.js:3158
Directive._bind	@	vue.common.js:8345
linkAndCapture	@	vue.common.js:6928
compositeLinkFn	@	vue.common.js:6897
Vue._compile	@	vue.common.js:8611
Vue.$mount	@	vue.common.js:9446
Vue._init	@	vue.common.js:2468
VueComponent	@	VM327:2
build	@	vue.common.js:5837
mountComponent	@	vue.common.js:5754
(anonymous function)	@	vue.common.js:5716
(anonymous function)	@	vue.common.js:5734
Vue._resolveComponent	@	vue.common.js:8869
resolveComponent	@	vue.common.js:5736
setComponent	@	vue.common.js:5715
update	@	vue.common.js:5689
Directive._bind	@	vue.common.js:8360
linkAndCapture	@	vue.common.js:6928
compositeLinkFn	@	vue.common.js:6897
Fragment	@	vue.common.js:3757
FragmentFactory.create	@	vue.common.js:3974
create	@	vue.common.js:4210
diff	@	vue.common.js:4109
update	@	vue.common.js:4042
Directive._bind	@	vue.common.js:8360
linkAndCapture	@	vue.common.js:6928
compositeLinkFn	@	vue.common.js:6897
Vue._compile	@	vue.common.js:8611
Vue.$mount	@	vue.common.js:9446
Vue._init	@	vue.common.js:2468
Vue	@	vue.common.js:9510
```

**Comment by Eldair** [comment]
The problem was that I was using `export default` in a mixin instead of `module.exports`. That was causing other issues etc. Now it works correctly (laravel-elixir v6.0.0-4 and elixir-vue)

**Comment by sailingdeveloper** [comment]
I am still having this issue, using 6.0.0-2. Had `laravel-elixir-browserify` installed, but it still crashed on `Elixir.config.js.browserify.transformers`.
Downgraded to ^5.0.0, no problems there.

**Comment by 7ammer** [comment]
I realised that `elixir.config.js.browserify` didn't exist before calling the elixir function so something like this worked for me:

```
var elixir = require('laravel-elixir');

function loadstuff(){
    elixir.config.js.browserify.transformers.push( ... );
}

var i = 0;
elixir(function(mix) {
    if(i == 0){
        loadstuff();
    }

    mix.browserify('app.js');
});
```

This allows the function `loadstuff()` to only load once.
