### ISSUE TITLE
mix.copy() does not work on folders if there is a dot in the directory name

### ISSUE THREAD

**Issue by anik786** [laravel/elixir#559]
### Environment

* Elixir version (gulp elixir -v):
```
[15:33:06] CLI version 1.2.1
[15:33:06] Local version 3.9.1
```

* Operating system: Windows 10 Home

### Current behaviour

I have found that if I use elixir on a directory that contains a dot, it will only copy the folder, but not the contents inside.

For example consider copying a folder called `public/a.something` at the root of the project:

```
exlixir(function(mix) {
    mix.copy('a.something', 'public/a.something');
});
```

The above will only make an empty directory called `a.something` and not copy its contents.

On the other hand the following works fine if the folder is called `a`:

```
exlixir(function(mix) {
    mix.copy('a', 'public/a');
});
```

### Expected behaviour

It should have copied the entire folder as well as the contents within it.

**Comment by JeffreyWay** [comment]
Okay, I've fixed the issue where a period in the src path doesn't copy properly. 

However, if you put a period in the output path, it has no way of knowing if you want a file or a directory. So, like "public/css/foo.bar" ... do you want a file or a directory of foo.bar? It doesn't know.

**Comment by anik786** [comment]
Thanks for the update. Will try it out.

I'm also not sure how a dot would make it more confusing as to why the program cannot determine if you want a file or directory.

It should also easily know if it is a file or directory based on the src. 
If the src is is a directory of course the output should be a directory,
Likewise, if src is a file, the output should also be a file. 
A dot does not make this more complex.

**Comment by JeffreyWay** [comment]
Good point. Done.
