### ISSUE TITLE
.scripts() parsed as Webpack?

### ISSUE THREAD

**Issue by EmilMoe** [laravel/elixir#565]
I updated Elixir and get some strange errors

~~~~shell
resolve 'jquery' in '//resources/components/eonasdan-bootstrap-datetimepicker/build/js'
  Parsed request is a module
..
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }
~~~~

It seems like `.scripts()` are now parsed with Webpack? How can I just merge Javascript files to one? I prefer to do it in my Gulpfile as it's some old stuff, in the future I will be moving to other strategy.

**Comment by EmilMoe** [comment]
Must be Webpack: `mix.scripts()    │ 1. Running Webpack`

**Comment by EmilMoe** [comment]
It seems `.combine()` works. Are there any drawbacks on it or is it the new `.scripts()`?

**Comment by JeffreyWay** [comment]
Keep in mind that Laravel v6 isn't out yet, so the docs haven't been updated.

But, yes, use .combine() for concatenation-only work.
