### ISSUE TITLE
Result messages

### ISSUE THREAD

**Issue by EmilMoe** [laravel/elixir#566]
I'm not sure if it's Elixir or Gulp that generates the messages when the compilation of a Gulpfile is done? 

If it's Elixir: On "smaller" screens 1440x900 the lines are too lone so it's very hard to read it. The old style worked better.

If it's Gulp, let me know and I will submit the issue to that project instead.

**Comment by JeffreyWay** [comment]
Elixir v6 isn't out yet, so still working on that stuff.
