### ISSUE TITLE
version: 6.0.0-4 breaks mix.scripts

### ISSUE THREAD

**Issue by stueynet** [laravel/elixir#567]
Updating to  6.0.0-4 has caused our mix.scripts build process to run extremely slowly and on some developers machines, the output file never gets generated. We have tested this by switching between 6.0.0-2 and 6.0.0-4. 6.0.0-2 == no problemo. We noticed the completely different output style going from 6.0.0-2 to 6.0.0-4 which is what initally made me wonder what was going on.

Here is the relevant portion of our gulpfile:

```
 mix.scripts([
        'bower_components/jquery/dist/jquery.js',
        'bower_components/bootstrap-sass/assets/javascripts/bootstrap.js',
        'bower_components/bootstrap-toggle/js/bootstrap-toggle.js',
        'bower_components/combodate/src/combodate.js',
        'resources/assets/js/vendor/modernizr.js',
        'bower_components/pwstrength-bootstrap/dist/pwstrength-bootstrap-1.2.9.js'
    ], 'public/js/vendor.js', './');
```

**Comment by JeffreyWay** [comment]
It hasn't broken mix.scripts(). You're using a version of Laravel that isn't out yet, and hasn't been documented. 

If you're going to stick with v6 for now, update that to mix.combine().

**Comment by stueynet** [comment]
Ah ok gotcha. I am using Laravel 5.2 but we switched to elixir 6 since it seemed to be moving ahead faster. Will try combine and then possibly revery till its all more stable.

**Comment by EmilMoe** [comment]
Just for notice. When you run NPM outdated it tells you that Elixir 6.0.0-5 is the newest version, so it is kinda made official.
