### ISSUE TITLE
Exec with watch?

### ISSUE THREAD

**Issue by balping** [laravel/elixir#571]
Hi!

I'm glad that there's an exec function in elixir. My only problem is that it doesn't seem to work with `gulp  watch`

Example:

```
elixir(function(mix) {
	mix.browserify('main.js').exec('echo "foo" > /tmp/bar.txt');
});
```

When I run `gulp` the shell command is run.

However with `gulp watch` the command is nut executed.

I'm not if it's an elixir related issue, or not. If not, I'd be happy if someone helped me solving this problem. Maybe there's an event fired after a file is generated, if I could listen to that, that would be fine. Sorry I don't know gulp.

**Comment by JeffreyWay** [comment]
You can a file watcher as the second argument to mix.exec().

**Comment by balping** [comment]
Great, thank you!

I just make a note here in case someone has a similar problem.

It was not obvious to me, what 'file watcher' means. The second parameter that exec accepts is just a plain string. I was trying gulp.watch, gulp-watch package and others. I thought exec waits some kind of watcher object, but no. Just pass a string.
