### ISSUE TITLE
[...a, 2, 3] is not compiled by used version of buble

### ISSUE THREAD

**Issue by ikoolik** [laravel/elixir#572]
This type of code:
```
let a = [1, 2, 3];
let b = [...a, 4, 5];
```
Is ignored by `buble@^0.7.1`. It is only supported since `buble@^0.9`
We're bonded to the `buble@^0.7.1` because of `buble-loader` peer dependency.

One of the consequences is `gulp --production` failure, since `uglify` can't process such syntax.

I am going to create a PR with peer dependency update for `buble-loader` and then create a PR to update buble dependency here if you do not mind.

**Comment by ikoolik** [comment]
Have created a PR in `buble-loader`. (https://github.com/sairion/buble-loader/pull/4)

**Comment by JeffreyWay** [comment]
Excellent. Thanks!

**Comment by ikoolik** [comment]
Since the webpack related code was moved to the `laravel-elixir-webpack-official` repo, there is no need to change anything in `laravel/elixir`.

As a side note: `buble-loader@0.2.2` was released. It has a peer dependency of `buble@^0.12.0`, which plays nicely with 
```
"buble": "^0.12.3",
"buble-loader": "^0.2.1"
```
from `laravel-elixir-webpack-official` packaje.json file
