### ISSUE TITLE
Error: no writecb in Transform class at afterTransform

### ISSUE THREAD

**Issue by rossjcooper** [laravel/elixir#574]
All of a sudden I am now recieving the following error when I try to run `gulp` or `gulp watch` when a sass file is modified, it works fine for js compiling.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
    at afterTransform (project_path\node_modules\laravel-elixir\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:95:33)
    at Immediate.TransformState.afterTransform (project_path\node_modules\laravel-elixir\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at Immediate.immediate._onImmediate (timers.js:435:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

After a little digging around this error crops up for certain versions of `gulp-less` and `gulp-autoprefixer` but there seems to be no correct solution, I am using Node-v4.4.7 and I have tried `npm install`, `npm update` and `npm cache clean` with no success. I am guessing its a bad version of a depency?

**Comment by JeffreyWay** [comment]
Hmm, haven't seen this before. If you can give me a simple reproducible setup, I'll test it out and try to find out the problem.

**Comment by rossjcooper** [comment]
Here is my gulp.js file if that helps, I can;t send the project due to NDAs.

```
var elixir = require('laravel-elixir');

elixir(function(mix) {
    mix.sass(['screen.scss'], 'public/css/site.css');
    mix.sass(['console.scss'], 'public/css/console.css');
    mix.sass(['print.scss'], 'public/css/print.css');
    mix.copy('node_modules/signature_pad/signature_pad.min.js', 'public/js/signature_pad.min.js');
    mix.scriptsIn("resources/assets/js", 'public/js/site.js');
});
```

**Comment by rossjcooper** [comment]
Another thing I have noticed is whenever I install or update `laravel-elixir` I always get a dependency warning:

`npm WARN optional dep failed, continuing fsevents@1.0.12` 

I don't know if this is related but could be useful?

**Comment by rossjcooper** [comment]
I have just switched from using the ^3.0.0 release to ^4.0.0 after a complete uninstall and reinstall and all seems well now seems like I haven;t being my updates properly
