### ISSUE TITLE
Strange sass bug

### ISSUE THREAD

**Issue by tobia** [laravel/elixir#576]
I'm seeing a strange bug. The following SASS:

    .test {
        cursor: -webkit-grab;
        cursor: grab;
    }

is translated by Elixir into this:

    .test {
        cursor: grab; }

which is wrong, because I explicitly need the vendor prefix before the standard property, as a separate `cursor:` line, otherwise it doesn't work on Chrome.

The strange thing is that I'm unable to reproduce the problem with plain Gulp. Using the following gulpfile, which does not use Elixir:

    var gulp = require('gulp');
    var sass = require('gulp-sass');
  
    gulp.task('default', function () {
      return gulp.src('resources/assets/sass/*.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('public/css'));
    });

…I get the right translation:

    .test {
      cursor: -webkit-grab;
      cursor: grab; }

Which is why I'm posting the issue here on Elixir.

All tests done on a fresh installation of Laravel 5.2

**Comment by JeffreyWay** [comment]
You can change the autoprefixer settings for your project. See here:

https://github.com/laravel/elixir/blob/master/src/Config.js#L184

You'd do something like:

```
elixir.config.css.autoprefix.options.browsers = ['last 5 versions'];
```

**Comment by tobia** [comment]
Thanks @JeffreyWay. To be honest I didn't even realize there was an autoprefixer to begin with 😓

This seems to be a bug in the (otherwise excellent) http://caniuse.com database the autoprefixer is based on. In my case, I simply disabled the removing of hand-picked prefixes, which seems a sensible setting anyways.

    elixir.config.css.autoprefix.options.remove = false
