### ISSUE TITLE
Overwriting paths

### ISSUE THREAD

**Issue by REBELinBLUE** [laravel/elixir#577]
My app has both front end and back end JS (a socket server). So I have been separating the code into 2 seperate `package.json` files, one in the root folder and one in `resources/assets` I have put my `gulpfile.js` there as well.

In the file I have

```js
const path = require('path');

Elixir.config.assetsPath = __dirname;
Elixir.config.publicPath = path.join(__dirname, '../../public');
Elixir.config.appPath = path.join(__dirname, '../../app');
Elixir.config.viewPath = path.join(__dirname, '../views');
Elixir.config.versioning.buildFolder = path.join(__dirname, '../../public/build');
```

and then various commands such as

```js
  mix.styles([
    'app.css',
    'console.css',
  ], Elixir.config.publicPath + '/css/app.css', './css/')
```

and 

```js
  mix.scripts([
    'app.js',
    'console.js',
  ], Elixir.config.publicPath + '/js/app.js', './js/')
```

This all works fine, until I try to add `version`

```js
mix.version([
    'css/app.css',
    'js/app.js'
])
```

I get

```Error: ENOENT: no such file or directory, open '/Users/stephen/Workspace/deployer/public/Users/stephen/Workspace/deployer/public/build/css/app.css.map'```

Because in the destination column it shows `/Users/stephen/Workspace/deployer/public/Users/stephen/Workspace/deployer/public/build`

I have tried using a relative path for buildPath, i.e. `../../public/build` but then end up with

```Error: EACCES: permission denied, mkdir '/public' at Error (native)```

I also tried just `build` as it would appear that the buildPath is being appending to the publicPath which I guess makes sense but I still end up with

```Error: EACCES: permission denied, mkdir '/public' at Error (native)```

I am guessing it is to do with https://github.com/laravel/elixir/blob/master/src/tasks/VersionTask.js#L51 where it is forcing the path to be prefixed with ./ Is there any particular reason for this and is there any way around my issue? 

The other tasks don't seem to do it https://github.com/laravel/elixir/blob/master/src/tasks/CssTask.js#L23 https://github.com/laravel/elixir/blob/master/src/tasks/VersionTask.js#L51

Or am I just being really stupid and missing something obvious?

Thanks

**Comment by jerguslejko** [comment]
I've been trying to make your scenario work for an hour now, but no success here.

Although I do not know why the `version` task path is prefixed with `./`, I would recommend moving node server to its own repository. It would solve all these issues and it might be a "cleaner" solution after all. I have very similar setup _(separate laravel and node repositories)_ and it's been working out great so far. 

🌵

**Comment by REBELinBLUE** [comment]
OK well I am glad I'm not going mad. Thanks. Thinking of splitting the front end code out into a separate repository now as it has become quite a large react app

**Comment by REBELinBLUE** [comment]
um.....
