### ISSUE TITLE
Cannot add a watcher

### ISSUE THREAD

**Issue by shakee93** [laravel/elixir#578]
I am trying to add a watcher to the less task.

```
// gulpfile.js

var elixir = require('laravel-elixir');

elixir(function(mix) {

mix.less([
       'admin/app.less'
    ], 'public/assets/admin/css/core.css');

elixir.Task.find('less').watch(GlobalFiles);
}

```

It says

`TypeError: elixir.Task.find is not a function`

How am i supposed to add a watcher to less ?

**Comment by JeffreyWay** [comment]
You'd probably have to do something like:

```
Elixir.tasks.byName('less').forEach(function(task) {
    task.watch('path/to/watch');
});
```

Generally, you shouldn't need to do this, though. The Less task will automatically watch relevant files.
