### ISSUE TITLE
Allow NODE_ENV to be set by --production

### ISSUE THREAD

**Issue by TheShiftExchange** [laravel/elixir#579]
Hi Jeffrey,

When you run `gulp --production` you want the output to be exactly as expected for production.

But a common issue discussed in many issues such as https://github.com/JeffreyWay/laravel-elixir-vueify/issues/12, https://github.com/JeffreyWay/laravel-elixir-vueify/issues/10, https://github.com/JeffreyWay/laravel-elixir-vueify/issues/7 and mentioned in Vueify docs https://github.com/vuejs/vueify#building-for-production all show confusion with `NODE_ENV`.

A very simple solution is to have Elixir set `NODE_ENV` to `production` when the `--production` flag is used. This ensures that all modules all way through the build process correctly build for production.

I had a look through the /src - and I dont know the "best/right" place to configure/insert this code:

```
if (Elixir.inProduction) {
    process.env.NODE_ENV = 'production';
}
```

This only sets `NODE_ENV` for that single build process - it is not saved globally.

And the code above must run sometime _after_ this has already been set:

```
Elixir.inProduction = gutils.env.production || process.env.NODE_ENV === 'production';
```

I thought about this been part of the Elixir-Vueify code only - but it would possibly be an overall benefit to the entire Elixir process, to ensure all modules take advantage of a `--production` flag.

**Comment by evertramos** [comment]
I am still having an issue with "gulp --production".

Gulp Version:
[16:56:51] CLI version 3.9.1
[16:56:51] Local version 3.9.1

Laravel-Elixir-Vue-2 version:
`-- laravel-elixir-vue-2@0.2.0

Even after gulp --production we will still show vue devtools etc.

Thanks!

**Comment by quiquegarcia** [comment]
Following the workaround suggested in [this thread](https://laracasts.com/discuss/channels/elixir/disabling-vue-devtools-in-production) vueDevTools is disabled in production, but as @evertramos commented, this would be awesome if is handled automatically running ```gulp --production```
