### ISSUE TITLE
Elixir is not uglifying files with combine task using --production flag

### ISSUE THREAD

**Issue by uxweb** [laravel/elixir#580]
Hi @JeffreyWay

I really love Elixir, it is such a great asset management tool!

I'm using the combine task to combine some vanilla js files and works great, but when i `gulp --production`it does not uglify the resulting file.

I know that using the scripts task with the --production flag will uglify the resulting script, but for these files there is no need to call babel compiler, they're simple js.

Is there something i'm missing or any reason why combine is not uglifying them?

Thanks!

**Comment by JeffreyWay** [comment]
Which version of Laravel Elixir are you using?

**Comment by uxweb** [comment]
Thanks for answering @JeffreyWay 

I'm using 5.0.0 version :)

**Comment by JeffreyWay** [comment]
mix.combine() is only intended for concatenation. It won't uglify the code, because that ends up being incredibly costly, in terms of time. Especially when most libraries have already been optimized and minified.
