### ISSUE TITLE
Sass not compiled and version not run when running with `watch`

### ISSUE THREAD

**Issue by oldskool73** [laravel/elixir#582]
I seem to have the same issue as https://github.com/laravel/elixir/issues/556 , but changing node version doesn't solve it for me. With the gulp file

```
elixir(function(mix) {
	mix.sass('app.scss');
	mix.browserify('app.js');
	mix.version([
		'css/app.css',
		'js/app.js'
	]);
	mix.browserSync({
		proxy: 'api.cw.app'
	});
});
```

When I just run `gulp` it works fine, builds the sass and js and versions as expected. 

When I run `gulp watch` it doesn't run the sass task, so the version fails and I get a broken page from laravel because `File css/app.css not defined in asset manifest`. If I change the sass file while watch is running it compiles the sass, but still doesn't run the version so the page is still broken.

```
[17:42:19] Starting 'watch'...
[17:42:19] Starting 'browserify'...

Fetching Browserify Source Files...
   - resources/assets/js/app.js


Saving To...
   - public/js/app.js

[17:42:31] Finished 'browserify' after 12 s
[17:42:31] Finished 'watch' after 12 s
[BS] Proxying: http://api.cw.app
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.8:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.8:3001
 ------------------------------------
[BS] Watching files...
[17:42:35] 898 bytes written (3.74 seconds)
[17:42:35] gulp-notify: [Laravel Elixir] Browserify Compiled!
[17:42:46] Starting 'sass'...

Fetching Sass Source Files...
   - resources/assets/sass/app.scss


Saving To...
   - public/css/app.css

[17:43:00] Finished 'sass' after 14 s
[17:43:00] gulp-notify: [Laravel Elixir] Sass Compiled!
```

I've also tried chaining the mix calls, which doesn't seem to change anything, but it'd be nice if the instructions gave an example of how it's supposed to be used in a real world example... chained, multiple mix calls, or doesn't matter... because there's no mention of that right now so it's kind of a random guess.

**Comment by jerguslejko** [comment]
> "chained, multiple mix calls, or doesn't matter..."

**Does not matter.** As you can see here https://github.com/laravel/elixir/blob/master/src/bootstrap/EnableExtension.js#L16, `Elixir.mixins` is returned after each `mix.task()` call, and it's the same object that is passed to the `elixir()` function (https://github.com/laravel/elixir/blob/master/src/index.js#L20).

**Comment by laracasts** [comment]
@oldskool73 Which version of Elixir are you using?

**Comment by oldskool73** [comment]
@laracasts : to be honest, none any more, scrapped it for a custom webpack setup instead. Elixir just seems to be an extra layer getting in the way of using gulp (or webpack or whatever) directly, decided it wasn't worth fighting it. But when I was having the issue above I was using whatever comes with a fresh install of Laravel, composer had `"laravel-elixir": "^5.0.0"`

@jerguslejko : yeah cool, I guess my point is though that on the Laravel help page there's loads of demos of features but not one of them uses more than one mix, so there's  example of using it in a real situation to do more than one thing in a build. Just a simple 'you can of course chain all these features together to create complex build process like this... { example code }' might make things clearer for a newb.

**Comment by jerguslejko** [comment]
@oldskool73 latest docs do show it. (kinda https://laravel.com/docs/master/elixir#introduction).

But, yeah, I agree with you, maybe submit a PR to the docs? 👍
