### ISSUE TITLE
relative path in copy function

### ISSUE THREAD

**Issue by glukash** [laravel/elixir#583]
Starting from 6.0.0-5 version there is an issue with copy function.
Specially if you use relative paths.
When destination folder is higher in folder structure than gulpfile.js itself, copied files don't appear in specified folder.
For example:
gulpfile.js is inside /admin folder (/admin folder is in the same level as /app directory with its own node_modules)
when I do:
```javascript
mix.copy(
        './resources/assets/lib/font-awesome/fonts',
        '../public/assets/admin/fonts/fontawesome'
)
```
files appear in /admin folder but not in /public

I discovered that removing theese lines from GulpPaths.js:

```javascript
// If there's a dot in the src file path, the parser
// will think the user is referencing a file, rather
// than a directory. So we'll check for that.
try {
    if (path.indexOf('.') > -1 && _fs2.default.statSync(path).isDirectory()) {
        segments.extname = '';
        segments.dirname = segments.name;
        segments.basename = segments.extname.replace('.', '');
    }
} catch (e) {}
```

fixes everything and it works fine like in every erlier elixir versions

**Comment by glukash** [comment]
Another tests and I found out that if the destination folder doesn't exist copy is made correct.
But then, the second time, it doesn't overwrite files, it copies them to the wrong destination.

**Comment by tecbeast42** [comment]
+1
