### ISSUE TITLE
exec command stopped working

### ISSUE THREAD

**Issue by legshooter** [laravel/elixir#587]
Hey,

Not sure what happened, but the same `mix.exec('gulp')` command I've been always running stopped working with the following error:

```javascript
Triggering Command...
gulp
/usr/bin/bash: /s: No such file or directory
[14:19:24] 'exec' errored after 106 ms
[14:19:24] Error in plugin 'gulp-shell'
Message:
    Command `gulp` failed with exit code 127
[14:19:24] Error in plugin 'run-sequence'
Message:
    An error occured in task 'exec'.
```

I can use alternative ways like:
```javascript
var shell = require('gulp-shell')
// ...
shell('gulp');
```
or:
```javascript
var exec = require('child_process').exec
// ...
exec('gulp', function (err, stdout, stderr) {
    console.log(stdout);
    console.log(stderr);
    console.log(err);
});
```
But then I get no console output for that command.

Thanks.

**Comment by laracasts** [comment]
Can you tell me which version of Laravel Elixir you're using? And also paste in the relevant portion of your Gulpfile.

**Comment by legshooter** [comment]
Sure, I'm using `v5.0.0`, and the relevant portion, is, well:
```javascript
mix.exec('gulp');
```
:flushed: 

I'm on Windows 10, node `v4.4.7`, npm `v3.10.5`, if that helps.

**Comment by laracasts** [comment]
Won't that just repeat your Gulp build indefinitely?

**Comment by legshooter** [comment]
In case you're wondering whether that would repeat my Gulp build indefinitely (:grin:), this is ran from a different gulpfile.

In case you're wondering why, it's my primitive way of separating my code from the vendor's (bower_components), so I only run the regular gulp file when I'm modifying my own code, and when a vendor updates, I run the other file, which mixes all the vendor stuff, and in the end, should run the regular gulp file (the exec that stopped working).

The reason I chose to separate stuff I rarely run to a different file to begin with, was the fact that it saves me a little time each time it runs, and for some reason otherwise my PhpStorm would considerably slow down, which could be it's own fault (I'm running MinGW from within it's terminal)).

Hope that that clears it up.

**Comment by JeffreyWay** [comment]
I haven't been able to reproduce this. mix.exec() seems to work properly.

**Comment by legshooter** [comment]
I haven't been able to fix this :laughing: 
v6 is around the corner so I hope it'll be magically fixed with the upgrade.

**Comment by legshooter** [comment]
Nothing wrong with elixir, it was `node-sass` misbehaving because I had `ComSpec` (Windows env var) point to `MinGW` instead of `cmd.exe`.
