### ISSUE TITLE
Notification message is empty in some environments.

### ISSUE THREAD

**Issue by iakio** [laravel/elixir#59]
From:
https://laracasts.com/discuss/channels/general-discussion/gulp-notify-error-in-notifier-error-in-plugin-gulp-notify-not-found-notify-send

In your video, 
![notify-mac](https://cloud.githubusercontent.com/assets/17942/6618881/99f89aa6-c909-11e4-91c1-02e303cb73fa.png)

But, in my environment (Windows 8.1, WindowsToaster),

![notify-win](https://cloud.githubusercontent.com/assets/17942/6618899/c7be21ae-c909-11e4-90c9-daaf3addf01d.png)

"Your PHPUnit tests passed!" is specified as `subtitle`, but that seems to only be available for NotificationCenter.

https://github.com/mikaelbr/node-notifier

**Comment by webcrazy** [comment]
On my ubuntu ... I got like this.
![elixir_error](https://cloud.githubusercontent.com/assets/5352704/6649929/bf344a62-ca27-11e4-9c9c-82078e7cf902.png)

**Comment by zachleigh** [comment]
Same thing on Kubuntu 14.10.  I get a Laravel Elixir notification that is totally empty. notify-send works fine, but messages from Gulp/Laravel do not work.

**Comment by xewl** [comment]
I would even like to disable gulp-notify, as mine returns "Error in plugin 'gulp-notify' not found: notify-send" anyway.

**Comment by Skyrpex** [comment]
I can reproduce the problem on Ubuntu 14.10 too.

**Comment by JeffreyWay** [comment]
Can someone submit a PR to fix this?

**Comment by iakio** [comment]
I'll try it.

**Comment by JeffreyWay** [comment]
Okay, #77 should have fixed this. Closing.

**Comment by joecwallace** [comment]
This seems to have broken notifications for my setup.

I have [vagrant-notify](https://github.com/fgrehm/vagrant-notify) plugin installed in Homestead and have a bash script (contents below) to pass notifications along to [terminal-notifier](https://github.com/alloy/terminal-notifier).

/usr/local/bin/notify-send:
```
/path/to/terminal-notifier -appIcon "$2" -title "$4" -message "$5"
```

Adding `echo $@` to the above bash scripts shows that the "subtitle" text isn't being passed in at all. When I edit `ingredients/commands/Notification.js` to use `notify({ ..., message: subtitle, ... })`, it works.

Is there a downside to using `notify()` with `{ ..., subtitle: subtitle, message: subtitle, ... }`? I assume this would cause something like:
# Laravel Elixir
## Subtitle
### Subtitle

on certain setups, but I don't know...

**Comment by iakio** [comment]
@joecwallace I put `notify-send` script like this:
```
(
 echo 1 $1
 echo 2 $2
 echo 3 $3
 echo 4 $4
 echo 5 $5
) >& 2
```
then, run gulp
```
[03:40:22] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
1 Laravel Elixir
2 Less Compiled!
3 --icon
4 /home/vagrant/src/gulp-notify/node_modules/laravel-elixir/ingredients/commands/../../icons/laravel.png
5
```
So, it seems correct setup is:
```
/path/to/terminal-notifier -appIcon "$4" -title "$1" -message "$2"
```
I don't understand why it works by `notify({ ..., message: subtitle, ... })`.
Anyway, I think the best to do that is parse arguments like
`https://github.com/fgrehm/vagrant-notify/blob/master/files/notify-send.erb`.

**Comment by joecwallace** [comment]
@iakio Here's what I get:

```
1 -i
2 /long/path/to/icons-laravel.png
3 --
4 Laravel Elixir
5 
```

laravel-elixir version: 0.14.0
gulp-notify version: 1.8.0

**Comment by ipsod** [comment]
I've updated and I'm still getting an empty message.  I can run  <notify-send "test" "message"> and it works as expected, but running gulp gives an empty message.

**Comment by ipsod** [comment]
I just updated both Laravel and Homestead, and I'm still having this issue.
