### ISSUE TITLE
JS sourcemap not created with successful webpack run

### ISSUE THREAD

**Issue by ejdelmonico** [laravel/elixir#592]
var elixir = require('laravel-elixir');

require('laravel-elixir-vue');

elixir(function(mix) {
    'use strict';
    mix.sass('app.scss')
       .webpack('app.js');
});

gulp --production returns sass and webpack compiled successfully. However, the css source map is properly located in the /public/css folder. The app.js file is compiled properly and located in the /public/js folder but the source map is missing (both the actual file and the reference in app.css) even though it is "recorded" as complete.

**Comment by ejdelmonico** [comment]
included webpack.config.js in project root with the following:

module.exports =
{
  devtool: 'source-map'
};

Now, produces js sourcemaps.

**Comment by ksdev-pl** [comment]
Thanks for this, now the js source in Chrome developer tools is readable.

**Comment by aligajani** [comment]
@ksdev-pl  True.
