### ISSUE TITLE
Sass does not support the third argument - base directory

### ISSUE THREAD

**Issue by randohinn** [laravel/elixir#593]
I just noticed that `sass`, unlike others, does not support the base directory argument - the 3rd one. Eg. this `mix.sass(["main.scss"],"public/css/foliage.css","scss");` goes to town trying to build `resources\assets\sass\main.scss`, which obviously doesn't exist, since I'm trying to specify a custom base directory.. This should exist.

**Comment by JeffreyWay** [comment]
Closing - as we have a PR for this.
