### ISSUE TITLE
Support Spread Operator

### ISSUE THREAD

**Issue by minhchu** [laravel/elixir#595]
How can I configure the browserify task to transform spread operator according to this answer: http://stackoverflow.com/a/33745466/6272893
Thanks

**Comment by StefanoMagrassi** [comment]
@minhchu it's not a "browserify" issue, but a "babel" one.

You need the [transform-object-rest-spread](http://babeljs.io/docs/plugins/transform-object-rest-spread/) Babel's plugin and to properly configure it in your [`.babelrc`](http://babeljs.io/docs/usage/babelrc/) file:

```json
{
  "presets": ["es2015"],
  "plugins": ["transform-object-rest-spread"]
}
```
The browserify task in Elixir is [already shipped with babelify transformer](https://laravel.com/docs/5.2/elixir#browserify) and with this stack it's always preferable to handle Babel configuration with a `.babelrc` file.
