### ISSUE TITLE
Problem with mix.version

### ISSUE THREAD

**Issue by braicauc** [laravel/elixir#596]
So... I have this things on my gulpfile.js : 

elixir(function(mix) {
    mix.styles([
        'bootstrap.min.css',
        'font-awesome.css',
        'style.css',
        'easy-autocomplete.css',
        'lightgreen.4.3.1.css',
        'styles.4.3.1.css'
    ],'public/css/all.css');
    mix.version('public/css/all.css');
});

elixir(function(mix) {
    mix.scripts([
        'jquery.1.11.3.js',
        'bootstrap.3.3.5.js',
        'easy-autocomplete.js'
    ],'public/js/all_new.js');
});

I want to make a version of javascript files too but does not work ... If i comment the line mix.version('public/css/all.css'); and put another one on js files it works ... 

If I put both mix.version('public/css/all.css'); and mix.version('public/js/all.js'); only the first file is created on the builds directory.

Whay ?

**Comment by tomcastleman** [comment]
I am not sure why have you got 2 calls to elixir. Also both your JS and CSS should be passed to version. So this should work:

```
elixir(function(mix) {
    mix.styles([
        'bootstrap.min.css',
        'font-awesome.css',
        'style.css',
        'easy-autocomplete.css',
        'lightgreen.4.3.1.css',
        'styles.4.3.1.css'
    ],'public/css/all.css');

    mix.scripts([
        'jquery.1.11.3.js',
        'bootstrap.3.3.5.js',
        'easy-autocomplete.js'
    ],'public/js/all_new.js');

    // takes paths relative to elixir.config.publicPath
    mix.version([
        'css/all.css',
        'js/all_new.js'
    ]);
});
```

Hope this helps

**Comment by braicauc** [comment]
Tank you Tom, your solusion works.
