### ISSUE TITLE
Gulp 6.0.0-9 ignores settings from elixir.json

### ISSUE THREAD

**Issue by ddctd143** [laravel/elixir#599]
Previously I had `6.0.0-5` version, which worked with my `elixir.json` config. When I'm printing console.log(elixir.config) into console, I see my settings, with 9 version, I see only default elixir settings, which are different from mine. Only thing that has changed is version, from beta 5 to beta 9 in my installation.
Is there something changed in recent versions about `elixir.json` config ?

**Comment by JeffreyWay** [comment]
Yes. Elixir 6, once it's released officially, won't read from elixir.json files anymore.

**Comment by ddctd143** [comment]
@JeffreyWay how can I extend config ? Because I had my custom variables also in there, which I have read from there, at example, list of js files from bower_components. Also I had custom output paths for js and css.

**Comment by zawilliams** [comment]
Also curious about extending the config.

**Comment by melloc01** [comment]
@JeffreyWay any reason for this? I'm really curious about it.
Seems like we're not supposed to use elixir without Laravel anymore?
I used to use it in some front-end only projects.

**Comment by JeffreyWay** [comment]
Just extend the config from your Gulpfile. `elixir.config.foo = 'bar'`

**Comment by melloc01** [comment]
Yep, that's what I did - was just trying to understand the reason.
Not a big prob. thx = ]

**Comment by dennschu** [comment]
instead of migrating all config properties from `elixir.json` to your `gulpfile.js` by hand you could try to merge the json config into elixir's like the following example:

```js
let fs = require( 'fs' );
let _ = require( 'lodash' );

let jsonConfigPath = __dirname + '/elixir.json';
if( fs.existsSync( jsonConfigPath ) ) {
  let elixirJsonConfig = JSON.parse( fs.readFileSync( jsonConfigPath ) );
  elixir.config = _.merge( elixir.config, elixirJsonConfig );
}
```

*(assumes that lodash and fs are present)*
