### ISSUE TITLE
Error: watch ENOSPC

### ISSUE THREAD

**Issue by basith374** [laravel/elixir#605]
Hi i'm getting this error while running gulp watch. im using **vueify**. why is this happening. it was working fine all these days and this came in today.

`$ gulp watch`
`[12:56:01] Using gulpfile ~/Documents/web_projects/next-home/gulpfile.js`
`[12:56:01] Starting 'watch'...`
`[12:56:01] Starting 'browserify'...`
`Fetching Browserify Source Files...`
`   - resources/assets/js/app.js`
`Saving To...`
`   - public/js/app.js`
`[12:56:02] Finished 'browserify' after 707 ms`
`[12:56:02] 'watch' errored after 722 ms`
`[12:56:02] Error: watch /home/bazi/Documents/web_projects/next-home/resources/assets/less/ ENOSPC`
`    at exports._errnoException (util.js:893:11)`
`    at FSWatcher.start (fs.js:1313:19)`
`    at Object.fs.watch (fs.js:1341:11)`
`    at Gaze._watchDir (/home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/gaze.js:289:30)`
`    at /home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/gaze.js:358:10`
`    at iterate (/home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/helper.js:52:5)`
`    at Object.forEachSeries (/home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/helper.js:66:3)`
`    at Gaze._initWatched (/home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/gaze.js:354:10)`
`    at Gaze.add (/home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/gaze.js:177:8)`
`    at new Gaze (/home/bazi/Documents/web_projects/next-home/node_modules/gaze/lib/gaze.js:74:10)`
`events.js:154`
`      throw er; // Unhandled 'error' event`
`      ^`
`Error: watch /home/bazi/Documents/web_projects/next-home/package.json ENOSPC`
`    at exports._errnoException (util.js:893:11)`
`    at FSWatcher.start (fs.js:1313:19)`
`    at Object.fs.watch (fs.js:1341:11)`
`    at createFsWatchInstance (/home/bazi/Documents/web_projects/next-home/node_modules/chokidar/lib/nodefs-handler.js:37:15)`
`    at setFsWatchListener (/home/bazi/Documents/web_projects/next-home/node_modules/chokidar/lib/nodefs-handler.js:80:15)`
`    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/bazi/Documents/web_projects/next-home/node_modules/chokidar/lib/nodefs-handler.js:228:14)`
`    at FSWatcher.NodeFsHandler._handleFile (/home/bazi/Documents/web_projects/next-home/node_modules/chokidar/lib/nodefs-handler.js:255:21)`
`    at FSWatcher.<anonymous> (/home/bazi/Documents/web_projects/next-home/node_modules/chokidar/lib/nodefs-handler.js:473:21)`
`    at FSReqWrap.oncomplete (fs.js:82:15)`

this is my gulpfile.js

`var elixir = require('laravel-elixir');
require('laravel-elixir-vueify');
elixir(function(mix) {
    mix.less('app.less');
    mix.browserify('app.js');
});`

**Comment by gergelypap** [comment]
This is a Linux/UNIX related issue, or more like a "default behavior" on these systems. Nothing to do with Elixir here.

This one beast of a command will fix it:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

As referenced in 217#issuecomment-61039024
Credit goes to [this StackOverflow answer](http://stackoverflow.com/a/17437601/1845279).

**Comment by JeffreyWay** [comment]
Great. Thanks!

**Comment by jimbarrett** [comment]
Brilliant. Thanks @gergelypap
