### ISSUE TITLE
Minification produces different versions

### ISSUE THREAD

**Issue by codedge** [laravel/elixir#606]
Hello!
When running `gulp --production` across different system, me and a colleague of mine get different results.

This is the `gulpfile.js` that we use
```js
var elixir = require('laravel-elixir');

/**
 * Set Elixir Source Maps
 *
 * @type {boolean}
 */
elixir.config.sourcemaps = true;

/**
 * Configuring assets path.
 * Explicitly setting it to empty, as we're not using Laravels resources/assets folder
 *
 * @type {string}
 */
elixir.config.assetsPath = '';

/**
 * Configuring Javascript assets path.
 * Explicitly setting it to empty, as we're not using Laravels resources/assets/js folder
 *
 * @type {string}
 */
elixir.config.js.folder = '';

/**
 * Configuring CSS assets path.
 * Explicitly setting it to empty, as we're not using Laravels resources/assets/css folder
 *
 * @type {string}
 */
elixir.config.css.folder = '';

/**
 * Remove all CSS comments
 *
 * @type {{discardComments: {removeAll: boolean}}}
 */
elixir.config.css.cssnano.pluginOptions = {
    discardComments: {
        removeAll: true
    }
};

/**
 * Directory for bower source files.
 * If changing this, please also see .bowerrc
 *
 * @type {string}
 */
var bowerDir = 'public/vendor';

elixir(function(mix) {

    /**
     * JS configuration
     */
    mix.scripts(['resources/assets/js/Chart.js'], 'public/js/Chart.min.js');
    
});

```

The difference after minifiying the `Chart.js` ([download here](https://github.com/invoiceninja/invoiceninja/blob/develop/resources/assets/js/Chart.js)) file is outlined in this screenshot. You can also checkout the `develop` branch from [Invoice Ninja](https://github.com/invoiceninja/invoiceninja).

<img width="868" alt="2016-08-05_11-33-35" src="https://cloud.githubusercontent.com/assets/4409904/17508349/cec6aea2-5e14-11e6-8fd4-0017267f5bbf.png">

The Gulp version used is 3.9.1, Laravel Elixir 5.0.0.

Does anybody have a clue why `\t` is replaced with `    ` on some systems?

Cheers!

**Comment by kohenkatz** [comment]
What OS(es)? What NodeJS version(s)?

**Comment by JeffreyWay** [comment]
I really have no idea. Maybe your coworker has a different version of some dependency installed. Either way, I'm not sure that there's anything I can do about this.
