### ISSUE TITLE
Getting Gulp watch to only compile "changed" SASS files?

### ISSUE THREAD

**Issue by 7ammer** [laravel/elixir#607]
I have this in my gulp file:
```
mix.sass('main.scss')
        .sass('base.scss')
```
When I run `gulp watch` each time I change one of the files, BOTH files get compiled. Shouldn't only the changed file get compiled?

In gulp you would do it like this:

```
gulp.task('watch:scss', function() {
    gulp.watch(["mypath/main.scss", "mypath/base.scss"], function(event){
        return gulp.src(event.path)
            .pipe(sass())
            .pipe(gulp.dest("public/assets/css/"));
    });
});
```

Note that the `event.path` variable contains the "changed" file only.

Having the ability to do this would cut down gulp task times when there are multiple sass files to compile.

**Comment by JeffreyWay** [comment]
Right now, Elixir watches any Sass file in your main directory for changes. So you have two sass() handlers listening for changes. `main.scss` could depend on `base.scss`, at which point it would need to recompile if `base.scss` changes. So it can get a little tricky.

Generally, we recommend that you only call `mix.sass()` once. That or pass an array to the method.
