### ISSUE TITLE
[6.0.0-9] Unexpected looping when using the watch task.

### ISSUE THREAD

**Issue by Jono20201** [laravel/elixir#608]
We recently updated Elixir to the beta version as we want to take advantage of Webpack + Vue.js. I have noticed some odd behaviour when using the watch task with Less and Coffee. However, when running the default task Elixir behaves as expected.

Please see the following basic Elixir code:
```js
elixir(function(mix) {
    mix
      .less('client-basic.less')
      .less('client-filemanager.less')
      .version([
        'css/client-basic.css',
        'css/client-filemanager.css'
      ]);
});
```

When running the default task, we see the following output:
![image](https://cloud.githubusercontent.com/assets/2374192/17592604/db8c0f02-5fda-11e6-878c-da85992f5ad1.png)

However, when we run using the watch task we see duplicated Summery text:
![image](https://cloud.githubusercontent.com/assets/2374192/17592556/b09d724a-5fda-11e6-9185-7e0f4241729e.png)

I believe this is the root cause the another issue I encountered this morning. We have a fairly complex Elixir script due to the fact we don't want to concatenate all our files into one large file, but rather include only what is needed on specific pages.

Our full Gulpfile.js: https://gist.github.com/Jono20201/6bd83230b2a9f34fd394b69c5a4ff9f7

When we run this using the default task all is built successfully. However, when running using the watch task the less 'Summery' is duplicated 15 times, and the Coffee summery duplicated many more times. We then see the following error repeated 20 odd times:

`(node:9408) Warning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit`

I think these are related but not totally sure. I am trying to get my head around Elixir's code base to further debug the issue.

**Comment by JeffreyWay** [comment]
This was fixed in a recent release, I believe. Just haven't tagged it yet.

**Comment by Jono20201** [comment]
@JeffreyWay Have you seen the issue with `(node:9408) Warning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit` before? I'll try with an up-to-date non-tagged version on Monday.
