### ISSUE TITLE
Unable to use Elixir 6 with VueJS 2 and Webpack

### ISSUE THREAD

**Issue by micheleivani** [laravel/elixir#612]
I'd like to try Laravel 5.3 and VueJS 2 RC3. Steps I made:

1. Run in my terminal `composer create-project laravel/laravel laravel53 dev-develop` .
2. Edit the vuejs version inside `package.json` file: `"vue": "^2.0.0-rc.3",`
3. Run `npm install`
4. Edit the `welcome.blade.php` file by adding following code before closing body tag
```
...
        <example></example>
        <script src="js/app.js"></script>
    </body>
...
```

Previewing the result in my chrome browser I got the following errors

```
[Vue warn]: Failed to mount component: template or render function not defined. (found in root instance)

Uncaught TypeError: Cannot read property 'hasAttribute' of null
```

<img width="926" alt="schermata 2016-08-21 alle 13 54 06" src="https://cloud.githubusercontent.com/assets/790928/17836978/befad340-67a6-11e6-8f32-12d6900097a7.png">

So I just made basic operations with no particular modifications.

Can you help me?

**Comment by JeffreyWay** [comment]
Not sure - but Vue 2 isn't out yet. I think Evan may make a plugin to help with this.

**Comment by Francismori7** [comment]
Hey @JeffreyWay, you may want to reopen this, as this still occurs with Vue 2.0.1.

**Comment by neindk** [comment]
I am also suffering from same issue with vue 2.0.1 while my component works fine with vue 1.x.
I followed migration guide, but no luck still.

**Comment by JellyBool** [comment]
@Francismori7 @neindk 

Just use Evan project  https://github.com/vuejs/laravel-elixir-vue-2

make it work with vuejs 2.0.1 and laravel 5.3 

```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.2"
  }
}
```

Once you created your laravel project, remember  to change `"vue": "^1.0.26"` to `"vue": "^2.0.1"` and also change `"laravel-elixir-vue": "^0.1.4",` to ` "vue": "^2.0.1"` which comes with laravel out of the box.
