### ISSUE TITLE
CSS3 transformations 

### ISSUE THREAD

**Issue by iarsovska** [laravel/elixir#614]
After i minimize and combine the css files, i happen to loose all specified css3 transformations for different browsers. For example, i loose all -moz-transform and  -o-transform css3 options and also for example if i have transform:translate(0 , 50%) it minifies it as transformY(50%) which is not the same.

**Comment by TobyRyuk** [comment]
I think that has to do with the autoprefixer processing the css, you could try doing an ugly fix by adding `/* autoprefixer: off */` on the line above the transform attribute.

Regarding the prefixed transform attributes, try overriding Elixirs config for autoprefixer. Elixirs config: [Config.js](https://github.com/laravel/elixir/blob/master/src/Config.js) and then read about autoprefixers browser support config, [autoprefixer](https://github.com/postcss/autoprefixer).

**Comment by iarsovska** [comment]
Thanks!
