### ISSUE TITLE
Does web-pack serve as an alternative to .scripts() ?

### ISSUE THREAD

**Issue by aligajani** [laravel/elixir#625]

**Comment by JeffreyWay** [comment]
No. .scripts() for combining arbitrary JavaScript files.

**Comment by aligajani** [comment]
@JeffreyWay  Sorry, I am a little lost here. Can you give an example of what does webpack do first which scripts finishes off at the end. Does a webpack bundled file also then get included in the scripts() ?

**Comment by JeffreyWay** [comment]
No. mix.scripts() is equivalent to manually concatenating a bunch of JavaScript files into one. mix.webpack() is for bundling up ES2015 code that is organized into various modules.

**Comment by aligajani** [comment]
Alright, here's the tricky part.I am running this webpack() and scripts() one after another. My `webpack()` contains my application files, `scripts()` contains all other vendor libraries. The problem is that since it runs in parallel, I get errors like 'File is not found, or files not found if I am using `**/*.js`. How do I approach this ?

**Comment by JeffreyWay** [comment]
I'd need to see your Gulpfile. They don't run in parallel.

**Comment by aligajani** [comment]
@JeffreyWay  here it is

```
const elixir = require('laravel-elixir');
const compass = require('laravel-elixir-sass-compass');
const saveeo = "public/js/app/**/*.js";

require('./elixir-extensions/template-versioner.js');
var vendor_libraries = require('./vendor.libraries.config.json');
vendor_libraries.javascript.push(saveeo);

elixir(function (mix) {
    mix

        .compass(["app.scss"], "public/css",
            {
                style: "compressed",
                sass: "./resources/assets/sass",
                sourcemap: true
            })
        .templateVersioner()

        .styles(vendor_libraries.stylesheets,
            'public/css/plain.css')

        .scripts(vendor_libraries.javascript,
            'public/js/app.js', './')

        .styles(['../../../public/css/app.css',
            '../../../public/css/plain.css' ],
            'public/css/bundle.css')

        .version(['public/css/bundle.css',
            'public/js/app.js'
        ])
});
```
