### ISSUE TITLE
scripts is not running correct

### ISSUE THREAD

**Issue by ultimateBusiness** [laravel/elixir#64]
I have the following config:

    elixir(function (mix) {

    mix.sass('app.scss');

    mix.copy('bower_components/jquery/dist/jquery.js', 'resources/assets/js/vendor/jquery.js');
    mix.copy('bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js', 'resources/assets/js/vendor/bootstrap.js');

    mix.scripts([
        'vendor/bootstrap.js',
        'vendor/jquery.js',
        'app.js'
    ]);

    mix.copy('bower_components/bootstrap-sass-official/assets/fonts/bootstrap', 'public/fonts');
    mix.copy('bower_components/fontawesome/fonts', 'public/fonts');

    mix.version('public/css/app.css');

    });

and my ressource-folder look's like this:

![bildschirmfoto 2015-03-14 um 19 27 45](https://cloud.githubusercontent.com/assets/1951575/6652943/566b4f86-ca80-11e4-8fc1-2a70fad7c6e7.png)

But when I run gulp - all things will build correctly only with the scripts-tag nothing happens.

**Comment by ultimateBusiness** [comment]
v0.13.1 from elixir was installed

**Comment by laracasts** [comment]
The default JS directory for Elixir is `resources/js`. You have yours in `resources/assets/js`. Either change your directory structure, or override the base directory using the third argument to `mix.scripts()`, like so:

```
mix.scripts([
    'vendor/bootstrap.js',
    'vendor/jquery.js',
    'app.js'
], null, './resources/assets/js');
```
