### ISSUE TITLE
Elixir.json optional configuration seems not to be working

### ISSUE THREAD

**Issue by emahuni** [laravel/elixir#648]
I don't understand why the elixir.json file is not being parsed:

elixir.json
```

{
	"browserSync": {
	  "proxy": "buck.dev",
	  "reloadOnRestart": true,
	  "notify": false
	},

  "css": {
	"outputFolder": "stylesheets"
  }
}

```

seems to do nothing at all.

**Comment by laracasts** [comment]
More information please. Which version of Laravel Elixir do you have installed?

**Comment by edbentinck** [comment]
I have the same issue. `"laravel-elixir": "^6.0.0-11"`

**Comment by shaneparsons** [comment]
I'm also having an issue that may be related. In my gulpfile, trying to override `notify:false` for browsersync isn't working.

`"laravel-elixir": "^6.0.0-11"`

**Comment by JeffreyWay** [comment]
Elixir 6 removes the elixir.json file. Stick with v5 or below if you still need to use it.

**Comment by shaneparsons** [comment]
> Elixir 6 removes the elixir.json file. Stick with v5 or below if you still need to use it.

Would that have anything to do with my issue?

**Comment by JeffreyWay** [comment]
I doubt it, if you're passing the Browsersync from your Gulpfile and not an elixir.json file.

**Comment by emahuni** [comment]
Ok. But why was it removed and what options or methods were dimmed better?

**Comment by emahuni** [comment]
Ok. But why was it removed and what options or methods were dimmed better?

**Comment by PMK** [comment]
I had the same problem... You said on a lot of channels that there where no big updates, but this one is huge!

See this package to fix this "issue": https://www.npmjs.com/package/laravel-elixir-config

**Comment by JeffreyWay** [comment]
It's not huge. Set the config in your Gulpfile instead.
