### ISSUE TITLE
Watch and minify at the same time.

### ISSUE THREAD

**Issue by huyle2607** [laravel/elixir#656]
Please help me with this one.
I'm really new to Elixir. Currently I have a big problem and I don't know how to solve it.
Is there anyway I can watch and minify CSS, JS,... at the same time. For example when you save your file, your files will be watched and minified at the same time instead of using 'gulp --production'.

Thank you very much!

**Comment by terrylow** [comment]
@huyle2607 you should be able to do that with gulp watch --production

**Comment by huyle2607** [comment]
@terrylow  Thank you very much! I just happened notice that too :)
