### ISSUE TITLE
Cannot read property 'mergeConfig' of undefined

### ISSUE THREAD

**Issue by kadnan** [laravel/elixir#657]
On Installing VueJS I am getting following:

```
Me-MBP:simpleb2b AdnanAhmad$ gulp build
/Applications/MAMP/htdocs//myProject//node_modules/laravel-elixir-vue/main.js:4
    Elixir.webpack.mergeConfig({
                  ^

TypeError: Cannot read property 'mergeConfig' of undefined
    at /Applications/MAMP/htdocs//myProject/node_modules/laravel-elixir-vue/main.js:4:19
    at /Applications/MAMP/htdocs//myProject//node_modules/laravel-elixir/dist/index.js:29:16
    at Array.forEach (native)
    at global.Elixir (/Applications/MAMP/htdocs//myProject//node_modules/laravel-elixir/dist/index.js:28:24)
    at Object.<anonymous> (/Applications/MAMP/htdocs//myProject//gulpfile.js:16:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by JeffreyWay** [comment]
Paste in your package.json file. I assume you have an old version of Elixir installed.

**Comment by kadnan** [comment]
```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^1.0.26",
    "vue-resource": "^0.9.3"
  }
}
```

**Comment by JenPage** [comment]
I had the same exact error. Here's what I did.
yum update npm
run gulp again you might get this error: 'Run `npm rebuild node-sass` to build the binding for your current environment.'
cd /
npm rebuild node-sass
cd laravel 
gulp

**Comment by zachleigh** [comment]
@kadnan Any solution here? Ive got the same problem.

**Comment by kadnan** [comment]
I am not using webpack anymore

**Comment by zachleigh** [comment]
Thanks. I moved back to browserify and its working fine.

**Comment by miladnit** [comment]
same error

**Comment by vgutnar** [comment]
I get the same error. Developing on Win 8.1/ Laravel 5.3
Here is my package.json file:
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^1.0.26",
    "vue-resource": "^0.9.3"
  }
}

**Comment by vgutnar** [comment]
I do get a lot of red on npm install:
![image](https://cloud.githubusercontent.com/assets/22861346/19419287/544762f2-9389-11e6-8fad-8cc9cb929027.png)

**Comment by leo-yi** [comment]
npm install --no-bin-links

can fix this

**Comment by ctrlaltdylan** [comment]
@leo-yi 's solution worked for me - my package.json:

```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-14",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.16.2",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3"
  },
  "dependencies": {
    "ckeditor": "^4.5.11",
    "laravel-elixir-vue-2": "^0.2.0",
    "webpack": "^1.13.3",
    "webpack-dev-server": "^1.16.2"
  }
}
```

**Comment by kadnan** [comment]
Actually I updated my `node` installation first and when I installed another setup of Laravel 5.3 and ran `npm install` then all went fine. Just update your `node/npm` and it should work.
