### ISSUE TITLE
gulp -- production with arrow function

### ISSUE THREAD

**Issue by Valonix** [laravel/elixir#658]
Hi, i have problem when i try gulp production because i have arrow function in my js files.
I tried use combine() instead scripts() and then webpack() but combine doesn work.
Can you help me and tell me how i can fix this problem?

` elixir(function(mix) {
 .scripts(
            [
                'app/app.js',
                'app/app.config.js',
                'app/core/core.module.js',

                'app/core/category/category.module.js',
                'app/core/category/category.service.js',

                'app/core/product/product.module.js',
                'app/core/product/product.service.js',

                'app/core/cart/cart.module.js',
                'app/core/cart/cart.service.js',
                'app/cart/cart.directive.js',
                'app/cart/cart.component.js',

                'app/home-page/home-page.module.js',
                'app/home-page/home-page.component.js',

                'app/category-detail/category-detail.module.js',
                'app/category-detail/category-detail.component.js',

                'app/category-list/category-list.module.js',
                'app/category-list/category-list.component.js',

                'app/category-page/category-page.module.js',
                'app/category-page/category-page.component.js',

                'app/product-detail/product-detail.module.js',
                'app/product-detail/product-detail.component.js',
                'app/product-detail/app.animations.js',

                'app/product-list/product-list.module.js',
                'app/product-list/product-list.component.js',

                'app/nav/nav.module.js',
                'app/nav/nav.component.js',

                'app/core/pagination/pagination.module.js',
                'app/core/pagination/pagination.service.js',
                'app/pagination/pagination.component.js',

            ],  'public/js/app.js'
        )
         .rollup(
            './public/js/app.js',
             './public/dist/js'
         );
});`

**Comment by JeffreyWay** [comment]
`mix.scripts()` and `mix.combine()` don't compile ES2015 down. For that you should use `mix.webpack()` or `mix.rollup()`.

**Comment by Valonix** [comment]
But I a have a lot of files, can I put in weboqck array?
