### ISSUE TITLE
How to use vuejs 2.0 with elixir ?

### ISSUE THREAD

**Issue by mattfanz** [laravel/elixir#659]

**Comment by jhkueh** [comment]
@mattfanz I think, I may have found the solution from [https://github.com/vuejs/laravel-elixir-vue-2](https://github.com/vuejs/laravel-elixir-vue-2):

Step 1: Install
------------------

`npm install laravel-elixir-vue-2 --save-dev`

Step 2: Gulpfile.js
------------------

```
var elixir = require('laravel-elixir')

require('laravel-elixir-vue-2')

elixir(function(mix) {
  mix.webpack('app.js'); // resources/assets/js/app.js
})
```

**Comment by keevitaja** [comment]
@jhkueh do i just remove the old vue from `package.json` and install latest?

**Comment by jhkueh** [comment]
@keevitaja yes, make sure that all your other vue tools (vue-resource, vue-router etc) are updated as well.

Here's a snippet of my `package.json` file.

```js
{
  ...
  },
  "devDependencies": {
    ...
    "laravel-elixir-vue-2": "^0.2.0",
    "vue": "^2.0.0",
    "vue-loader": "^9.5.0",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.0",
    ...
}
```

And, update your `Gulpfile.js` as outline [above](#issuecomment-250926867) & you're good to go.

**Comment by mattfanz** [comment]
@jhkueh Thanks you !
https://github.com/laravel/laravel/pull/3979/commits
I think laravel will update soon
