### ISSUE TITLE
Proposal: stop using `build` directory for `version` task

### ISSUE THREAD

**Issue by Gavrisimo** [laravel/elixir#66]
So at the moment when you run `version` like this, you'll get `public/build` directory with your `css/js` files:

```javascript
mix.version('css/all.css');
```

You end up with your "original" asset files, if you are like me they'll be in `public/assets/css` and `public/assets/js`, and same thing with different name, but in `public/build/assets/css` and `public/build/assets/js` directories.

What I propose is, in my opinion, much nicer way to do this. Given following in `gulpfile.js`:

```javascript
mix.version([
    'assets/css/all.css',
    'assets/js/all.js'
]);
```

We could do following for each specified file:

1. check if revision file already exist, if it does delete it
2. create revision file in same place where the file is

Then place `rev-manifest.json` to `public` folder, since there won't be any `build` directory.

```
public
├── rev-manifest.json
├── assets
|   ├── css
|   |   ├── all-906ce017.css
|   |   ├── all.css
|   |   └── all.css.map
|   └── js
|   |   ├── all-906ce017.js
|   |   ├── all.js
|   |   └── all.js.map
```

This way everything is in one place and you are not forcing users to fix `background-image` paths, since `build` folder caused `.css` files to gain on more level.

@JeffreyWay what are your thoughts on this? If you are ok with this I would love to try and get this to work... :)

**Comment by EspadaV8** [comment]
This would need a change within Laravel itself too. The `elixir` function is hardcoded to check `public_path() . '/build/rev-manifest.json'`. I do agree with the idea, I've just been looking for a solution to this problem myself.

**Comment by legshooter** [comment]
:+1: I would even go as far as choosing your own "build" dir, without the entire loop of the added build/path/to/files being created each time.

**Comment by Gavrisimo** [comment]
@EspadaV8 yeah, it's kinda weird that it is hardcoded to check for `public/build` *WHILE* you can specify your own buildDir path: https://github.com/laravel/elixir/blob/master/ingredients/version.js#L69-L77

@legshooter well if I understand what you mean, this proposal would take care of that in an implicit way... :) See how I have that `public/assets` folder in first comment? I'm specifying that path in my `sass` and `scripts` tasks and then for `version` task you just specify paths to those built assets. So what I'm saying is that you *are* specifying "build" dir when you use `sass` or `scripts`... :)

**Comment by EspadaV8** [comment]
Only you can't really set your own build path because it always adds a '/build' to the end of whatever you pass it.

**Comment by EspadaV8** [comment]
@Gavrisimo @legshooter I've opened up #70 that changes `version` to work like this. The only change that should be needed is to pass `'public'` in as the second parameter to the `version()` call.

I've (obviously) tested it myself, but if you get a chance would you be able to have a look and see if it works for you too.

If you have any suggestions on how to clean the code up as well that would be great.

**Comment by legshooter** [comment]
@Gavrisimo I like the addition of the explicit way @EspadaV8 is offering (if I understood you both correctly, hehe).

**Comment by tholu** [comment]
I guess this would also save the following issue:

If you use `.version()` and Boostrap3 (sass), you have to `.copy()` the glyphicon fonts to the build directory manually. However, if you use `gulp watch`, it deletes the whole build folder every time it recompiles and the font files are gone (since `.copy()` is not executed in `gulp watch`).

**Comment by irazasyed** [comment]
+1 for this. Had trouble with the image files like already mention by OP.

**Comment by miguelbalboa** [comment]
+1, In another gulpfile.js I try to put files in the build directory, but elixir delete them after version().

**Comment by jfsullivan** [comment]
+1, It would make it easier to develop my multi-tenant site where we need to build different CSS for each client.

**Comment by JeffreyWay** [comment]
Closing this, as we're working on it here: https://github.com/laravel/elixir/pull/70

**Comment by adamramadhan** [comment]
+1

**Comment by tholu** [comment]
@adamramadhan You have to `copy()` after `version()` - unfortunately `gulp watch` does not work anymore then (because it does only `version()` and deletes all files and not `copy()` afterwards).

**Comment by slakbal** [comment]
Any news on this proposal, I like the idea because of all the extra level issues. It implies e.g. font files to also go into the build folder or updates to all the relative paths which is just a pain again from all over.

**Comment by shaneparsons** [comment]
+1 for updates regarding this proposal.
The build folder just adds unnecessary confusion to the gulpfile and just linkage in general.

I don't understand why the version task doesn't just overwrite the un-versioned css / js.. it's not like they're needed if the versioned files are there..

**Comment by Rjs37** [comment]
mix.version('css/all.css', 'public');

Does actually produce what I'd expect: just a single versioned file in the correct directory (no build folder created), it also adds the rev-manifest file into the public directory.

It just seems to me that Laravel's elixir helper still uses a hardcoded build directory. So it's really an issue for that repo and not this one as far as I can tell?

**Comment by cspshadx** [comment]
+1. Changing images path just because of this is really stupid and annoying

**Comment by isaacperaza** [comment]
Guys, this solution is for every body that wants to user laravel-elixir in your projects or another frameworks, take a look: https://github.com/isaacperaza/elixir-busting

Elixir Busting does not create a build folder, it just place the versioned files next to the original source file.

@Gavrisimo I had the same problem as you and I totally agree with your proposal, I hope laravel-elixir creators could do this changes soon.

**Comment by Rjs37** [comment]
@isaacperaza You can get very close to what you are proposing using just laravel elixir. As I showed in my comment, you can get it to use the same directory already. It doesn't keep the original file though. That's the only real difference with what you've provided. Having that as an option for Elixir could be useful.

The main problem is just that Laravel's elixir helper doesn't support different directories being used for the versioned files. I was already using gulp with a custom asset service provider beforehand so I've just adapted that to work with elixir.

The recommendation for Laravel users seems to be to extend the application class and implement the change of behaviour for yourself. That way you can carry on using the same functions and if the situation changes (i.e. Taylor changes his mind) you can just remove the overriding of the function and keep everything working.

**Comment by isaacperaza** [comment]
@Rjs37 I created a merge request to elixir/master with a solution, take a look when you have time https://github.com/laravel/elixir/pull/328

**Comment by jaw-sh** [comment]
Please tell me this has been fixed. It's been almost a year.
