### ISSUE TITLE
Why clean-css? And how to change it?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [laravel/elixir#661]
Hi there!

After upgrading to 5.3, Elixir 6 became to use clean-css as the minifier plugin, which has a lot of issues. You can see in the clean-css repo a lot issues marked as "Enhanced", but actually most of them are critical bugs.

A simple "gulp --production" vanished 20% of my css styles, which broke the app. Even when setting all clean-css options to false, it made no difference at all. As reported in #649, looks like --production broke his app as well.

Is it possible to use a different css minifier in Elixir 6? I think Elixir 5 had cssnano by default.

Best regards,
Rafael Pacheco.

**Comment by rafael-renan-pacheco** [comment]
Playing around with this issue, I found that `gulp --production` misses half of my scss in the `mix.sass` array list.

I have the following list:

```js
mix.sass([
    "app.scss",
    "base.scss",
    "flex.scss",
    "login.scss",
    "label.scss",
    "callout.scss",
    "container.scss",
    "box.scss",
    "breadcrumb.scss",
    "description.scss",
    "documento.scss",
    "error-page.scss",
    "feedback.scss",
    "widget.scss",
    "button.scss",
    "header.scss",
    "info-box.scss",
    "list.scss",
    "loader.scss",
    "box-opcao.scss",
    "box-pessoa.scss",
    "sidebar.scss",
    "small-box.scss",
    "table.scss",
    "textarea.scss",
    "perfil.scss",
    "proposta.scss",
    "panel-protocolo.scss",
    "progress-bar.scss",
    "regra.scss",
    "simulador.scss",
    "well.scss",
    "flatpickr.scss",
    "magnific.scss",
    "parsley.scss",
    "selectize.scss",
    "sweetalert2.scss",
    "welcome.scss",
    "wenk.scss",
    "toastr.scss"], "public/css/all.css");
```

And after trial and error, I found that everything beyond `header.scss` is not saved in the final `all.css` file. Also, `app.scss` is a simple scss that includes node_modules scss extensions, like bootstrap, font-awesome, toastr. If I remove `app.scss` from the array list, all of scss files are minified as expected. If I keep `app.scss`, but erase all it's content (blank file), then everything up to `magnific.scss` is minified. If I keep `app.scss` with all @imports, and remove `header.scss`, then everything up to `info-box.scss` is minified, and everything beyond that are ignored.

Looks like `gulp --production` is limiting the amount of scss in some way. Just `gulp` works perfectly.

Any idea on what is happening here @JeffreyWay ?

Best regards,
Rafael Pacheco.

**Comment by JeffreyWay** [comment]
@rafael-renan-pacheco Can you not do mix.sass('app.scss'), and then have that file import all of those other little components?

**Comment by rafael-renan-pacheco** [comment]
Hi @JeffreyWay!

Same behavior. For each css I add I lose one custom scss.

As you requested, I removed app.scss and add just two imports from that file in the mix.sass command. This was the result:

```js
mix.sass([
    "../../../node_modules/bootstrap/dist/css/bootstrap.css",
    "../../../node_modules/animate.css/source/_base.css",
    "base.scss",
    "flex.scss",
    "login.scss",
    "label.scss",
    "callout.scss",
    "container.scss",
    "box.scss",
    "breadcrumb.scss",
    "description.scss",
    "documento.scss",
    "error-page.scss",
    "feedback.scss",
    "widget.scss",
    "button.scss",
    "header.scss",
    "info-box.scss",
    "list.scss",
    "loader.scss",
    "box-opcao.scss",
    "box-pessoa.scss",
    "sidebar.scss",
    "small-box.scss",
    "table.scss",
    "textarea.scss",
    "perfil.scss",
    "proposta.scss",
    "panel-protocolo.scss",
    "progress-bar.scss",
    "regra.scss",
    "simulador.scss",
    "well.scss",
    "flatpickr.scss",
    "magnific.scss",
    "parsley.scss",
    "selectize.scss",
    "sweetalert2.scss",
    "welcome.scss",
    "wenk.scss",
    "toastr.scss"], "public/css/all.css");
```

First I added only `bootstrap`, then `--production` went until `header.scss`.
Then I added `animate.css`, then `--production` went until `button.scss`, 1 file less.
So, to confirm the pattern, I added another css after animate.css, and the pattern was confirmed. `--production` went until `widget.scss`.

For each file I add in the beginning of `mix.sass` I lose one file at the end.

:weary:

**Comment by rafael-renan-pacheco** [comment]
Hi @JeffreyWay!

I added all scss import in the `app.scss` file, which now has node_modules and also my custom scss.

The result was this:

```js
mix.sass(["app.scss"], "public/css/all.css"); /* lots of @import here */
```

And `gulp --production` is now working fine. Also `gulp watch` is working fine this way. So it's a good alternative for this problem.

Since this is not related to clean-css as I thought it was, I'm closing this issue.

Thank you for your support!

Best regards,
Rafael Pacheco.
