### ISSUE TITLE
"throw er; // Unhandled stream error in pipe." error when run gulp

### ISSUE THREAD

**Issue by cuonghuynh** [laravel/elixir#662]
I have the error when run gulp at second time (see the attached image). At first, I run gulp and it works 

![](https://i.gyazo.com/fec0eb31d0ccfa2e61a54d9fe8fba7f0.png)

System:
- Windows 10
- Vagrant
- Node 6.6.&
- Npm 3.*

**Comment by cuonghuynh** [comment]
Seems that only get errors in vagrant. I have updated node to latest version (6.x) 
Do steps on my machine windows 10  (not vagrant): 
- removed **node_modules** folder
- run **npm install**

Finally it works.

**Comment by daverdalas** [comment]
@cuonghuynh Is the problem did not show up again? I also use Vagrant (Laravel Homestead) and this error occurs very often. I tried the solution proposed by you but nothing helped. I noticed that the problem appears when setting NFS option for shared folder. Unfortunately, without this option vagrant works very slowly :( Maybe someone somehow coped with this problem.
