### ISSUE TITLE
Multiple elixir calling ruins webpack build

### ISSUE THREAD

**Issue by tam5** [laravel/elixir#668]
I have had a package which extends elixir by wrapping up and using some of the built in elixir functions (meaning the package itself uses mix.scripts etc. rather than rewriting the same tasks).

However, if I do this:

```javascript
elixir.extend('speak', function (message) {
  elixir(mix => {
    console.log(message);
  });
});

elixir(mix => {
    mix.sass('app.scss')
       .speak('Hello, World!')
       .webpack('app.js');
});
```
I get the error:

> [Vue warn]: Failed to mount component: template or render function not defined. (found in component <example>)

If I simply comment out the part where I call elixir, then everything loads fine (change the first part to this):

```javascript
elixir.extend('speak', function (message) {
  console.log(message);
});
```

I am trying to understand this behavior but so far I have not been able to figure it out, or how to solve the issue. Any explanations would be helpful, or perhaps suggest an alternative way to reuse elixir recipes?

(Laravel 5.3.18, Laravel-Elixir 6.0.0-11, Laravel-Elixir-Webpack 1.0.8, Vue 2.0.1)

**Comment by maxxscho** [comment]
I have a similar problem. In my fresh Laravel installation, I have a very basic gulpfile:
````
elixir(mix => {
    mix.browserSync({
        proxy: 'example.dev',
        open: false
    });
});

elixir(mix => {
    mix.sass('app.scss');
    mix.webpack('app.js');
});
````
The two elixir calls are breaking webpack and I get the same error. If I change it into one elixir call, like this:
````
elixir(mix => {
    mix.sass('app.scss');
    mix.webpack('app.js');
    mix.browserSync({
        proxy: 'example.dev',
        open: false
    });
});
````
everything works fine.

**Comment by JeffreyWay** [comment]
You should only call the elixir() function once.

**Comment by gpressutto5** [comment]
I have the same problem, but I'm calling the elixir function only once.

    const gulp = require('gulp');
    const elixir = require('laravel-elixir');
    require('laravel-elixir-vue-2');
    require('laravel-elixir-webpack-official');
    
    const webpack = require('webpack');
    const WebpackDevServer = require('webpack-dev-server');
    
    const webpackConfig  = require('./webpack.config');
    const webpackDevConfig  = require('./webpack.dev.config');
    
    const mergeWebpack = require('webpack-merge');
    
    
    Elixir.webpack.config.module.loaders = [];
    Elixir.webpack.mergeConfig(webpackConfig);
    Elixir.webpack.mergeConfig(webpackDevConfig);
    
    gulp.task('webpack-dev-server', () => {
        let config = mergeWebpack(webpackConfig, webpackDevConfig);
        let inlineHot = [
            'webpack/hot/dev-server',
            'webpack-dev-server/client?http://192.168.10.10:8080'
        ];
        config.entry.admin = [config.entry.admin].concat(inlineHot);
        new WebpackDevServer(webpack(config), {
            hot: true,
            proxy: {
                '*': 'http://192.168.10.10'
            },
            watchOptions: {
                poll: true,
                agregateTimeout: 300
            },
            publicPath: config.output.publicPath,
            noInfo: true,
            stats: { colors: true }
        }).listen(8080, "192.168.10.10", () => {
            console.log('Bundling project...');
        });
    });
    
    elixir(mix => {
        mix.sass('./resources/assets/admin/sass/admin.scss')
            .copy('./node_modules/materialize-css/fonts/roboto', './public/fonts/roboto');
        gulp.start('webpack-dev-server');
        mix.browserSync({
            proxy: 'http://192.168.10.10:8080',
            open: false
        });
    });

**Comment by raphcadiz** [comment]
hey guys, I'm getting the same problem that "Failed to load components". I call elixir() once also because it was the default during installation but I can't get it working still.
