### ISSUE TITLE
Don't make elixir a sub-universe.

### ISSUE THREAD

**Issue by lukasoppermann** [laravel/elixir#67]
Hey @JeffreyWay,

I think it is a pretty nice idea to give laravel users some gulp magic out of the box, but I am wondering if it is wise and nice to do it in such a exclusive way.

Let me explain:
At the moment, I have a choice, either I use elixir with nice things like asset versioning, or I use my own gulp setup. My only options are: 1. write elixir ingredients for everything I want to use, 2. have separate gulp workflows for my added stuff.

If I want to port this gulp stuff to other projects, I can not bring everything, because parts are tightly coupled to elixir. Why don't you just write all the ingredients as nice gulp plugins instead and just build a good gulpfile to start with?

If you think the gulpfile will look to scary for beginners, you could still build separate plugins and just wrap them in an elixir function. This would mean people can go with elixir, but also use the plugins within their normal gulp workflow, and add them to other tasks, have a different default task, etc.

I would appreciate you considering this, thanks. :)

**Comment by legshooter** [comment]
:+1:

**Comment by Gavrisimo** [comment]
@lukasoppermann 

>If I want to port this gulp stuff to other projects, I can not bring everything, because parts are tightly coupled to elixir.

Why don't you bring the entire elixir as dependency to those other projects, and then just use what you need? It's not like this is being used in browser so it can affect visitors of your site... :)

Or am I missing your point?

**Comment by lukasoppermann** [comment]
Well, this is one part. I know I could do this, but it adds an overhead for other devs who know gulp but don't know elixir. And you still need to write elixir ingredients and are pretty restricted in your usage, like defining different gulp tasks, etc.

Since Laravel is all about sharing with the community, and reusing packages in php, I don't see why it makes sense to build a new eco-system in js.

I really like the elixir modules and I would like to use them with straight gulp. I know I could port them, but then you have duplicated components again.

**Comment by jdgriffith** [comment]
:+1:

**Comment by JeffreyWay** [comment]
> ...and just build a good gulpfile to start with?

Because this would defeat the whole purpose of us building Elixir. 

We're not building a new eco-system. Elixir is a small wrapper around Gulp to make the most common tasks that 80% of devs require as simple as possible. These tasks are fairly simple at their core.

**Comment by lukasoppermann** [comment]
Hmm, I thought you could maybe alter stuff so that one can use for e.g. the .version() in a normal gulpfile but also in elixir. This was what I was thinking about, because then one can just use gulp setups from other projects and mix it with the laravel defaults, which are pretty nice.

**Comment by spronkey** [comment]
Hmm, I tend to agree. Came here looking for some docs on how Elixir'd tdd command actually works, lots of indirection in there.

A basic gulpfile to me would actually be just as simple...
