### ISSUE TITLE
npm ERR! Maximum call stack size exceeded on "npm install --no-bin-links"

### ISSUE THREAD

**Issue by fpinger** [laravel/elixir#675]
[npm-debug.log.txt](https://github.com/laravel/elixir/files/552235/npm-debug.log.txt)

Hi,
I tried to install Laravel Elixir on win 7.
Command: npm install --no-bin-links
Error messages:

> C:\projects\domains\quester>npm install --no-bin-links
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in
>  the tree.
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> 
> npm ERR! Maximum call stack size exceeded
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\projects\domains\quester\npm-debug.log

**Comment by terrylow** [comment]
@fpinger i have the same problem too, but once remove --no-bin-links, it install without any problem

**Comment by fpinger** [comment]
@terrylow thank you. Everything worked out.
