### ISSUE TITLE
Proposal: Separate similar tasks into groups?

### ISSUE THREAD

**Issue by Gercoli** [laravel/elixir#68]
I like to generate separate javascript files that should be loaded at different times in my document, for instance a vendor.js that is loaded in the ***head*** of a document, and app.js that gets loaded before the closing of ***body***. This is pretty common. This requires two separate mix.scripts() calls, which I do, but when any script gets modified, all scripts in each of the calls get all of their tasks ran. If you're versioning, they get re-hashed and new source maps are generated, if you do minification/compression that is also re-ran.

I've started writing extensions for elixir, and I've noticed that the my script is getting fed all of these files whenever any script is modified (even when it's not in the same .scripts() call), so the only way my extension can really tell if the file has in fact been modified is by getting the hash of the file (since the modification time on the filesystem has also changed).. I find this to be inefficient for large files.

Would it be possible to split separate .scripts() into their own groups so only those scripts get re-ran upon modification or Is there a reason NOT to do this?

**Comment by JeffreyWay** [comment]
This will be added to the next release of Elixir, very likely. Sorry for delay in responding.
