### ISSUE TITLE
mix.webpack('app.js'); doesn't work properly

### ISSUE THREAD

**Issue by aleixfabra** [laravel/elixir#680]
Node: 4.6.1
Npm: 2.15.9

-------------------------------------------------------------------------------------
{ [Error: Entry module not found: Error: Can't resolve 'buble' in '/Users/aleix/www/demo'
resolve 'buble' in '/Users/aleix/www/demo'
  Parsed request is a module
  using description file: /Users/aleix/www/demo/package.json (relative path: .)
  after using description file: /Users/aleix/www/demo/package.json (relative path: .)
    resolve as module
      module variation buble-loader
        /Users/aleix/www/node_modules doesn't exist or is not a directory
        /Users/aleix/node_modules doesn't exist or is not a directory
        /Users/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
        looking for modules in /Users/aleix/www/demo/node_modules
          using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)
          after using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)
            using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules/buble-loader)
              as directory
                /Users/aleix/www/demo/node_modules/buble-loader doesn't exist
              no extension
                /Users/aleix/www/demo/node_modules/buble-loader doesn't exist
              .js
                /Users/aleix/www/demo/node_modules/buble-loader.js doesn't exist
              .json
                /Users/aleix/www/demo/node_modules/buble-loader.json doesn't exist
      /Users/aleix/www/node_modules doesn't exist or is not a directory
      /Users/aleix/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/aleix/www/demo/node_modules
        using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)
        after using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)
          using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules/buble)
            as directory
              /Users/aleix/www/demo/node_modules/buble doesn't exist
            no extension
              /Users/aleix/www/demo/node_modules/buble doesn't exist
            .js
              /Users/aleix/www/demo/node_modules/buble.js doesn't exist
            .json
              /Users/aleix/www/demo/node_modules/buble.json doesn't exist]
  message: 'Entry module not found: Error: Can\'t resolve \'buble\' in \'/Users/aleix/www/demo\'\nresolve \'buble\' in \'/Users/aleix/www/demo\'\n  Parsed request is a module\n  using description file: /Users/aleix/www/demo/package.json (relative path: .)\n  after using description file: /Users/aleix/www/demo/package.json (relative path: .)\n    resolve as module\n      module variation buble-loader\n        /Users/aleix/www/node_modules doesn\'t exist or is not a directory\n        /Users/aleix/node_modules doesn\'t exist or is not a directory\n        /Users/node_modules doesn\'t exist or is not a directory\n        /node_modules doesn\'t exist or is not a directory\n        looking for modules in /Users/aleix/www/demo/node_modules\n          using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)\n          after using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)\n            using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules/buble-loader)\n              as directory\n                /Users/aleix/www/demo/node_modules/buble-loader doesn\'t exist\n              no extension\n                /Users/aleix/www/demo/node_modules/buble-loader doesn\'t exist\n              .js\n                /Users/aleix/www/demo/node_modules/buble-loader.js doesn\'t exist\n              .json\n                /Users/aleix/www/demo/node_modules/buble-loader.json doesn\'t exist\n      /Users/aleix/www/node_modules doesn\'t exist or is not a directory\n      /Users/aleix/node_modules doesn\'t exist or is not a directory\n      /Users/node_modules doesn\'t exist or is not a directory\n      /node_modules doesn\'t exist or is not a directory\n      looking for modules in /Users/aleix/www/demo/node_modules\n        using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)\n        after using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules)\n          using description file: /Users/aleix/www/demo/package.json (relative path: ./node_modules/buble)\n            as directory\n              /Users/aleix/www/demo/node_modules/buble doesn\'t exist\n            no extension\n              /Users/aleix/www/demo/node_modules/buble doesn\'t exist\n            .js\n              /Users/aleix/www/demo/node_modules/buble.js doesn\'t exist\n            .json\n              /Users/aleix/www/demo/node_modules/buble.json doesn\'t exist',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

**Comment by JeffreyWay** [comment]
First update your Node and npm dependencies to their latest versions, and see if that changes the error. You have some outdated installs.

**Comment by aleixfabra** [comment]
It has been fixed by updating the node version.
