### ISSUE TITLE
Extending web pack

### ISSUE THREAD

**Issue by prakashchokalingam** [laravel/elixir#683]
I have this codes in my gulp.js

        elixir(mix => {
           // for auth
            mix.sass('auth/auth.scss');
           mix.webpack('auth/auth.js', {
           module: {
              loaders: [
                 {test:/\.css$/, loader: 'style!css'}
               ]
            }
         });

But when I do gulp watch terminal throws the below error ,

       throw new TypeError('parse-filepath expects a string');
       ^
        TypeError: parse-filepath expects a string

How should I extend webpack exlixir ?

**Comment by elpete** [comment]
You should be able to pass a configuration to be merged as the 4th parameter.

See also https://www.laravel.com/docs/5.3/elixir#webpack and https://github.com/JeffreyWay/laravel-elixir-webpack-official for other ways of accomplishing the same task.
