### ISSUE TITLE
Pass argument to gulp tdd --filter="FooControllerTest"

### ISSUE THREAD

**Issue by cmosguy** [laravel/elixir#686]
@JeffreyWay Is there a way to specify an argument in the phpunit command for the --filter=""?  I would like to somehow how do `gulp tdd --filter=""` and pass that through to the phpunit at the command line.  is this possible?

Cheers!

**Comment by JeffreyWay** [comment]
No, you can't do that at the moment. Probably best to defer to the regular `phpunit --filter` for those sorts of things.
