### ISSUE TITLE
@import not working with sass

### ISSUE THREAD

**Issue by robertmylne** [laravel/elixir#688]
_Latest versions of everything._

app.scss
```
@import "../../../../node_modules/semantic-ui/dist/semantic.css";
```
gulpfile.js
```
mix.sass('editor/app.scss', 'public/css/editor/app.css')
```
compiled app.css
```
@import url(../../../../node_modules/semantic-ui/dist/semantic.css);

/*# sourceMappingURL=app.css.map */
```

As you can see the app.css isn't importing the file contents correctly.

**Comment by terrylow** [comment]
is this happen only when your doing gulp --production ?

try to add the following statement after require elixir

`Elixir.config.css.minifier.pluginOptions = {processImport: false};`

in case you are interested in where these options come from, please refer to clean-css docs [https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api)

**Comment by robertmylne** [comment]
It is happening for both: ```gulp``` & ```gulp --production```.

Your fix also did not help.

**Comment by robertmylne** [comment]
Worked it out.

This
```@import "../../../../node_modules/semantic-ui/dist/semantic.css";```

Needed to be this
```@import "../../../../node_modules/semantic-ui/dist/semantic";```
