### ISSUE TITLE
Watchers of same name + watcher fire exponentially

### ISSUE THREAD

**Issue by desicochrane** [laravel/elixir#693]
**[⚠️PR with fix here⚠️](https://github.com/laravel/elixir/pull/692)**

A bug whereby watching tasks of the same name with the same watching directory means they will be fired exponentially!

This is because during `gulp watch` when a matching watcher file pattern triggers its task, then each task will then proceed to run all tasks with the same name.

By indicating that a particular task is currently being "watched" and flagging whether elixir is in "watch mode" or not, this PR attempts to only fire the task being watched (and not all with the same name) when elixir is in watch mode.

## Steps to reproduce the bug:
1. create 2 new files: `resources/assets/sass/a.scss` and `resources/assets/sass/b.scss` both with the contents:
    ```scss
    @import "app";
    ```
1. in your gulpfile:
    ```js
    elixir((mix) => {
        mix.sass('a.scss')
           .sass('b.scss');
    });
    ```
1. run `gulp watch`
1. You should see no problem at this point ✅
1. Make a change to `resources/assets/sass/app.scss`
1. check the terminal, you should see gulp has done compiled `a.scss` and `b.scss` twice! 🐛

**Comment by JeffreyWay** [comment]
Closing, since your PR was merged.
