### ISSUE TITLE
How disable minify (uglify) in production?

### ISSUE THREAD

**Issue by drozdzynski** [laravel/elixir#694]
Hello,

how can I disable minify (uglify) of js files in production.

**Comment by JeffreyWay** [comment]
Don't run `gulp --production`. Just do `gulp`.

**Comment by drozdzynski** [comment]
I want to be run with production to minify CSS but without uglify JS.

**Comment by JeffreyWay** [comment]
`mix.combine()` will combine any number of scripts, without applying minification. But, for Webpack or Browserify, those will always receive automatic minification when you run `gulp --production`.

**Comment by briedis** [comment]
My case is like this - I have a JS error, but it is imossible to debug in production with uglified code. So I would like to see combined + versioned code. If I run without --production, it does not get versioned and the wrong version loads on production.
