### ISSUE TITLE
Error: spawn node_modules/webpack/bin/webpack.js ENOENT

### ISSUE THREAD

**Issue by ItsRD** [laravel/elixir#710]
I've got this error when running `npm run dev` and I've no idea what the problem could be. I've tried removing the node_modules folder and running `npm install` again, but non of that work. 

Versions:
NPM: 4.1.2
Node: 7.4.0

Package.json dependencies
```
"devDependencies": {
    "axios": "^0.15.2",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.1.4",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.5.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1"
  }
```

webpack.mix.js

```
const { mix } = require('laravel-mix');


mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');
```

**Comment by ItsRD** [comment]
Okay I fixed this problem just after posting this issue.. (been searching 2 hours before posting an issue).

I don't really get why Jeffrey can install those dependencies so easily in his tutorials and I've always troubles and have to add a lot more dependencies...?

**Comment by JCarlosR** [comment]
@ItsRD Did you find an answer?

I am also adding dependencies manually.

**Comment by ItsRD** [comment]
I had this enabled: `npm set legacy-bundling=true`, but that broke it
