### ISSUE TITLE
Default resource paths

### ISSUE THREAD

**Issue by FatBoyXPC** [laravel/elixir#72]
LESS: resources/assets/less
SASS: resources/assets/sass
CSS: resources/css
JS: resources/js

Can we make this more consistent?

**Comment by JeffreyWay** [comment]
That's what Taylor wanted. CSS and JS aren't being compiled, so they don't go in the assets directory.

**Comment by FatBoyXPC** [comment]
But they do get handled by elixir, and copied into the public directory. I
feel like this isn't intuitive at all (although it is documented).
