### ISSUE TITLE
[Proposals] Manage TypeScript Compilation

### ISSUE THREAD

**Issue by RomainLanz** [laravel/elixir#78]
Hey @JeffreyWay,

Is it possible to handle TypeScript compilation like CoffeeScript?

https://github.com/Microsoft/TypeScript

Thanks.

**Comment by tymondesigns** [comment]
There is already an [extension for this](https://www.npmjs.com/package/laravel-elixir-typescript)

**Comment by RomainLanz** [comment]
Oooh, perfect, thanks @tymondesigns!
