### ISSUE TITLE
Copy not executed on watch

### ISSUE THREAD

**Issue by bastiaan89** [laravel/elixir#79]
In my gulpfile, I copy the ``resources/css`` folder to ``public/css`` for development. This works fine when just running ``gulp``, however with ``gulp watch``, it just compiles my less files to ``resources/css``. I understand it only runs those tasks for which the input files are changed, but shouldn't that include the copy task as well? (even though they are changed by elixir, not by myself).

**Comment by JeffreyWay** [comment]
This is a tough one. But the reason is because, if you're copying lots of files as part of your Gulpfile, you probably don't want to re-copy those things *every* single time you save a file...

**Comment by boyd91** [comment]
I understand the difficulties. Does elixir provide any other way of executing an post compile script?

**Comment by tkahl** [comment]
I have the same problem... I use the version function and need to copy some files in the newly created build directory. With "watch", this copy command is not executed - so the files are missing :(

**Comment by davidhemphill** [comment]
@JeffreyWay Just wanted to chime in here. I wanted to use Elixir for my Laravel package and if the copy task would have the ability to run with the watch task, that would save me from having to manually publish the files every time there's a CSS change. Just a thought :-)

**Comment by vedmant** [comment]
I have the same problem, for example I have some images I use in css, firstly I have to add command to copy all images to build directory, secondly I have to launch gulp manually each time I add new image or edit css where I use this images.

**Comment by oflannabhra** [comment]
Anyway we could get configuration option to do this? I also have a use case (which I realize is probably a marginal use case) where having `gulp watch` copy changed files would be very handy.

**Comment by JeffreyWay** [comment]
There's a watcher now for copying tasks. Upgrade to ^3.0.0.

**Comment by davidhemphill** [comment]
@JeffreyWay Thank you! You're a kind and humble human being.

**Comment by MozMorris** [comment]
@JeffreyWay the watcher in ^3.0.0 works great, thank you.  

The copy doesn't run on the initial `gulp watch`. Of course I'm assuming there's nothing wrong with my config...

```js
elixir(function(mix) {
	mix.copy('vendor/twbs/bootstrap/dist/js/bootstrap.min.js', 'public/js/vendor');
});
```

**Comment by bretmette** [comment]
@MozMorris I believe the only task run when `gulp watch` is executed is `browserSync.init` this is intentional. Other tasks are only invoked by `gulp watch` when a change is detected, tasks are not run when watch is started.

 Also I understand this is a very old comment but, I replied  incase someone comes across this on a search for information.
