### ISSUE TITLE
Proposal: Allow functions in config.watchers

### ISSUE THREAD

**Issue by Skyrpex** [laravel/elixir#81]
Hi!

I'm trying to create a browserify ingredient (along with watchify). Currently, the watch-assets task calls gulp.watch, and this won't allow to use a custom task like watchify when calling gulp watch.

This is the current watch-assets task:

```javascript
gulp.task('watch-assets', function() {
    for (var task in srcPaths) {
        gulp.watch(srcPaths[task], [task]);
    }
});
```

If we change it to this code, it would allow developers to register functions with complex code to be called when watch is scheduled:

```javascript
gulp.task('watch-assets', function() {
    for (var task in srcPaths) {
        if (_.isFunction(srcPaths[task])) {
            srcPaths[task].call(this);
        } else {
            gulp.watch(srcPaths[task], [task]);
        }
    }
});
```

Then, I would use this code in my browserify ingredient:

```javascript
this.registerWatcher('browserify', function() {
  createWatchifyBundle();
});
```

**Comment by JeffreyWay** [comment]
Merged.
