### ISSUE TITLE
multi sass files when using rubySass

### ISSUE THREAD

**Issue by SimonJ** [laravel/elixir#83]
Ok, just made a quick test :
```
mix.sass(['resources/assets/sass/admin.scss','resources/assets/sass/main.scss']);
```
Works.
----------------------

```
mix.rubySass(['resources/assets/sass/admin.scss','resources/assets/sass/main.scss']);
```
Falis.

Im i the only one having this problem?

**Comment by JeffreyWay** [comment]
It's an issue with the gulp-ruby-sass Gulp plugin. We have to wait for them to update it.

> "gulp-ruby-sass doesn't support globs yet, only single files or directories. Just like Sass."

https://github.com/sindresorhus/gulp-ruby-sass

**Comment by graciano** [comment]
@SimonJ Did you created an issue there? If so, please link it here. I'm having the same problem that you had [here](https://laracasts.com/discuss/channels/general-discussion/how-to-have-multi-sass-files-when-using-rubysass).

**Comment by SimonJ** [comment]
Hey @graciano its not a problem any more they updated rubySass so it works now

**Comment by graciano** [comment]
I updated it here and it's working, thanks ;)
