### ISSUE TITLE
Bug: sourceMappingURLs are broken after versioning

### ISSUE THREAD

**Issue by nlogachev** [laravel/elixir#87]
- **mix.coffee**: resources/js/app/foo.coffee **-> becomes ->** public/js/app/foo.js
  - public/js/app/foo.js has `//# sourceMappingURL=../app/foo.js.map`
- **mix.version**: public/js/app/foo.js **-> becomes ->** public/build/js/app/foo-XXXXX.js
  - public/build/js/app/foo-XXXXX.js has `//# sourceMappingURL=../app/foo.js.map`

The sourceMappingUrl in the versioned file will never be found since the relative file location doesn't exist. The .map files are also versioned inside public/build/**

**Comment by briedis** [comment]
Voting for this.

**Comment by briedis** [comment]
Looks like there is just a slash forgotten in the path when copying.

![Image](http://i.imgur.com/mZr1S4O.png)

Because if there were a slash, map files would end up in the correct directories.

As a temporary solution, you can copy map files manually with copy commad.

```
mix.copy(baseDist + 'buildcss/*.map', baseDist + 'build/css');
mix.copy(baseDist + 'buildjs/*.map', baseDist + 'build/js');
```

Correc the path as needed (I use elixir in a custom project, I dont know the correct paths for laravel)

**Comment by briedis** [comment]
Any status on this? Makes JS/CSS debugging really hard :(

**Comment by JeffreyWay** [comment]
I just tested out:

```
mix.coffee('foo.coffee')
       .version('public/js/app.js');
```

and everything was in its proper location, using the latest version of Elixir.

http://d.pr/i/xAj4

Closing, unless you guys can give me more info, or an example.

**Comment by briedis** [comment]
This is a clean install:

![Screenshot](https://ziedlejas.lv/screenshots/img.2015.06.30.KZPQZm.png)

You can see dist is the target directory, but the sourcemap is in a strange directory.

Maybe I'm doing something wrong?

Gulpfile contents:
```
var elixir = require('laravel-elixir');

var baseDist = './assets/dist/';
var baseSrc = './assets/src/';
var targetFile = baseDist + 'js/compiled.js';

elixir.config.publicDir = baseDist;

elixir(function(mix){
	mix.scripts(
		[
			'js/test.js',
			'js/test2.js'
		],
		targetFile,
		baseSrc
	);

	mix.version([targetFile]);
});
```

Just create src directory and two sample files to be compiled.

Regards, 
Martin

**Comment by briedis** [comment]
@JeffreyWay did you have a chance to try it out?
