### ISSUE TITLE
Bug: strange interaction between multiple scripts() and version()

### ISSUE THREAD

**Issue by nlogachev** [laravel/elixir#88]
@JeffreyWay this is a weird one and I've had it happening since starting to use Elixir early this year...

```
elixir(function(mix) {
	mix.scripts([
			'transition.js',
			'modal.js'
		], 'public/js/vendor/bootstrap.js', 'bower_components/bootstrap-sass-official/assets/javascripts/bootstrap')
		.scripts([
			'app.js',
			'app/Controllers/*',
			'init.js'
		], 'public/js','public/js')
		.version('js/all.js');
});
```
In the code above, **only** the following combinations work:
- Only the first `scripts` call **with** the `version` call (adjusted to js/vendor/bootstrap.js). *Script combination and versioning succeeds.*
- Only the second `scripts` call **with** the `version` call. *Script combination and versioning succeeds.*
- Each `scripts` call in isolation (without the other and without the version call). *Script combination succeeds.*

If I try **all three together**, then both `scripts` calls succeed, but the **versioning doesn't happen**! What's more, if I take out the `version` and put it into a separate mix in the end (like below), **only the css versioning works**! :hushed: 

```
elixir(function(mix) {
	mix.version([
		'css/app.css',
		'js/all.js'
	]);
});
```

**Comment by constb** [comment]
I have similar issue. It seems like a race condition to me, because if I run ``gulp version`` later it fixes bad versioning made by ``gulp``.

**Comment by nlogachev** [comment]
Fixed in one of the latest versions,
