### ISSUE TITLE
logTask text color(gutil.colors.black)

### ISSUE THREAD

**Issue by spajz** [laravel/elixir#91]
Hi,
text color for logTask (gutil.colors.black)  in my case is the same as background. It is normal behavior?

![cmd](https://cloud.githubusercontent.com/assets/801824/6979956/631c6b28-d9eb-11e4-8e21-d140df601bfb.jpg)

**Comment by JeffreyWay** [comment]
That's weird. I was under the impression that it compensates for a black background and adjusts the color. I'll try to work something out.
