### ISSUE TITLE
Pass options to bowserify task

### ISSUE THREAD

**Issue by jorisnoo** [laravel/elixir#92]
In order to use browserify within a _subfolder_ in `resources/js`, I want to be able to pass `options.paths` – otherwise modules with paths relative to the subfolder won't be found.

**Comment by JeffreyWay** [comment]
You can now pass Browserify options as the fourth argument to mix.browserify().

**Comment by jorisnoo** [comment]
thank you, Jeffrey! 👍

**Comment by jorisnoo** [comment]
In addition, would it be possible to use any other transform method when running browserify? E.g. `.transform(hbsfy)`.
