### ISSUE TITLE
Bug: [0.16.3] Scripts wildcard works but throws error

### ISSUE THREAD

**Issue by nlogachev** [laravel/elixir#95]
```
// public/js/bar/ folder contains bar.js, baz.js
mix.scripts(['foo.js','bar/*'], 'public/js','public/js');
```

The files `foo.js`, `bar/bar.js`, `bar/baz.js` **do** get be merged into `public/js/all.js`as expected, but the gulp output still throws an error:

`File not found: public/js/bar/*`

**Comment by JeffreyWay** [comment]
Can you do `npm update` and let me know if this is still an issue on your end?

**Comment by nlogachev** [comment]
@JeffreyWay 
Can't test it at the moment... 0.18.1-0.18.2 have the following error:

```
TypeError: Object resources/assets/sass/**/*.+(sass|scss) has no method 'forEach'
    at module.exports (/Users/N/Code/p/node_modules/laravel-elixir/ingredients/commands/CompileCSS.js:74:9)
```

:smile:
