### ISSUE TITLE
Bug: [0.18.2] .sass() has no method forEach

### ISSUE THREAD

**Issue by nlogachev** [laravel/elixir#96]
0.18.1-0.18.2 have the following error:

```
TypeError: Object resources/assets/sass/**/*.+(sass|scss) has no method 'forEach'
    at module.exports (/Users/N/Code/p/node_modules/laravel-elixir/ingredients/commands/CompileCSS.js:74:9)
```

**Comment by JeffreyWay** [comment]
Can you show me your Gulpfile, and what you specifically passed to `mix.sass()`?

**Comment by nlogachev** [comment]
@JeffreyWay Cheers! In 0.18.3: sass() works, coffee() works, multiple scripts() work, yay! :+1:
