### ISSUE TITLE
Making Sourcemaps Opt-In?

### ISSUE THREAD

**Issue by JeffreyWay** [laravel/elixir#97]
Thinking about making the sourcemaps stuff opt-in. A lot of people don't even know what these "*.map" files are. Might be confusing to them.

Anyhow have a problem with this? You'd only need to add one call to enable sourcemaps.

**Comment by tymondesigns** [comment]
Agreed.. I think the people who know why they need sourcemaps, wouldn't mind adding an option.

As opposed to people who are thinking "what the hell is this .map file for?"
